// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public readonly struct CopeResult<TValue, TError>
{
    private readonly TValue _value;
    private readonly TError _error;
    public bool IsOk { get; }

    public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException("Result has no value.");
    public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException("Result has no error.");

    private CopeResult(bool isOk, TValue value, TError error)
    {
        IsOk = isOk;
        _value = value;
        _error = error;
    }

    public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);
    public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);
}

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(__CopeRecord_r2[] value0)
    {
        __field_r1_002Ef0 = value0;
    }

    internal __CopeRecord_r2[] __field_r1_002Ef0 { get; }
}

public sealed class __CopeRecord_r2
{
    internal __CopeRecord_r2(string value0, string value1, double value2)
    {
        __field_r2_002Ef0 = value0;
        __field_r2_002Ef1 = value1;
        __field_r2_002Ef2 = value2;
    }

    public string __field_r2_002Ef0 { get; }

    internal string __field_r2_002Ef1 { get; }

    public double __field_r2_002Ef2 { get; }
}


public abstract record PersonError
{
    protected PersonError()
    {
    }

    public sealed record InvalidAge(double age) : PersonError;

}

public static class CopelandModule
{
    public static CopeResult<__CopeRecord_r2, PersonError> Person__constructor(string name, double age)
    {
        if ((age < 0.0))
        {
            return CopeResult<__CopeRecord_r2, PersonError>.Err(new PersonError.InvalidAge(age));
        }
        var __cope_record_init_0 = name;
        var __cope_record_init_1 = Person__normalize(name);
        var __cope_record_init_2 = age;
        return CopeResult<__CopeRecord_r2, PersonError>.Ok(new __CopeRecord_r2(__cope_record_init_0, __cope_record_init_1, __cope_record_init_2));
    }

    public static string Person__normalize(string name)
    {
        return name;
    }

    public static __CopeRecord_r2 Person__birthday(__CopeRecord_r2 person)
    {
        var __cope_record_source_0 = person;
        var __cope_record_replacement_1 = ((person).__field_r2_002Ef2 + 1.0);
        return new __CopeRecord_r2(__cope_record_source_0.__field_r2_002Ef0, __cope_record_source_0.__field_r2_002Ef1, __cope_record_replacement_1);
    }

    public static double Person__identity__primitive_number__7F14E33913752003(double value)
    {
        return value;
    }

    public static string label__record_Person__66BA86D43998F2CA(__CopeRecord_r2 value)
    {
        return (value).__field_r2_002Ef0;
    }

    public static string main()
    {
        string __cope_try_result_h1_0;
        PersonError __cope_try_error_h1_0 = default!;
        {
            var __cope_tmp0 = Person__constructor("Ada", 41.0);
            if (!__cope_tmp0.IsOk)
            {
                __cope_try_error_h1_0 = __cope_tmp0.Error;
                goto __cope_try_handler_h1_0;
            }
            __CopeRecord_r2 person = __cope_tmp0.Value;
            var __cope_record_init_1 = new __CopeRecord_r2[] { person };
            __CopeRecord_r1 envelope = new __CopeRecord_r1(__cope_record_init_1);
            __CopeCallable_2C53F04DF4CB97A3C71FD0C1C5AF58ADB023C292F13B5619E3C8673500669286 birthday = (__CopeCallable_2C53F04DF4CB97A3C71FD0C1C5AF58ADB023C292F13B5619E3C8673500669286)Person__birthday;
            __CopeRecord_r2 older = birthday(person);
            double age = Person__identity__primitive_number__7F14E33913752003((older).__field_r2_002Ef2);
            __cope_try_result_h1_0 = label__record_Person__66BA86D43998F2CA(older);
            goto __cope_try_join_h1_0;
        }
        __cope_try_handler_h1_0:
        {
            var error = __cope_try_error_h1_0;
            {
                __cope_try_result_h1_0 = "recovered";
                goto __cope_try_join_h1_0;
            }
        }
        __cope_try_join_h1_0:
        return __cope_try_result_h1_0;
    }

}
