<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TinyFarm.Core/TinyFarm.Core.csproj" />
    <ProjectReference Include="../../Aurelian/Aurelian.Runtime/Aurelian.Runtime.csproj" />
    <ProjectReference Include="../../Aurelian/Aurelian.Audio/Aurelian.Audio.csproj" />
    <ProjectReference Include="../../Copeland/Copeland.TS/Copeland.TS.csproj" />
    <PackageReference Include="Dominatus.Core" />
    <PackageReference Include="Dominatus.OptFlow" />
    <PackageReference Include="Ariadne.OptFlow" />
    <PackageReference Include="DotRecast.Detour" />
    <PackageReference Include="DotRecast.Recast" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Content/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Content/M12/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Content/M14/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Content/M18/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Content/M19/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Content/M20/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Content/M21/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
