<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TinyFarm.Core/TinyFarm.Core.csproj" />
    <ProjectReference Include="../../Aurelian/Aurelian.Runtime/Aurelian.Runtime.csproj" />
    <ProjectReference Include="../../Aurelian/Aurelian.Audio/Aurelian.Audio.csproj" />
    <ProjectReference Include="../../Aurelian/Aurelian.Effects2D/Aurelian.Effects2D.csproj" />
    <ProjectReference Include="../../Aurelian/Aurelian.Simulation/Aurelian.Simulation.csproj" />
    <ProjectReference Include="../../Copeland/Copeland.TS/Copeland.TS.csproj" />
    <ProjectReference Include="../../../../Deliverance/src/Deliverance.Core/Deliverance.Core.csproj" />
    <ProjectReference Include="../../../../Deliverance/src/Deliverance.Dominatus/Deliverance.Dominatus.csproj" />
    <ProjectReference Include="../../../../Dominatus/src/Dominatus.Core/Dominatus.Core.csproj" />
    <ProjectReference Include="../../../../Dominatus/src/Dominatus.OptFlow/Dominatus.OptFlow.csproj" />
    <ProjectReference Include="../../../../Dominatus/src/Dominatus.OptFlow.Generators/Dominatus.OptFlow.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    <ProjectReference Include="../../../../Dominatus/src/Ariadne.OptFlow/Ariadne.OptFlow.csproj" />
    <PackageReference Include="DotRecast.Detour" />
    <PackageReference Include="DotRecast.Recast" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Content/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Content/M12/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Content/M14/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Content/M18/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Content/M19/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Content/M20/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Content/M21/*.obj.ts" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
