<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Machina.Fonts</AssemblyName>
    <RootNamespace>Machina.Fonts</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../ThirdParty/Machina.Typography.OpenFont/Machina.Typography.OpenFont.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MSDF-Sharp.Core" />
    <PackageReference Include="Tomlyn" />
  </ItemGroup>
</Project>
