<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Copeland.TS</AssemblyName>
    <RootNamespace>Copeland.TS</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Copeland.Markdown/Copeland.Markdown.csproj" />
    <ProjectReference Include="../Copeland.TS.Mir/Copeland.TS.Mir.csproj" />
    <ProjectReference Include="../Copeland.TS.Workspace/Copeland.TS.Workspace.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>
</Project>
