<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Copeland.Cli.Tests</AssemblyName>
    <RootNamespace>Copeland.Cli.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Copeland/Copeland.Cli/Copeland.Cli.csproj" />
    <ProjectReference Include="../../../tools/CtsJitM0/CtsJitM0.csproj" />
    <ProjectReference Include="../../../src/Copeland/Copeland.TS.LanguageServer/Copeland.TS.LanguageServer.csproj" />
    <ProjectReference Include="../../../src/Copeland/Copeland.TS.MSBuild/Copeland.TS.MSBuild.csproj" />
  </ItemGroup>
</Project>
