<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <CopelandRequiredVersion>0.1.0</CopelandRequiredVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Copeland.TS.Sdk" Version="0.1.0" PrivateAssets="all" />
    <CopelandCompile Include="Copeland\**\*.ts" />
  </ItemGroup>
</Project>
