<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Copeland.TS.Database.Tests</AssemblyName>
    <RootNamespace>Copeland.TS.Database.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Copeland/Copeland.TS.Database/Copeland.TS.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fixture/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
