// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(double value0)
    {
        __field_r1_002Ef0 = value0;
    }

    internal double __field_r1_002Ef0 { get; }
}

public sealed class __CopeRecord_r2
{
    internal __CopeRecord_r2(double value0, double value1)
    {
        __field_r2_002Ef0 = value0;
        __field_r2_002Ef1 = value1;
    }

    internal double __field_r2_002Ef0 { get; }

    internal double __field_r2_002Ef1 { get; }
}


public abstract record Shape
{
    protected Shape()
    {
    }

    public sealed record Circle(__CopeRecord_r1 value) : Shape;

    public sealed record Rectangle(__CopeRecord_r2 value) : Shape;

}

public static class CopelandModule
{
    public static double main()
    {
        var __cope_record_init_0 = 4.0;
        __CopeRecord_r1 circle = new __CopeRecord_r1(__cope_record_init_0);
        Shape shape = new Shape.Circle(circle);
        return shape switch { Shape.Circle(var value) => ((value).__field_r1_002Ef0 * (value).__field_r1_002Ef0), Shape.Rectangle(var value) => ((value).__field_r2_002Ef0 * (value).__field_r2_002Ef1), _ => throw new global::System.InvalidOperationException("Non-exhaustive match.") };
    }

}
