[atlas]
format = 1
kind = "machina-font-atlas"
name = "crimson-text-msdf-proofs"
distance_field = "msdf"
version = 1

[font]
face = "CrimsonText-Regular"
family = "Space Mono"
style = "Regular"
source = "C:\\Users\\yuech\\source\\repos\\Copeland\\tests\\Machina.Fonts.Tests\\bin\\Debug\\net10.0\\Fixtures\\Fonts\\SpaceMono-Regular.ttf"
source_hash = "sha256-space-mono"
license = "OFL-1.1"

[metrics]
em_size = 32
units_per_em = 1000
ascent = 25.600000000000001
descent = -6.4000000000000004
line_gap = 0
line_height = 32

[msdf]
range = 4
scale = 1
edge_coloring = "simple"
miter_limit = 2

[[page]]
index = 0
image = "crimson-text-msdf-proofs.page0.dfpage"
width = 128
height = 128
content_hash = "sha256:a66e107887ed6f88b791bcb94bdf2615283f207cd2896de137c69dc2172d031b"

[[glyph]]
codepoint = 65
char = "A"
em_size = 32
weight = 400
slant = "upright"
page = 0
x = 0
y = 0
width = 32
height = 32
advance = 21.375
bearing_x = 0.625
bearing_y = 20.71875
u0 = 0
v0 = 0
u1 = 0.25
v1 = 0.25

[[glyph]]
codepoint = 82
char = "R"
em_size = 32
weight = 400
slant = "upright"
page = 0
x = 34
y = 0
width = 32
height = 32
advance = 20.625
bearing_x = 1.1875
bearing_y = 20.625
u0 = 0.265625
v0 = 0
u1 = 0.515625
v1 = 0.25

[[glyph]]
codepoint = 84
char = "T"
em_size = 32
weight = 400
slant = "upright"
page = 0
x = 68
y = 0
width = 32
height = 32
advance = 20.90625
bearing_x = 0.875
bearing_y = 20.96875
u0 = 0.53125
v0 = 0
u1 = 0.78125
v1 = 0.25

[[glyph]]
codepoint = 86
char = "V"
em_size = 32
weight = 400
slant = "upright"
page = 0
x = 0
y = 34
width = 32
height = 32
advance = 22.15625
bearing_x = 0.53125
bearing_y = 20.6875
u0 = 0
v0 = 0.265625
u1 = 0.25
v1 = 0.515625

[[glyph]]
codepoint = 87
char = "W"
em_size = 32
weight = 400
slant = "upright"
page = 0
x = 34
y = 34
width = 32
height = 32
advance = 33.625
bearing_x = 0.5
bearing_y = 20.6875
u0 = 0.265625
v0 = 0.265625
u1 = 0.515625
v1 = 0.515625

[[glyph]]
codepoint = 89
char = "Y"
em_size = 32
weight = 400
slant = "upright"
page = 0
x = 68
y = 34
width = 32
height = 32
advance = 20.28125
bearing_x = 0.46875
bearing_y = 20.6875
u0 = 0.53125
v0 = 0.265625
u1 = 0.78125
v1 = 0.515625

[[glyph]]
codepoint = 97
char = "a"
em_size = 32
weight = 400
slant = "upright"
page = 0
x = 0
y = 68
width = 32
height = 32
advance = 13.21875
bearing_x = 1.21875
bearing_y = 13.625
u0 = 0
v0 = 0.53125
u1 = 0.25
v1 = 0.78125

[[glyph]]
codepoint = 111
char = "o"
em_size = 32
weight = 400
slant = "upright"
page = 0
x = 34
y = 68
width = 32
height = 32
advance = 15.9375
bearing_x = 1.15625
bearing_y = 13.65625
u0 = 0.265625
v0 = 0.53125
u1 = 0.515625
v1 = 0.78125

