using System.Globalization;
using System.Text;
using Aurelian.Shaders.Language.Ast;
using Aurelian.Shaders.Language.Diagnostics;

namespace Aurelian.Shaders.Language.Emission.Hlsl;

public static class HlslEmitter
{
    public static HlslEmissionResult EmitModule(SdslvModule module, HlslEmissionOptions? options = null)
    {
        _ = options;
        var emitter = new Emitter(module);
        return emitter.Emit();
    }

    private sealed class Emitter(SdslvModule module)
    {
        private readonly StringBuilder _builder = new();
        private readonly List<SdslvDiagnostic> _diagnostics = [];
        private int _indent;

        public HlslEmissionResult Emit()
        {
            WriteLine("// Generated by Aurelian SDSL-V HLSL M0.");
            if (module.Namespace is not null)
            {
                WriteLine($"// namespace {module.Namespace}");
            }

            if (module.Namespace is not null || module.Declarations.Count > 0)
            {
                WriteLine();
            }

            foreach (var declaration in module.Declarations)
            {
                EmitDeclaration(declaration);
            }

            return new HlslEmissionResult(_builder.ToString(), _diagnostics);
        }

        private void EmitDeclaration(SdslvDecl declaration)
        {
            switch (declaration)
            {
                case SdslvRecordDecl record:
                    EmitAggregate(record.Name, record.Fields);
                    WriteLine();
                    break;
                case SdslvStreamDecl stream:
                    EmitAggregate(stream.Name, stream.Fields);
                    WriteLine();
                    break;
                case SdslvShaderDecl shader:
                    EmitShader(shader);
                    break;
                case SdslvTypeAliasDecl alias:
                    WriteLine($"typedef {MapType(alias.TargetType)} {alias.Name};");
                    WriteLine();
                    break;
                case SdslvEnumDecl enumDecl:
                    EmitEnum(enumDecl);
                    WriteLine();
                    break;
                case SdslvFlowDecl:
                case SdslvCompileDecl:
                case SdslvInterfaceDecl:
                    Error(
                        HlslEmissionDiagnosticCodes.UnsupportedDeclarationForHlslM0,
                        $"HLSL M0 does not support declaration shape '{declaration.GetType().Name}'.");
                    break;
                default:
                    Error(
                        HlslEmissionDiagnosticCodes.UnsupportedDeclarationForHlslM0,
                        $"HLSL M0 does not recognize declaration shape '{declaration.GetType().Name}'.");
                    break;
            }
        }

        private void EmitAggregate(string name, IReadOnlyList<SdslvFieldDecl> fields)
        {
            WriteLine($"struct {name} {{");
            Indent();
            foreach (var field in fields)
            {
                var semantic = GetM0Semantic(name, field.Name);
                WriteLine(semantic is null
                    ? $"{MapType(field.TypeName)} {field.Name};"
                    : $"{MapType(field.TypeName)} {field.Name} : {semantic};");
            }

            Outdent();
            WriteLine("};");
        }

        private void EmitEnum(SdslvEnumDecl enumDecl)
        {
            for (var i = 0; i < enumDecl.Variants.Count; i++)
            {
                WriteLine(FormattableString.Invariant($"static const int {enumDecl.Name}_{enumDecl.Variants[i].Name} = {i};"));
            }
        }

        private void EmitShader(SdslvShaderDecl shader)
        {
            foreach (var materialField in shader.MaterialFields)
            {
                WriteLine($"static {MapType(materialField.TypeName)} {materialField.Name};");
            }

            if (shader.MaterialFields.Count > 0)
            {
                WriteLine();
            }

            foreach (var method in shader.Methods)
            {
                EmitFunction(method);
                WriteLine();
            }

            foreach (var stageMethod in shader.StageMethods)
            {
                EmitFunction(stageMethod);
                WriteLine();
            }
        }

        private void EmitFunction(SdslvFunctionDecl function)
        {
            if (function.ErrorType is not null)
            {
                Error(
                    HlslEmissionDiagnosticCodes.UnsupportedDeclarationForHlslM0,
                    $"HLSL M0 does not support fallible function '{function.Name}'.");
            }

            var parameters = string.Join(", ", function.Parameters.Select(parameter => $"{MapType(parameter.TypeName)} {parameter.Name}"));
            var returnSemantic = GetM0ReturnSemantic(function);
            WriteLine(returnSemantic is null
                ? $"{MapType(function.ReturnType)} {function.Name}({parameters})"
                : $"{MapType(function.ReturnType)} {function.Name}({parameters}) : {returnSemantic}");
            WriteLine("{");
            Indent();
            if (function.Body is not null)
            {
                foreach (var statement in function.Body.Statements)
                {
                    EmitStatement(statement);
                }
            }

            Outdent();
            WriteLine("}");
        }

        private void EmitStatement(SdslvStatement statement)
        {
            switch (statement)
            {
                case SdslvLetStatement let:
                    if (let.Initializer is null)
                    {
                        WriteLine($"{MapType(let.TypeName)} {let.Name};");
                    }
                    else
                    {
                        WriteLine($"{MapType(let.TypeName)} {let.Name} = {EmitExpression(let.Initializer)};");
                    }
                    break;
                case SdslvAssignStatement assign:
                    WriteLine($"{EmitExpression(assign.Target)} = {EmitExpression(assign.Value)};");
                    break;
                case SdslvReturnStatement ret:
                    WriteLine($"return {EmitExpression(ret.Value)};");
                    break;
                case SdslvExpressionStatement expression:
                    WriteLine($"{EmitExpression(expression.Value)};");
                    break;
                case SdslvEmptyStatement:
                    WriteLine(";");
                    break;
                case SdslvIfStatement ifStatement:
                    EmitIfStatement(ifStatement);
                    break;
                case SdslvForStatement forStatement:
                    EmitForStatement(forStatement);
                    break;
                default:
                    Error(
                        HlslEmissionDiagnosticCodes.UnsupportedStatementForHlslM0,
                        $"HLSL M0 does not recognize statement shape '{statement.GetType().Name}'.");
                    break;
            }
        }

        private void EmitIfStatement(SdslvIfStatement ifStatement)
        {
            WriteLine($"if ({EmitExpression(ifStatement.Condition)})");
            EmitStatementBlock(ifStatement.ThenBody);
            if (ifStatement.ElseBody is not null)
            {
                WriteLine("else");
                EmitStatementBlock(ifStatement.ElseBody);
            }
        }

        private void EmitForStatement(SdslvForStatement forStatement)
        {
            var iterator = forStatement.Iterator;
            var start = EmitExpression(forStatement.Start);
            var end = EmitExpression(forStatement.End);
            var step = forStatement.Step is null ? "1" : EmitExpression(forStatement.Step);
            WriteLine($"for (int {iterator} = {start}; {iterator} < {end}; {iterator} += {step})");
            EmitStatementBlock(forStatement.Body);
        }

        private void EmitStatementBlock(IReadOnlyList<SdslvStatement> statements)
        {
            WriteLine("{");
            Indent();
            foreach (var statement in statements)
            {
                EmitStatement(statement);
            }

            Outdent();
            WriteLine("}");
        }

        private string EmitExpression(SdslvExpression expression) => expression switch
        {
            SdslvIdentifierExpression identifier => identifier.Name,
            SdslvIntegerLiteralExpression integer => integer.Value,
            SdslvFloatLiteralExpression floating => floating.Value,
            SdslvStringLiteralExpression text => text.Value,
            SdslvBoolLiteralExpression boolean => boolean.Value ? "true" : "false",
            SdslvArrayLiteralExpression array => "{" + string.Join(", ", array.Elements.Select(EmitExpression)) + "}",
            SdslvFieldAccessExpression fieldAccess => $"{EmitExpression(fieldAccess.Base)}.{fieldAccess.Field}",
            SdslvIndexExpression index => $"{EmitExpression(index.Base)}[{EmitExpression(index.Index)}]",
            SdslvCallExpression call => $"{EmitExpression(call.Callee)}({string.Join(", ", call.Arguments.Select(EmitExpression))})",
            SdslvBinaryExpression binary => $"({EmitExpression(binary.Left)} {MapBinaryOperator(binary.Operator)} {EmitExpression(binary.Right)})",
            SdslvUnaryExpression unary => $"{MapUnaryOperator(unary.Operator)}{EmitExpression(unary.Operand)}",
            SdslvWithExpression or SdslvSwitchExpression or SdslvMatchExpression or SdslvWhenUtilityExpression or SdslvTryPropagateExpression or SdslvUnwrapExpression => UnsupportedExpression(expression),
            _ => UnsupportedExpression(expression),
        };

        private string UnsupportedExpression(SdslvExpression expression)
        {
            Error(
                HlslEmissionDiagnosticCodes.UnsupportedExpressionForHlslM0,
                $"HLSL M0 does not support expression shape '{expression.GetType().Name}'.");
            return "/* unsupported */";
        }

        private static string? GetM0Semantic(string aggregateName, string fieldName)
        {
            if (aggregateName.Equals("VertexInput", StringComparison.Ordinal) &&
                fieldName.Equals("Position", StringComparison.Ordinal))
            {
                return "POSITION";
            }

            if (aggregateName.Equals("VertexOutput", StringComparison.Ordinal) &&
                fieldName.Equals("Position", StringComparison.Ordinal))
            {
                return "SV_Position";
            }

            if (fieldName.Equals("Color", StringComparison.Ordinal))
            {
                return "COLOR0";
            }

            return null;
        }

        private static string? GetM0ReturnSemantic(SdslvFunctionDecl function)
        {
            if (!function.Name.Equals("PSMain", StringComparison.Ordinal))
            {
                return null;
            }

            if (function.ReturnType is SdslvNamedTypeRef named &&
                named.Path.Segments.Count > 0 &&
                named.Path.Segments[^1].Equals("float4", StringComparison.Ordinal))
            {
                return "SV_Target0";
            }

            return null;
        }

        private string MapType(SdslvTypeRef typeRef)
        {
            if (typeRef is SdslvNamedTypeRef named)
            {
                var name = named.Path.ToString();
                var lastSegment = named.Path.Segments.Count == 0 ? name : named.Path.Segments[^1];
                return lastSegment switch
                {
                    "void" => "void",
                    "bool" => "bool",
                    "int" => "int",
                    "uint" => "uint",
                    "float" => "float",
                    "float2" => "float2",
                    "float3" => "float3",
                    "float4" => "float4",
                    "float4x4" => "float4x4",
                    _ => lastSegment,
                };
            }

            if (typeRef is SdslvArrayTypeRef array)
            {
                return $"{MapType(array.Element)}[{array.Length.ToString(CultureInfo.InvariantCulture)}]";
            }

            Error(
                HlslEmissionDiagnosticCodes.UnsupportedTypeForHlslM0,
                $"HLSL M0 does not recognize type reference shape '{typeRef.GetType().Name}'.");
            return "/* unsupported-type */";
        }

        private static string MapBinaryOperator(SdslvBinaryOperator op) => op switch
        {
            SdslvBinaryOperator.Add => "+",
            SdslvBinaryOperator.Subtract => "-",
            SdslvBinaryOperator.Multiply => "*",
            SdslvBinaryOperator.Divide => "/",
            SdslvBinaryOperator.Modulo => "%",
            SdslvBinaryOperator.LogicalOr => "||",
            SdslvBinaryOperator.LogicalAnd => "&&",
            SdslvBinaryOperator.Equal => "==",
            SdslvBinaryOperator.NotEqual => "!=",
            SdslvBinaryOperator.Less => "<",
            SdslvBinaryOperator.LessEqual => "<=",
            SdslvBinaryOperator.Greater => ">",
            SdslvBinaryOperator.GreaterEqual => ">=",
            _ => "/* unsupported-op */",
        };

        private static string MapUnaryOperator(SdslvUnaryOperator op) => op switch
        {
            SdslvUnaryOperator.Negate => "-",
            SdslvUnaryOperator.Not => "!",
            _ => "/* unsupported-unary */",
        };

        private void WriteLine(string text = "")
        {
            if (text.Length > 0)
            {
                _builder.Append(new string(' ', _indent * 4));
            }

            _builder.AppendLine(text);
        }

        private void Indent() => _indent++;

        private void Outdent() => _indent = Math.Max(0, _indent - 1);

        private void Error(string code, string message) => _diagnostics.Add(new SdslvDiagnostic(
            code,
            SdslvDiagnosticSeverity.Error,
            SdslvDiagnosticPhase.Emission,
            message,
            SdslvSpan.Unknown));
    }
}
