<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Copeland.TsonWorkbookM0</AssemblyName>
    <RootNamespace>Copeland.TsonWorkbookM0</RootNamespace>
    <CopelandTaskAssembly>$(MSBuildProjectDirectory)\..\..\..\..\src\Copeland\Copeland.TS.MSBuild\bin\$(Configuration)\net10.0\Copeland.TS.MSBuild.dll</CopelandTaskAssembly>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Copeland\Copeland.TS.MSBuild\Copeland.TS.MSBuild.csproj"
                      ReferenceOutputAssembly="false" />
    <CopelandCompile Include="Workbook.ts" />
  </ItemGroup>

  <Import Project="..\..\..\..\src\Copeland\Copeland.TS.MSBuild\build\Copeland.TS.Sdk.targets" />
</Project>
