// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public readonly struct CopeResult<TValue, TError>
{
    private readonly TValue _value;
    private readonly TError _error;
    public bool IsOk { get; }

    public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException("Result has no value.");
    public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException("Result has no error.");

    private CopeResult(bool isOk, TValue value, TError error)
    {
        IsOk = isOk;
        _value = value;
        _error = error;
    }

    public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);
    public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);
}

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(string value0)
    {
        __field_r1_002Ef0 = value0;
    }

    internal string __field_r1_002Ef0 { get; }
}

public sealed class __CopeRecord_r2
{
    internal __CopeRecord_r2(double[] value0, bool[] value1, double[] value2, string[] value3, double[][] value4, __CopeRecord_r1[] value5, Signal[] value6, __CopeRecord_r1[] value7)
    {
        __field_r2_002Ef0 = value0;
        __field_r2_002Ef1 = value1;
        __field_r2_002Ef2 = value2;
        __field_r2_002Ef3 = value3;
        __field_r2_002Ef4 = value4;
        __field_r2_002Ef5 = value5;
        __field_r2_002Ef6 = value6;
        __field_r2_002Ef7 = value7;
    }

    internal double[] __field_r2_002Ef0 { get; }

    internal bool[] __field_r2_002Ef1 { get; }

    internal double[] __field_r2_002Ef2 { get; }

    internal string[] __field_r2_002Ef3 { get; }

    internal double[][] __field_r2_002Ef4 { get; }

    internal __CopeRecord_r1[] __field_r2_002Ef5 { get; }

    internal Signal[] __field_r2_002Ef6 { get; }

    internal __CopeRecord_r1[] __field_r2_002Ef7 { get; }
}


public abstract record TsonEncodeError
{
    protected TsonEncodeError()
    {
    }

    public sealed record InvalidUnicode : TsonEncodeError;

    public sealed record OutputLimitExceeded : TsonEncodeError;

}
public abstract record Signal
{
    protected Signal()
    {
    }

    public sealed record Idle : Signal;

    public sealed record Text(string value) : Signal;

    public sealed record DetailValue(__CopeRecord_r1 detail) : Signal;

}

public static class CopelandModule
{
    private sealed class __TsonWriter
    {
        private readonly global::System.Text.StringBuilder _builder = new();
        private readonly int _maximumBytes;
        private readonly int _maximumStringCodeUnits;
        private int _bytes;
        internal TsonEncodeError? Error { get; private set; }

        internal __TsonWriter(int maximumBytes, int maximumStringCodeUnits)
        {
            _maximumBytes = maximumBytes;
            _maximumStringCodeUnits = maximumStringCodeUnits;
        }

        internal bool Static(string value) => AppendRaw(value, false);

        internal bool Indent(int level)
        {
            return Static(new string(' ', level * 4));
        }

        internal bool String(string value)
        {
            if (value.Length > _maximumStringCodeUnits)
            {
                return FailOutputLimit();
            }
            for (int index = 0; index < value.Length; index++)
            {
                char character = value[index];
                if (char.IsHighSurrogate(character))
                {
                    if (index + 1 >= value.Length || !char.IsLowSurrogate(value[index + 1])) return FailInvalidUnicode();
                    index++;
                }
                else if (char.IsLowSurrogate(character)) return FailInvalidUnicode();
            }
            if (!Static("\"")) return false;
            for (int index = 0; index < value.Length; index++)
            {
                char character = value[index];
                switch (character)
                {
                    case '"': if (!Static("\\\"")) return false; break;
                    case '\\': if (!Static("\\\\")) return false; break;
                    case '\b': if (!Static("\\b")) return false; break;
                    case '\f': if (!Static("\\f")) return false; break;
                    case '\n': if (!Static("\\n")) return false; break;
                    case '\r': if (!Static("\\r")) return false; break;
                    case '\t': if (!Static("\\t")) return false; break;
                    case '\u2028': if (!UnicodeEscape(character)) return false; break;
                    case '\u2029': if (!UnicodeEscape(character)) return false; break;
                    default:
                        if (character < ' ') { if (!UnicodeEscape(character)) return false; }
                        else if (char.IsHighSurrogate(character))
                        {
                            if (index + 1 >= value.Length || !char.IsLowSurrogate(value[index + 1])) return FailInvalidUnicode();
                            if (!AppendScalar(character, value[++index])) return false;
                        }
                        else if (char.IsLowSurrogate(character)) return FailInvalidUnicode();
                        else if (!AppendRaw(character.ToString(), false)) return false;
                        break;
                }
            }
            return Static("\"");
        }

        internal bool Number(double value)
        {
            ulong bits = global::System.BitConverter.DoubleToUInt64Bits(value);
            if ((bits & 0x7FF0000000000000UL) == 0x7FF0000000000000UL && (bits & 0x000FFFFFFFFFFFFFUL) != 0) bits = 0x7FF8000000000000UL;
            return Static("$number(\"" + bits.ToString("X16", global::System.Globalization.CultureInfo.InvariantCulture) + "\")");
        }

        internal string Finish() => _builder.ToString();

        private bool UnicodeEscape(char value)
        {
            return Static("\\u" + ((int)value).ToString("X4", global::System.Globalization.CultureInfo.InvariantCulture));
        }

        private bool AppendScalar(char high, char low)
        {
            if (_bytes > _maximumBytes - 4) return FailOutputLimit();
            _bytes += 4;
            _builder.Append(high);
            _builder.Append(low);
            return true;
        }

        private bool AppendRaw(string value, bool enforceStringLimit)
        {
            if (enforceStringLimit && value.Length > _maximumStringCodeUnits) return FailOutputLimit();
            int byteCount = 0;
            for (int index = 0; index < value.Length; index++)
            {
                char character = value[index];
                if (character <= 0x7F) byteCount += 1;
                else if (character <= 0x7FF) byteCount += 2;
                else if (char.IsHighSurrogate(character))
                {
                    if (index + 1 >= value.Length || !char.IsLowSurrogate(value[index + 1])) return FailInvalidUnicode();
                    byteCount += 4;
                    index++;
                }
                else if (char.IsLowSurrogate(character)) return FailInvalidUnicode();
                else byteCount += 3;
            }
            if (_bytes > _maximumBytes - byteCount) return FailOutputLimit();
            _bytes += byteCount;
            _builder.Append(value);
            return true;
        }

        private bool FailInvalidUnicode()
        {
            Error = new TsonEncodeError.InvalidUnicode();
            return false;
        }

        private bool FailOutputLimit()
        {
            Error = new TsonEncodeError.OutputLimitExceeded();
            return false;
        }

        internal bool OutputLimit() => FailOutputLimit();
    }

    private static bool __tson_write_boolean(__TsonWriter writer, bool value, int indentation) => writer.Static(value ? "true" : "false");
    private static bool __tson_write_number(__TsonWriter writer, double value, int indentation) => writer.Number(value);
    private static bool __tson_write_string(__TsonWriter writer, string value, int indentation) => writer.String(value);

    private static CopeResult<string, TsonEncodeError> __tson_encode_tson0(__CopeRecord_r2 value)
    {
        var writer = new __TsonWriter(1048576, 262144);
        if (!writer.Static("const $schema: string = \"copeland://corpus/runtime-array-encoding\";\n\nrecord Detail {\n    label: string;\n}\n\nrecord Packet {\n    emptyNumbers: number[];\n    booleans: boolean[];\n    numbers: number[];\n    texts: string[];\n    nested: number[][];\n    details: Detail[];\n    signals: Signal[];\n    emptyDetails: Detail[];\n}\n\nenum Signal {\n    Idle,\n    Text(value: string),\n    DetailValue(detail: Detail),\n}\n\nconst $value = ")
            || !__tson_write_tson0_005Frecord_005Fr2(writer, value, 0)
            || !writer.Static(";\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        return CopeResult<string, TsonEncodeError>.Ok(writer.Finish());
    }

    private static bool __tson_write_tson0_005Frecord_005Fr1(__TsonWriter writer, __CopeRecord_r1 value, int indentation)
    {
        if (!writer.Static("$record.Detail({\n") ) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"label\": ")) return false;
        if (!__tson_write_string(writer, value.__field_r1_002Ef0, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation)) return false;
        return writer.Static("})");
    }

    private static bool __tson_write_tson0_005Frecord_005Fr2(__TsonWriter writer, __CopeRecord_r2 value, int indentation)
    {
        if (!writer.Static("$record.Packet({\n") ) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"emptyNumbers\": ")) return false;
        if (!__tson_write_tson0_005Farray_005F0(writer, value.__field_r2_002Ef0, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"booleans\": ")) return false;
        if (!__tson_write_tson0_005Farray_005F1(writer, value.__field_r2_002Ef1, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"numbers\": ")) return false;
        if (!__tson_write_tson0_005Farray_005F0(writer, value.__field_r2_002Ef2, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"texts\": ")) return false;
        if (!__tson_write_tson0_005Farray_005F2(writer, value.__field_r2_002Ef3, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"nested\": ")) return false;
        if (!__tson_write_tson0_005Farray_005F3(writer, value.__field_r2_002Ef4, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"details\": ")) return false;
        if (!__tson_write_tson0_005Farray_005F4(writer, value.__field_r2_002Ef5, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"signals\": ")) return false;
        if (!__tson_write_tson0_005Farray_005F5(writer, value.__field_r2_002Ef6, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"emptyDetails\": ")) return false;
        if (!__tson_write_tson0_005Farray_005F4(writer, value.__field_r2_002Ef7, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation)) return false;
        return writer.Static("})");
    }

    private static bool __tson_write_tson0_005Fenum_005FSignal(__TsonWriter writer, Signal value, int indentation)
    {
        switch (value)
        {
            case Signal.Idle:
                return writer.Static("Signal.Idle");
            case Signal.Text item:
                if (!writer.Static("Signal.Text(\n")) return false;
                if (!writer.Indent(indentation + 1)) return false;
                if (!__tson_write_string(writer, item.value, indentation + 1)) return false;
                if (!writer.Static("\n")) return false;
                if (!writer.Indent(indentation)) return false;
                return writer.Static(")");
            case Signal.DetailValue item:
                if (!writer.Static("Signal.DetailValue(\n")) return false;
                if (!writer.Indent(indentation + 1)) return false;
                if (!__tson_write_tson0_005Frecord_005Fr1(writer, item.detail, indentation + 1)) return false;
                if (!writer.Static("\n")) return false;
                if (!writer.Indent(indentation)) return false;
                return writer.Static(")");
            default:
                throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        }
    }

    private static bool __tson_write_tson0_005Farray_005F0(__TsonWriter writer, double[] value, int indentation)
    {
        if (value is null) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var array = value;
        var length = array.Length;
        if (length > 100000) return writer.OutputLimit();
        if (length == 0) return writer.Static("[]");
        if (!writer.Static("[\n")) return false;
        for (var index = 0; index < length; index++)
        {
            var element = array[index];
            if (!writer.Indent(indentation + 1)) return false;
            if (!__tson_write_number(writer, element, indentation + 1)) return false;
            if (!writer.Static(",\n")) return false;
        }
        if (!writer.Indent(indentation)) return false;
        return writer.Static("]");
    }

    private static bool __tson_write_tson0_005Farray_005F1(__TsonWriter writer, bool[] value, int indentation)
    {
        if (value is null) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var array = value;
        var length = array.Length;
        if (length > 100000) return writer.OutputLimit();
        if (length == 0) return writer.Static("[]");
        if (!writer.Static("[\n")) return false;
        for (var index = 0; index < length; index++)
        {
            var element = array[index];
            if (!writer.Indent(indentation + 1)) return false;
            if (!__tson_write_boolean(writer, element, indentation + 1)) return false;
            if (!writer.Static(",\n")) return false;
        }
        if (!writer.Indent(indentation)) return false;
        return writer.Static("]");
    }

    private static bool __tson_write_tson0_005Farray_005F2(__TsonWriter writer, string[] value, int indentation)
    {
        if (value is null) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var array = value;
        var length = array.Length;
        if (length > 100000) return writer.OutputLimit();
        if (length == 0) return writer.Static("[]");
        if (!writer.Static("[\n")) return false;
        for (var index = 0; index < length; index++)
        {
            var element = array[index];
            if (!writer.Indent(indentation + 1)) return false;
            if (!__tson_write_string(writer, element, indentation + 1)) return false;
            if (!writer.Static(",\n")) return false;
        }
        if (!writer.Indent(indentation)) return false;
        return writer.Static("]");
    }

    private static bool __tson_write_tson0_005Farray_005F3(__TsonWriter writer, double[][] value, int indentation)
    {
        if (value is null) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var array = value;
        var length = array.Length;
        if (length > 100000) return writer.OutputLimit();
        if (length == 0) return writer.Static("[]");
        if (!writer.Static("[\n")) return false;
        for (var index = 0; index < length; index++)
        {
            var element = array[index];
            if (!writer.Indent(indentation + 1)) return false;
            if (!__tson_write_tson0_005Farray_005F0(writer, element, indentation + 1)) return false;
            if (!writer.Static(",\n")) return false;
        }
        if (!writer.Indent(indentation)) return false;
        return writer.Static("]");
    }

    private static bool __tson_write_tson0_005Farray_005F4(__TsonWriter writer, __CopeRecord_r1[] value, int indentation)
    {
        if (value is null) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var array = value;
        var length = array.Length;
        if (length > 100000) return writer.OutputLimit();
        if (length == 0) return writer.Static("[]");
        if (!writer.Static("[\n")) return false;
        for (var index = 0; index < length; index++)
        {
            var element = array[index];
            if (!writer.Indent(indentation + 1)) return false;
            if (!__tson_write_tson0_005Frecord_005Fr1(writer, element, indentation + 1)) return false;
            if (!writer.Static(",\n")) return false;
        }
        if (!writer.Indent(indentation)) return false;
        return writer.Static("]");
    }

    private static bool __tson_write_tson0_005Farray_005F5(__TsonWriter writer, Signal[] value, int indentation)
    {
        if (value is null) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var array = value;
        var length = array.Length;
        if (length > 100000) return writer.OutputLimit();
        if (length == 0) return writer.Static("[]");
        if (!writer.Static("[\n")) return false;
        for (var index = 0; index < length; index++)
        {
            var element = array[index];
            if (!writer.Indent(indentation + 1)) return false;
            if (!__tson_write_tson0_005Fenum_005FSignal(writer, element, indentation + 1)) return false;
            if (!writer.Static(",\n")) return false;
        }
        if (!writer.Indent(indentation)) return false;
        return writer.Static("]");
    }

    public static CopeResult<string, TsonEncodeError> encode()
    {
        var __cope_record_init_0 = new double[] {  };
        var __cope_record_init_1 = new bool[] { true, false, true };
        var __cope_record_init_2 = new double[] { 0.0, -0.0, 1.5, global::System.BitConverter.UInt64BitsToDouble(0x7FF8000000000000UL), global::System.Double.PositiveInfinity, global::System.Double.NegativeInfinity };
        var __cope_record_init_3 = new string[] { "quote: \"; slash: \\; line: \n", "snow 雪 😀" };
        var __cope_record_init_4 = new double[][] { new double[] { 0.0, -0.0 }, new double[] { 1.5 }, new double[] {  } };
        var __cope_record_init_5 = "first";
        var __cope_argument_6 = new __CopeRecord_r1(__cope_record_init_5);
        var __cope_record_init_7 = "second";
        var __cope_argument_8 = new __CopeRecord_r1(__cope_record_init_7);
        var __cope_record_init_9 = new __CopeRecord_r1[] { __cope_argument_6, __cope_argument_8 };
        var __cope_argument_10 = new Signal.Idle();
        var __cope_argument_11 = new Signal.Text("payload");
        var __cope_record_init_12 = "nested record";
        var __cope_argument_13 = new __CopeRecord_r1(__cope_record_init_12);
        var __cope_argument_14 = new Signal.DetailValue(__cope_argument_13);
        var __cope_record_init_15 = new Signal[] { __cope_argument_10, __cope_argument_11, __cope_argument_14 };
        var __cope_record_init_16 = new __CopeRecord_r1[] {  };
        __CopeRecord_r2 loaded = new __CopeRecord_r2(__cope_record_init_0, __cope_record_init_1, __cope_record_init_2, __cope_record_init_3, __cope_record_init_4, __cope_record_init_9, __cope_record_init_15, __cope_record_init_16);
        return __tson_encode_tson0(loaded);
    }

}
