using Copeland.TS.Mir;

namespace Copeland.TS.Backend.CSharp;

public static class CSharpBackend
{
    private sealed class HandlerTransfer(string errorTemporary, string label)
    {
        public string ErrorTemporary { get; } = errorTemporary;
        public string Label { get; } = label;
    }

    private sealed class CSharpEmissionState(IReadOnlyDictionary<MirRecordTypeId, MirRecordDefinition> records)
    {
        public Dictionary<MirHandlerId, HandlerTransfer> Handlers { get; } = [];
        public IReadOnlyDictionary<MirRecordTypeId, MirRecordDefinition> Records { get; } = records;
        public int TryIndex { get; set; }
    }

    private static readonly AsyncLocal<CSharpEmissionState?> CurrentEmissionState = new();

    public static CSharpCompilation Emit(MirProgram program)
    {
        var diagnostics = MirValidator.Validate(program)
            .Select(diagnostic => new CSharpDiagnostic("COPE-CS-0002", $"Invalid MIR: {diagnostic.Message}"))
            .ToList();
        if (diagnostics.Count > 0)
        {
            return new CSharpCompilation(string.Empty, diagnostics);
        }
        var writer = new CSharpTextWriter();
        var enumNames = program.Enums.Select(@enum => @enum.Name).ToHashSet(StringComparer.Ordinal);
        var recordsById = program.Records.ToDictionary(record => record.Id);
        var usesResult = ProgramUsesResult(program) || program.Tables.Count > 0;
        var usesUnwrap = ProgramUsesUnwrap(program);
        var needsUnit = EnumerateTypes(program).Any(ContainsVoidResult);
        var errorTypes = CollectErrorNominalTypes(program, enumNames);

        writer.WriteLine("// <auto-generated />"); writer.WriteLine("#nullable enable"); writer.WriteLine();
        writer.WriteLine("namespace Copeland.Generated;"); writer.WriteLine();
        if (needsUnit) EmitUnit(writer);
        if (usesResult) EmitResult(writer);
        foreach (var errorType in errorTypes) writer.WriteLine($"public readonly record struct {CSharpNameMangler.Mangle(errorType)};");
        if (errorTypes.Count > 0) writer.WriteLine();
        foreach (var record in program.Records) EmitRecord(writer, record);
        if (program.Records.Count > 0) writer.WriteLine();
        foreach (var mirEnum in program.Enums) EmitEnum(writer, mirEnum);
        if (program.Enums.Count > 0) writer.WriteLine();
        if (program.Tables.Count > 0)
        {
            EmitColumnSupport(writer);
            foreach (var table in program.Tables)
            {
                EmitTable(writer, table, recordsById);
            }
        }
        writer.WriteLine("public static class CopelandModule"); writer.WriteLine("{"); writer.Indent();
        foreach (var table in program.Tables)
        {
            writer.WriteLine($"private static readonly {TableTypeName(table.Id)} {TableSingletonName(table.Id)} = {TableTypeName(table.Id)}.Create();");
        }
        if (program.Tables.Count > 0)
        {
            writer.WriteLine();
        }
        if (usesUnwrap)
        {
            EmitUnwrapPanic(writer);
        }
        if (program.TsonEncodingPlans.Count > 0)
        {
            EmitTsonEncodingRuntime(writer, program.TsonEncodingPlans, recordsById);
        }
        foreach (var function in program.Functions) EmitFunction(writer, function, enumNames, recordsById, diagnostics);
        writer.Unindent(); writer.WriteLine("}");
        return diagnostics.Count == 0
            ? new CSharpCompilation(writer.ToString(), diagnostics)
            : new CSharpCompilation(string.Empty, diagnostics);
    }

    private static void EmitRecord(CSharpTextWriter writer, MirRecordDefinition record)
    {
        string typeName = RecordTypeName(record.Id);
        string parameters = string.Join(
            ", ",
            record.Fields.Select((field, index) => $"{MapType(field.Type)} value{index}"));

        writer.WriteLine($"public sealed class {typeName}");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"internal {typeName}({parameters})");
        writer.WriteLine("{");
        writer.Indent();
        for (int index = 0; index < record.Fields.Count; index++)
        {
            writer.WriteLine($"{RecordFieldName(record.Fields[index].Id)} = value{index};");
        }
        writer.Unindent();
        writer.WriteLine("}");

        foreach (var field in record.Fields)
        {
            writer.WriteLine();
            writer.WriteLine($"internal {MapType(field.Type)} {RecordFieldName(field.Id)} {{ get; }}");
        }

        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void EmitUnit(CSharpTextWriter writer)
    {
        writer.WriteLine("public readonly record struct CopeUnit"); writer.WriteLine("{"); writer.Indent();
        writer.WriteLine("public static readonly CopeUnit Value = new();"); writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
    }

    private static void EmitResult(CSharpTextWriter writer)
    {
        writer.WriteLine("public readonly struct CopeResult<TValue, TError>"); writer.WriteLine("{"); writer.Indent();
        writer.WriteLine("private readonly TValue _value;"); writer.WriteLine("private readonly TError _error;"); writer.WriteLine("public bool IsOk { get; }"); writer.WriteLine();
        writer.WriteLine("public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException(\"Result has no value.\");");
        writer.WriteLine("public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException(\"Result has no error.\");"); writer.WriteLine();
        writer.WriteLine("private CopeResult(bool isOk, TValue value, TError error)"); writer.WriteLine("{"); writer.Indent();
        writer.WriteLine("IsOk = isOk;"); writer.WriteLine("_value = value;"); writer.WriteLine("_error = error;"); writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
        writer.WriteLine("public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);");
        writer.WriteLine("public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);");
        writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
    }

    private static void EmitUnwrapPanic(CSharpTextWriter writer)
    {
        writer.WriteLine("private sealed class CopeUnwrapPanicException : global::System.Exception");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("public object? Error { get; }");
        writer.WriteLine();
        writer.WriteLine("public CopeUnwrapPanicException(object? error)");
        writer.WriteLine("    : base(\"COPE-PANIC-UNWRAP: Result unwrap encountered err\")");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("Error = error;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void EmitEnum(CSharpTextWriter writer, MirEnum mirEnum)
    {
        var enumName = CSharpNameMangler.Mangle(mirEnum.Name); writer.WriteLine($"public abstract record {enumName}"); writer.WriteLine("{"); writer.Indent(); writer.WriteLine($"protected {enumName}()"); writer.WriteLine("{"); writer.WriteLine("}"); writer.WriteLine();
        foreach (var @case in mirEnum.Cases)
        {
            var caseName = CSharpNameMangler.Mangle(@case.Name);
            writer.WriteLine(@case.PayloadFields.Count == 0
                ? $"public sealed record {caseName} : {enumName};"
                : $"public sealed record {caseName}({string.Join(", ", @case.PayloadFields.Select(field => $"{MapType(field.Type)} {CSharpNameMangler.Mangle(field.Name)}"))}) : {enumName};");
            writer.WriteLine();
        }
        writer.Unindent(); writer.WriteLine("}");
    }

    private static void EmitColumnSupport(CSharpTextWriter writer)
    {
        writer.WriteLine("public abstract class CopeColumn<T>");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("internal abstract CopeResult<T, TableBoundsError> Get(double index);");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void EmitTable(
        CSharpTextWriter writer,
        MirTableDefinition table,
        IReadOnlyDictionary<MirRecordTypeId, MirRecordDefinition> records)
    {
        string tableType = TableTypeName(table.Id);
        string rowType = TableRowTypeName(table.RowTypeId);

        foreach (var column in table.Columns)
        {
            writer.WriteLine($"public sealed class {TableColumnTypeName(column.Id)} : CopeColumn<{MapType(column.ElementType)}>");
            writer.WriteLine("{");
            writer.Indent();
            writer.WriteLine($"private readonly {MapType(column.ElementType)}[] _values;");
            writer.WriteLine();
            writer.WriteLine($"internal {TableColumnTypeName(column.Id)}({MapType(column.ElementType)}[] values)");
            writer.WriteLine("{");
            writer.Indent();
            writer.WriteLine("_values = values;");
            writer.Unindent();
            writer.WriteLine("}");
            writer.WriteLine();
            EmitBoundsCheckedElementAccess(writer, column.ElementType, "_values", table.RowCount);
            writer.Unindent();
            writer.WriteLine("}");
            writer.WriteLine();
        }

        writer.WriteLine($"public sealed class {rowType}");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"private readonly {tableType} _table;");
        writer.WriteLine("private readonly int _index;");
        writer.WriteLine();
        writer.WriteLine($"internal {rowType}({tableType} table, int index)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("_table = table;");
        writer.WriteLine("_index = index;");
        writer.Unindent();
        writer.WriteLine("}");
        foreach (var column in table.Columns)
        {
            writer.WriteLine();
            writer.WriteLine($"internal {MapType(column.ElementType)} {TableRowFieldName(column.Id)} => _table.{TableReadMethodName(column.Id)}(_index);");
        }
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine($"public sealed class {tableType}");
        writer.WriteLine("{");
        writer.Indent();
        foreach (var column in table.Columns)
        {
            writer.WriteLine($"private readonly {MapType(column.ElementType)}[] {TableStorageName(column.Id)};");
        }
        writer.WriteLine();
        writer.WriteLine($"private {tableType}({string.Join(", ", table.Columns.Select((column, index) => $"{MapType(column.ElementType)}[] values{index}"))})");
        writer.WriteLine("{");
        writer.Indent();
        for (int index = 0; index < table.Columns.Count; index++)
        {
            MirTableColumnDefinition column = table.Columns[index];
            writer.WriteLine($"{TableStorageName(column.Id)} = values{index};");
            writer.WriteLine($"{TableColumnPropertyName(column.Id)} = new {TableColumnTypeName(column.Id)}(values{index});");
        }
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine($"internal static {tableType} Create()");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"return new {tableType}(");
        writer.Indent();
        for (int index = 0; index < table.Columns.Count; index++)
        {
            MirTableColumnDefinition column = table.Columns[index];
            string values = string.Join(", ", column.Constants.Select(constant => EmitTableConstant(constant, records)));
            string comma = index == table.Columns.Count - 1 ? string.Empty : ",";
            writer.WriteLine($"new {MapType(column.ElementType)}[] {{ {values} }}{comma}");
        }
        writer.Unindent();
        writer.WriteLine(");");
        writer.Unindent();
        writer.WriteLine("}");
        foreach (var column in table.Columns)
        {
            writer.WriteLine();
            writer.WriteLine($"internal {TableColumnTypeName(column.Id)} {TableColumnPropertyName(column.Id)} {{ get; }}");
            writer.WriteLine();
            writer.WriteLine($"internal {MapType(column.ElementType)} {TableReadMethodName(column.Id)}(int index) => {TableStorageName(column.Id)}[index];");
        }
        writer.WriteLine();
        writer.WriteLine($"internal CopeResult<{rowType}, TableBoundsError> GetRow(double index)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("return CopeResult<" + rowType + ", TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine($"if (index < 0 || index >= {table.RowCount.ToString(global::System.Globalization.CultureInfo.InvariantCulture)})");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("return CopeResult<" + rowType + ", TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, " + table.RowCount.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + ".0));");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine("return CopeResult<" + rowType + ", TableBoundsError>.Ok(new " + rowType + "(this, (int)index));");
        writer.Unindent();
        writer.WriteLine("}");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void EmitBoundsCheckedElementAccess(CSharpTextWriter writer, MirType elementType, string storage, int rowCount)
    {
        string elementTypeName = MapType(elementType);
        writer.WriteLine($"internal override CopeResult<{elementTypeName}, TableBoundsError> Get(double index)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"return CopeResult<{elementTypeName}, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine($"if (index < 0 || index >= {rowCount.ToString(global::System.Globalization.CultureInfo.InvariantCulture)})");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"return CopeResult<{elementTypeName}, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, {rowCount.ToString(global::System.Globalization.CultureInfo.InvariantCulture)}.0));");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine($"return CopeResult<{elementTypeName}, TableBoundsError>.Ok({storage}[(int)index]);");
        writer.Unindent();
        writer.WriteLine("}");
    }

    private static string EmitTableConstant(MirTableConstant constant, IReadOnlyDictionary<MirRecordTypeId, MirRecordDefinition> records)
    {
        return constant switch
        {
            MirTableLiteralConstant literal => CSharpLiteralWriter.Write(literal.Value),
            MirTableRecordConstant record => EmitTableRecordConstant(record, records),
            MirTableEnumConstant value => $"new {CSharpNameMangler.Mangle(value.EnumName)}.{CSharpNameMangler.Mangle(value.CaseName)}({string.Join(", ", value.Payloads.Select(payload => EmitTableConstant(payload, records)))})",
            MirTableResultConstant result => EmitTableResultConstant(result, records),
            _ => throw new InvalidOperationException($"Unsupported validated table constant {constant.GetType().Name}."),
        };
    }

    private static string EmitTableRecordConstant(MirTableRecordConstant constant, IReadOnlyDictionary<MirRecordTypeId, MirRecordDefinition> records)
    {
        MirRecordDefinition definition = records[constant.RecordTypeId];
        var values = constant.Fields.ToDictionary(field => field.FieldId, field => field.Value);
        return $"new {RecordTypeName(constant.RecordTypeId)}({string.Join(", ", definition.Fields.Select(field => EmitTableConstant(values[field.Id], records)))})";
    }

    private static string EmitTableResultConstant(MirTableResultConstant constant, IReadOnlyDictionary<MirRecordTypeId, MirRecordDefinition> records)
    {
        string successType = MapResultComponentType(constant.Type.SuccessType);
        string errorType = MapType(constant.Type.ErrorType);
        string factory = constant.IsOk ? "Ok" : "Err";
        return $"CopeResult<{successType}, {errorType}>.{factory}({EmitTableConstant(constant.Payload, records)})";
    }

    private static void EmitFunction(
        CSharpTextWriter writer,
        MirFunction function,
        IReadOnlySet<string> enumNames,
        IReadOnlyDictionary<MirRecordTypeId, MirRecordDefinition> records,
        List<CSharpDiagnostic> diagnostics)
    {
        var returnType = MapType(function.ReturnType); var parameters = string.Join(", ", function.Parameters.Select(parameter => $"{MapType(parameter.Type)} {CSharpNameMangler.Mangle(parameter.Name)}"));
        writer.WriteLine($"public static {returnType} {CSharpNameMangler.Mangle(function.Name)}({parameters})"); writer.WriteLine("{"); writer.Indent();
        var tempIndex = 0;
        var previousState = CurrentEmissionState.Value;
        CurrentEmissionState.Value = new CSharpEmissionState(records);
        try
        {
            foreach (var statement in function.Body) EmitStatement(writer, statement, function, enumNames, ref tempIndex, diagnostics);
        }
        finally
        {
            CurrentEmissionState.Value = previousState;
        }
        writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
    }

    private static void EmitStatement(CSharpTextWriter writer, MirStatement statement, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        switch (statement)
        {
            case MirVariableDeclarationStatement declaration:
                writer.WriteLine($"{MapValueStorageType(declaration.Local.Type)} {CSharpNameMangler.Mangle(declaration.Local.Name)} = {EmitExpression(writer, declaration.Initializer, function, enumNames, ref tempIndex, diagnostics)};"); break;
            case MirExpressionStatement expression:
                writer.WriteLine($"{EmitExpression(writer, expression.Expression, function, enumNames, ref tempIndex, diagnostics)};"); break;
            case MirReturnStatement { Expression: null }:
                writer.WriteLine("return;"); break;
            case MirReturnStatement returnStatement:
                if (function.ReturnType.Identifier == "void")
                {
                    writer.WriteLine($"{EmitExpression(writer, returnStatement.Expression!, function, enumNames, ref tempIndex, diagnostics)};");
                    writer.WriteLine("return;");
                }
                else
                {
                    writer.WriteLine($"return {EmitExpression(writer, returnStatement.Expression!, function, enumNames, ref tempIndex, diagnostics)};");
                }
                break;
            case MirIfStatement conditional:
                writer.WriteLine($"if ({EmitExpression(writer, conditional.Condition, function, enumNames, ref tempIndex, diagnostics)})"); writer.WriteLine("{"); writer.Indent(); foreach (var nested in conditional.ThenStatements) EmitStatement(writer, nested, function, enumNames, ref tempIndex, diagnostics); writer.Unindent(); writer.WriteLine("}");
                if (conditional.ElseStatements is not null) { writer.WriteLine("else"); writer.WriteLine("{"); writer.Indent(); foreach (var nested in conditional.ElseStatements) EmitStatement(writer, nested, function, enumNames, ref tempIndex, diagnostics); writer.Unindent(); writer.WriteLine("}"); } break;
            default: diagnostics.Add(new CSharpDiagnostic("COPE-CS-0001", $"Unsupported MIR statement: {statement.GetType().Name}")); break;
        }
    }

    private static string EmitExpression(CSharpTextWriter writer, MirExpression expression, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
        => expression switch
        {
            MirLiteralExpression literal => CSharpLiteralWriter.Write(literal.Value),
            MirUnitExpression => "CopeUnit.Value",
            MirVariableExpression variable => CSharpNameMangler.Mangle(variable.Name),
            MirAssignmentExpression assignment => $"{CSharpNameMangler.Mangle(assignment.Name)} = {EmitExpression(writer, assignment.Expression, function, enumNames, ref tempIndex, diagnostics)}",
            MirUnaryExpression unary => unary.Operator + ParenthesizeAssignmentOperand(unary.Operand, EmitExpression(writer, unary.Operand, function, enumNames, ref tempIndex, diagnostics)),
            MirBinaryExpression binary => EmitBinary(writer, binary, function, enumNames, ref tempIndex, diagnostics),
            MirCallExpression call => $"{CSharpNameMangler.Mangle(call.FunctionName)}({string.Join(", ", EmitArguments(call.Arguments, writer, function, enumNames, ref tempIndex, diagnostics))})",
            MirArrayExpression array => $"new {MapType(array.Type)} {{ {string.Join(", ", EmitArguments(array.Elements, writer, function, enumNames, ref tempIndex, diagnostics))} }}",
            MirRecordConstructionExpression construction => EmitRecordConstruction(writer, construction, function, enumNames, ref tempIndex, diagnostics),
            MirRecordFieldAccessExpression access => EmitRecordFieldAccess(writer, access, function, enumNames, ref tempIndex, diagnostics),
            MirRecordWithExpression withExpression => EmitRecordWith(writer, withExpression, function, enumNames, ref tempIndex, diagnostics),
            MirTableReferenceExpression reference => TableSingletonName(reference.TableId),
            MirTableColumnAccessExpression access => $"{EmitExpression(writer, access.Receiver, function, enumNames, ref tempIndex, diagnostics)}.{TableColumnPropertyName(access.ColumnId)}",
            MirTableRowAccessExpression access => $"{EmitExpression(writer, access.Receiver, function, enumNames, ref tempIndex, diagnostics)}.GetRow({EmitExpression(writer, access.Index, function, enumNames, ref tempIndex, diagnostics)})",
            MirColumnElementAccessExpression access => $"{EmitExpression(writer, access.Receiver, function, enumNames, ref tempIndex, diagnostics)}.Get({EmitExpression(writer, access.Index, function, enumNames, ref tempIndex, diagnostics)})",
            MirTableRowFieldAccessExpression access => $"{EmitExpression(writer, access.Receiver, function, enumNames, ref tempIndex, diagnostics)}.{TableRowFieldName(access.FieldId)}",
            MirEnumValueExpression value => $"new {CSharpNameMangler.Mangle(value.EnumName)}.{CSharpNameMangler.Mangle(value.CaseName)}({string.Join(", ", EmitArguments(value.Arguments, writer, function, enumNames, ref tempIndex, diagnostics))})",
            MirMatchExpression match => EmitEnumMatch(writer, match, function, enumNames, ref tempIndex, diagnostics),
            MirIfExpression conditional => EmitIfExpression(writer, conditional, function, enumNames, ref tempIndex, diagnostics),
            MirTsonEncodeExpression encode => $"{TsonEncodeMethodName(encode.PlanId)}({EmitExpression(writer, encode.Operand, function, enumNames, ref tempIndex, diagnostics)})",
            MirOkExpression ok => $"CopeResult<{MapResultComponentType(((MirResultType)ok.Type).SuccessType)}, {MapType(((MirResultType)ok.Type).ErrorType)}>.Ok({EmitExpression(writer, ok.Payload, function, enumNames, ref tempIndex, diagnostics)})",
            MirErrExpression err => $"CopeResult<{MapResultComponentType(((MirResultType)err.Type).SuccessType)}, {MapType(((MirResultType)err.Type).ErrorType)}>.Err({EmitExpression(writer, err.Payload, function, enumNames, ref tempIndex, diagnostics)})",
            MirResultMatchExpression match => EmitResultMatch(writer, match, function, enumNames, ref tempIndex, diagnostics),
            MirPropagateExpression propagate => EmitPropagation(writer, propagate, function, enumNames, ref tempIndex, diagnostics),
            MirUnwrapExpression unwrap => EmitUnwrap(writer, unwrap, function, enumNames, ref tempIndex, diagnostics),
            MirTryExpression tryExpression => EmitTryExcept(writer, tryExpression, function, enumNames, ref tempIndex, diagnostics),
            _ => UnsupportedExpression(expression, diagnostics)
        };

    private static string EmitBinary(
        CSharpTextWriter writer,
        MirBinaryExpression binary,
        MirFunction function,
        IReadOnlySet<string> enumNames,
        ref int tempIndex,
        List<CSharpDiagnostic> diagnostics)
    {
        string binaryOperator = binary.Operator switch
        {
            "===" => "==",
            "!==" => "!=",
            _ => binary.Operator,
        };

        if (binaryOperator is "&&" or "||"
            && (ExpressionRequiresStatements(binary.Left) || ExpressionRequiresStatements(binary.Right)))
        {
            return EmitStatementfulLogicalBinary(
                writer,
                binary,
                function,
                enumNames,
                ref tempIndex,
                diagnostics,
                binaryOperator);
        }

        if (!ExpressionRequiresStatements(binary.Left) && !ExpressionRequiresStatements(binary.Right))
        {
            string simpleLeft = ParenthesizeAssignmentOperand(binary.Left, EmitExpression(writer, binary.Left, function, enumNames, ref tempIndex, diagnostics));
            string simpleRight = ParenthesizeAssignmentOperand(binary.Right, EmitExpression(writer, binary.Right, function, enumNames, ref tempIndex, diagnostics));
            return $"({simpleLeft} {binaryOperator} {simpleRight})";
        }

        string left = ParenthesizeAssignmentOperand(binary.Left, EmitExpression(writer, binary.Left, function, enumNames, ref tempIndex, diagnostics));
        string leftTemporary = $"__cope_operand_{tempIndex++}";
        writer.WriteLine($"var {leftTemporary} = {left};");
        string right = ParenthesizeAssignmentOperand(binary.Right, EmitExpression(writer, binary.Right, function, enumNames, ref tempIndex, diagnostics));
        string rightTemporary = $"__cope_operand_{tempIndex++}";
        writer.WriteLine($"var {rightTemporary} = {right};");
        return $"({leftTemporary} {binaryOperator} {rightTemporary})";
    }

    private static string EmitStatementfulLogicalBinary(
        CSharpTextWriter writer,
        MirBinaryExpression binary,
        MirFunction function,
        IReadOnlySet<string> enumNames,
        ref int tempIndex,
        List<CSharpDiagnostic> diagnostics,
        string binaryOperator)
    {
        string left = ParenthesizeAssignmentOperand(binary.Left, EmitExpression(writer, binary.Left, function, enumNames, ref tempIndex, diagnostics));
        string resultTemporary = $"__cope_logical_result_{tempIndex++}";
        writer.WriteLine($"bool {resultTemporary};");
        string branchCondition = binaryOperator == "&&" ? left : $"!({left})";
        writer.WriteLine($"if ({branchCondition})");
        writer.WriteLine("{");
        writer.Indent();
        string right = ParenthesizeAssignmentOperand(binary.Right, EmitExpression(writer, binary.Right, function, enumNames, ref tempIndex, diagnostics));
        writer.WriteLine($"{resultTemporary} = {right};");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine("else");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"{resultTemporary} = {(binaryOperator == "&&" ? "false" : "true")};");
        writer.Unindent();
        writer.WriteLine("}");
        return resultTemporary;
    }

    private static string ParenthesizeAssignmentOperand(MirExpression expression, string emitted)
        => expression is MirAssignmentExpression ? $"({emitted})" : emitted;

    private static string EmitIfExpression(
        CSharpTextWriter writer,
        MirIfExpression conditional,
        MirFunction function,
        IReadOnlySet<string> enumNames,
        ref int tempIndex,
        List<CSharpDiagnostic> diagnostics)
    {
        if (!ExpressionRequiresStatements(conditional.ThenExpression)
            && !ExpressionRequiresStatements(conditional.ElseExpression))
        {
            string condition = EmitExpression(writer, conditional.Condition, function, enumNames, ref tempIndex, diagnostics);
            string thenExpression = EmitExpression(writer, conditional.ThenExpression, function, enumNames, ref tempIndex, diagnostics);
            string elseExpression = EmitExpression(writer, conditional.ElseExpression, function, enumNames, ref tempIndex, diagnostics);
            return $"({condition} ? {thenExpression} : {elseExpression})";
        }

        string conditionValue = EmitExpression(writer, conditional.Condition, function, enumNames, ref tempIndex, diagnostics);
        string resultTemporary = $"__cope_if_result_{tempIndex++}";
        writer.WriteLine($"{MapValueStorageType(conditional.Type)} {resultTemporary};");
        writer.WriteLine($"if ({conditionValue})");
        writer.WriteLine("{");
        writer.Indent();
        string thenValue = EmitExpression(writer, conditional.ThenExpression, function, enumNames, ref tempIndex, diagnostics);
        writer.WriteLine($"{resultTemporary} = {thenValue};");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine("else");
        writer.WriteLine("{");
        writer.Indent();
        string elseValue = EmitExpression(writer, conditional.ElseExpression, function, enumNames, ref tempIndex, diagnostics);
        writer.WriteLine($"{resultTemporary} = {elseValue};");
        writer.Unindent();
        writer.WriteLine("}");
        return resultTemporary;
    }

    private static string EmitRecordConstruction(
        CSharpTextWriter writer,
        MirRecordConstructionExpression construction,
        MirFunction function,
        IReadOnlySet<string> enumNames,
        ref int tempIndex,
        List<CSharpDiagnostic> diagnostics)
    {
        MirRecordDefinition record = GetRecordDefinition(construction.RecordTypeId);
        var valuesByField = new Dictionary<MirRecordFieldId, string>();

        foreach (var initializer in construction.Initializers)
        {
            string value = EmitExpression(writer, initializer.Value, function, enumNames, ref tempIndex, diagnostics);
            string temporary = $"__cope_record_init_{tempIndex++}";
            writer.WriteLine($"var {temporary} = {value};");
            valuesByField.Add(initializer.FieldId, temporary);
        }

        string arguments = string.Join(", ", record.Fields.Select(field => valuesByField[field.Id]));
        return $"new {RecordTypeName(record.Id)}({arguments})";
    }

    private static string EmitRecordFieldAccess(
        CSharpTextWriter writer,
        MirRecordFieldAccessExpression access,
        MirFunction function,
        IReadOnlySet<string> enumNames,
        ref int tempIndex,
        List<CSharpDiagnostic> diagnostics)
    {
        string receiver = EmitExpression(writer, access.Receiver, function, enumNames, ref tempIndex, diagnostics);
        return $"({receiver}).{RecordFieldName(access.FieldId)}";
    }

    private static string EmitRecordWith(
        CSharpTextWriter writer,
        MirRecordWithExpression withExpression,
        MirFunction function,
        IReadOnlySet<string> enumNames,
        ref int tempIndex,
        List<CSharpDiagnostic> diagnostics)
    {
        MirRecordDefinition record = GetRecordDefinition(withExpression.RecordTypeId);
        string sourceValue = EmitExpression(writer, withExpression.Source, function, enumNames, ref tempIndex, diagnostics);
        string sourceTemporary = $"__cope_record_source_{tempIndex++}";
        writer.WriteLine($"var {sourceTemporary} = {sourceValue};");

        var replacementsByField = new Dictionary<MirRecordFieldId, string>();
        foreach (var replacement in withExpression.Replacements)
        {
            string replacementValue = EmitExpression(writer, replacement.Value, function, enumNames, ref tempIndex, diagnostics);
            string replacementTemporary = $"__cope_record_replacement_{tempIndex++}";
            writer.WriteLine($"var {replacementTemporary} = {replacementValue};");
            replacementsByField.Add(replacement.FieldId, replacementTemporary);
        }

        var arguments = new List<string>(record.Fields.Count);
        foreach (var field in record.Fields)
        {
            if (replacementsByField.TryGetValue(field.Id, out string? replacement))
            {
                arguments.Add(replacement);
            }
            else
            {
                arguments.Add($"{sourceTemporary}.{RecordFieldName(field.Id)}");
            }
        }

        return $"new {RecordTypeName(record.Id)}({string.Join(", ", arguments)})";
    }

    private static MirRecordDefinition GetRecordDefinition(MirRecordTypeId id)
    {
        CSharpEmissionState state = CurrentEmissionState.Value
            ?? throw new InvalidOperationException("Record emission requires function-local state.");
        return state.Records[id];
    }

    private static string EmitPropagation(CSharpTextWriter writer, MirPropagateExpression propagation, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        if (propagation.Target is MirPropagationTarget.LexicalExcept lexical)
        {
            var state = CurrentEmissionState.Value;
            if (state is null || !state.Handlers.TryGetValue(lexical.HandlerId, out var handler))
            {
                diagnostics.Add(new CSharpDiagnostic("COPE-CS-0002", $"Lexical except propagation target '{lexical.HandlerId}' is not active."));
                return "default!";
            }

            var temporary = $"__cope_tmp{tempIndex++}";
            writer.WriteLine($"var {temporary} = {EmitExpression(writer, propagation.Operand, function, enumNames, ref tempIndex, diagnostics)};");
            writer.WriteLine($"if (!{temporary}.IsOk)");
            writer.WriteLine("{");
            writer.Indent();
            writer.WriteLine($"{handler.ErrorTemporary} = {temporary}.Error;");
            writer.WriteLine($"goto {handler.Label};");
            writer.Unindent();
            writer.WriteLine("}");
            return $"{temporary}.Value";
        }

        if (function.ReturnType is not MirResultType functionResult || propagation.Operand.Type is not MirResultType operandResult || !MirTypeFacts.AreEquivalent(functionResult.ErrorType, operandResult.ErrorType))
        {
            diagnostics.Add(new CSharpDiagnostic("COPE-CS-0002", "Function-return propagation requires compatible Result error types.")); return "default!";
        }
        var functionTemporary = $"__cope_tmp{tempIndex++}"; writer.WriteLine($"var {functionTemporary} = {EmitExpression(writer, propagation.Operand, function, enumNames, ref tempIndex, diagnostics)};"); writer.WriteLine($"if (!{functionTemporary}.IsOk)"); writer.WriteLine("{"); writer.Indent(); writer.WriteLine($"return CopeResult<{MapResultComponentType(functionResult.SuccessType)}, {MapType(functionResult.ErrorType)}>.Err({functionTemporary}.Error);"); writer.Unindent(); writer.WriteLine("}"); return $"{functionTemporary}.Value";
    }

    private static string EmitUnwrap(CSharpTextWriter writer, MirUnwrapExpression unwrap, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        if (unwrap.Operand.Type is not MirResultType resultType || !MirTypeFacts.AreEquivalent(unwrap.Type, resultType.SuccessType))
        {
            diagnostics.Add(new CSharpDiagnostic("COPE-CS-0002", "Result unwrap requires a Result operand and its success type."));
            return "default!";
        }

        string temporary = $"__cope_tmp{tempIndex++}";
        writer.WriteLine($"var {temporary} = {EmitExpression(writer, unwrap.Operand, function, enumNames, ref tempIndex, diagnostics)};");
        writer.WriteLine($"if (!{temporary}.IsOk)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"throw new CopeUnwrapPanicException({temporary}.Error);");
        writer.Unindent();
        writer.WriteLine("}");
        return $"{temporary}.Value";
    }

    private static string EmitTryExcept(CSharpTextWriter writer, MirTryExpression tryExpression, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        var state = CurrentEmissionState.Value;
        if (state is null)
        {
            diagnostics.Add(new CSharpDiagnostic("COPE-CS-0002", "Try/except emission requires a function-local emission state."));
            return "default!";
        }

        if (state.Handlers.ContainsKey(tryExpression.HandlerId))
        {
            diagnostics.Add(new CSharpDiagnostic("COPE-CS-0002", $"Duplicate active try handler identity '{tryExpression.HandlerId}'."));
            return "default!";
        }

        var index = state.TryIndex++;
        var suffix = $"h{tryExpression.HandlerId.Value}_{index}";
        var resultTemporary = $"__cope_try_result_{suffix}";
        var errorTemporary = $"__cope_try_error_{suffix}";
        var handlerLabel = $"__cope_try_handler_{suffix}";
        var joinLabel = $"__cope_try_join_{suffix}";

        writer.WriteLine($"{MapValueStorageType(tryExpression.Type)} {resultTemporary};");
        writer.WriteLine($"{MapType(tryExpression.HandledErrorType)} {errorTemporary} = default!;");
        state.Handlers.Add(tryExpression.HandlerId, new HandlerTransfer(errorTemporary, handlerLabel));
        EmitTryValueBlock(writer, tryExpression.Protected, resultTemporary, joinLabel, function, enumNames, ref tempIndex, diagnostics);
        state.Handlers.Remove(tryExpression.HandlerId);
        writer.WriteLine($"{handlerLabel}:");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"var {CSharpNameMangler.Mangle(tryExpression.HandlerBinding.Name)} = {errorTemporary};");
        EmitTryValueBlock(writer, tryExpression.Handler, resultTemporary, joinLabel, function, enumNames, ref tempIndex, diagnostics);
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine($"{joinLabel}:");
        return resultTemporary;
    }

    private static void EmitTryValueBlock(CSharpTextWriter writer, MirValueBlock block, string resultTemporary, string joinLabel, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        writer.WriteLine("{");
        writer.Indent();
        foreach (var statement in block.PrefixStatements)
        {
            if (statement is MirExpressionStatement expressionStatement)
            {
                writer.WriteLine($"_ = {EmitExpression(writer, expressionStatement.Expression, function, enumNames, ref tempIndex, diagnostics)};");
            }
            else
            {
                EmitStatement(writer, statement, function, enumNames, ref tempIndex, diagnostics);
            }
        }

        writer.WriteLine($"{resultTemporary} = {EmitExpression(writer, block.ValueExpression, function, enumNames, ref tempIndex, diagnostics)};");
        writer.WriteLine($"goto {joinLabel};");
        writer.Unindent();
        writer.WriteLine("}");
    }

    private static string EmitResultMatch(CSharpTextWriter writer, MirResultMatchExpression match, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        var resultTemporary = $"__cope_tmp{tempIndex++}"; var valueTemporary = $"__cope_tmp{tempIndex++}";
        writer.WriteLine($"var {resultTemporary} = {EmitExpression(writer, match.Scrutinee, function, enumNames, ref tempIndex, diagnostics)};"); writer.WriteLine($"{MapType(match.Type)} {valueTemporary};"); writer.WriteLine($"if ({resultTemporary}.IsOk)"); writer.WriteLine("{"); writer.Indent(); writer.WriteLine($"var {CSharpNameMangler.Mangle(match.OkBinding.Name)} = {resultTemporary}.Value;"); writer.WriteLine($"{valueTemporary} = {EmitExpression(writer, match.OkExpression, function, enumNames, ref tempIndex, diagnostics)};"); writer.Unindent(); writer.WriteLine("}"); writer.WriteLine("else"); writer.WriteLine("{"); writer.Indent(); writer.WriteLine($"var {CSharpNameMangler.Mangle(match.ErrBinding.Name)} = {resultTemporary}.Error;"); writer.WriteLine($"{valueTemporary} = {EmitExpression(writer, match.ErrExpression, function, enumNames, ref tempIndex, diagnostics)};"); writer.Unindent(); writer.WriteLine("}"); return valueTemporary;
    }

    private static string EmitEnumMatch(CSharpTextWriter writer, MirMatchExpression match, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        if (match.Scrutinee.Type is not MirType enumType || match.Scrutinee.Type is MirArrayType or MirResultType || !enumNames.Contains(enumType.Identifier)) return UnsupportedExpression(match, diagnostics);
        if (match.Arms.Any(arm => ExpressionRequiresStatements(arm.Expression)))
        {
            return EmitStatementfulEnumMatch(writer, match, function, enumNames, ref tempIndex, diagnostics, enumType);
        }
        var scrutinee = EmitExpression(writer, match.Scrutinee, function, enumNames, ref tempIndex, diagnostics);
        var arms = new List<string>();
        foreach (var arm in match.Arms)
        {
            var pattern = arm.PayloadBindings.Count == 0 ? $"{CSharpNameMangler.Mangle(enumType.Identifier)}.{CSharpNameMangler.Mangle(arm.CaseName)} _" : $"{CSharpNameMangler.Mangle(enumType.Identifier)}.{CSharpNameMangler.Mangle(arm.CaseName)}({string.Join(", ", arm.PayloadBindings.Select(binding => $"var {CSharpNameMangler.Mangle(binding.Name)}"))})";
            arms.Add($"{pattern} => {EmitExpression(writer, arm.Expression, function, enumNames, ref tempIndex, diagnostics)}");
        }
        arms.Add("_ => throw new global::System.InvalidOperationException(\"Non-exhaustive match.\")");
        return $"{scrutinee} switch {{ {string.Join(", ", arms)} }}";
    }

    private static string EmitStatementfulEnumMatch(
        CSharpTextWriter writer,
        MirMatchExpression match,
        MirFunction function,
        IReadOnlySet<string> enumNames,
        ref int tempIndex,
        List<CSharpDiagnostic> diagnostics,
        MirType enumType)
    {
        string scrutineeValue = EmitExpression(writer, match.Scrutinee, function, enumNames, ref tempIndex, diagnostics);
        string scrutineeTemporary = $"__cope_match_scrutinee_{tempIndex++}";
        string resultTemporary = $"__cope_match_result_{tempIndex++}";
        writer.WriteLine($"{MapType(enumType)} {scrutineeTemporary} = {scrutineeValue};");
        writer.WriteLine($"{MapValueStorageType(match.Type)} {resultTemporary};");
        writer.WriteLine($"switch ({scrutineeTemporary})");
        writer.WriteLine("{");
        writer.Indent();

        foreach (var arm in match.Arms)
        {
            string enumName = CSharpNameMangler.Mangle(enumType.Identifier);
            string caseName = CSharpNameMangler.Mangle(arm.CaseName);
            string pattern = arm.PayloadBindings.Count == 0
                ? $"{enumName}.{caseName} _"
                : $"{enumName}.{caseName}({string.Join(", ", arm.PayloadBindings.Select(binding => $"var {CSharpNameMangler.Mangle(binding.Name)}"))})";
            writer.WriteLine($"case {pattern}:");
            writer.WriteLine("{");
            writer.Indent();
            string armValue = EmitExpression(writer, arm.Expression, function, enumNames, ref tempIndex, diagnostics);
            writer.WriteLine($"{resultTemporary} = {armValue};");
            writer.WriteLine("break;");
            writer.Unindent();
            writer.WriteLine("}");
        }

        writer.WriteLine("default:");
        writer.Indent();
        writer.WriteLine("throw new global::System.InvalidOperationException(\"Non-exhaustive match.\");");
        writer.Unindent();
        writer.Unindent();
        writer.WriteLine("}");
        return resultTemporary;
    }

    private static List<string> EmitArguments(IReadOnlyList<MirExpression> expressions, CSharpTextWriter writer, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        var values = new List<string>(expressions.Count);
        bool requiresOrderedStaging = expressions.Any(ExpressionRequiresStatements);
        foreach (var expression in expressions)
        {
            string value = EmitExpression(writer, expression, function, enumNames, ref tempIndex, diagnostics);
            if (!requiresOrderedStaging)
            {
                values.Add(value);
                continue;
            }

            string temporary = $"__cope_argument_{tempIndex++}";
            writer.WriteLine($"var {temporary} = {value};");
            values.Add(temporary);
        }
        return values;
    }

    private static string UnsupportedExpression(MirExpression expression, List<CSharpDiagnostic> diagnostics) { diagnostics.Add(new CSharpDiagnostic("COPE-CS-0001", $"Unsupported MIR expression: {expression.GetType().Name}")); return "default!"; }

    private static void EmitTsonEncodingRuntime(
        CSharpTextWriter writer,
        IReadOnlyList<MirTsonEncodingPlan> plans,
        IReadOnlyDictionary<MirRecordTypeId, MirRecordDefinition> records)
    {
        EmitTsonWriter(writer);
        foreach (MirTsonEncodingPlan plan in plans)
        {
            EmitTsonEncodingPlan(writer, plan, records);
        }
    }

    private static void EmitTsonWriter(CSharpTextWriter writer)
    {
        writer.WriteLine("private sealed class __TsonWriter");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("private readonly global::System.Text.StringBuilder _builder = new();");
        writer.WriteLine("private readonly int _maximumBytes;");
        writer.WriteLine("private readonly int _maximumStringCodeUnits;");
        writer.WriteLine("private int _bytes;");
        writer.WriteLine("internal TsonEncodeError? Error { get; private set; }");
        writer.WriteLine();
        writer.WriteLine("internal __TsonWriter(int maximumBytes, int maximumStringCodeUnits)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("_maximumBytes = maximumBytes;");
        writer.WriteLine("_maximumStringCodeUnits = maximumStringCodeUnits;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("internal bool Static(string value) => AppendRaw(value, false);");
        writer.WriteLine();
        writer.WriteLine("internal bool Indent(int level)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("return Static(new string(' ', level * 4));");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("internal bool String(string value)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("if (value.Length > _maximumStringCodeUnits)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("return FailOutputLimit();");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine("for (int index = 0; index < value.Length; index++)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("char character = value[index];");
        writer.WriteLine("if (char.IsHighSurrogate(character))");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("if (index + 1 >= value.Length || !char.IsLowSurrogate(value[index + 1])) return FailInvalidUnicode();");
        writer.WriteLine("index++;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine("else if (char.IsLowSurrogate(character)) return FailInvalidUnicode();");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine("if (!Static(\"\\\"\")) return false;");
        writer.WriteLine("for (int index = 0; index < value.Length; index++)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("char character = value[index];");
        writer.WriteLine("switch (character)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("case '\"': if (!Static(\"\\\\\\\"\")) return false; break;");
        writer.WriteLine("case '\\\\': if (!Static(\"\\\\\\\\\")) return false; break;");
        writer.WriteLine("case '\\b': if (!Static(\"\\\\b\")) return false; break;");
        writer.WriteLine("case '\\f': if (!Static(\"\\\\f\")) return false; break;");
        writer.WriteLine("case '\\n': if (!Static(\"\\\\n\")) return false; break;");
        writer.WriteLine("case '\\r': if (!Static(\"\\\\r\")) return false; break;");
        writer.WriteLine("case '\\t': if (!Static(\"\\\\t\")) return false; break;");
        writer.WriteLine("case '\\u2028': if (!UnicodeEscape(character)) return false; break;");
        writer.WriteLine("case '\\u2029': if (!UnicodeEscape(character)) return false; break;");
        writer.WriteLine("default:");
        writer.Indent();
        writer.WriteLine("if (character < ' ') { if (!UnicodeEscape(character)) return false; }");
        writer.WriteLine("else if (char.IsHighSurrogate(character))");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("if (index + 1 >= value.Length || !char.IsLowSurrogate(value[index + 1])) return FailInvalidUnicode();");
        writer.WriteLine("if (!AppendScalar(character, value[++index])) return false;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine("else if (char.IsLowSurrogate(character)) return FailInvalidUnicode();");
        writer.WriteLine("else if (!AppendRaw(character.ToString(), false)) return false;");
        writer.WriteLine("break;");
        writer.Unindent();
        writer.Unindent();
        writer.WriteLine("}");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine("return Static(\"\\\"\");");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("internal bool Number(double value)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("ulong bits = global::System.BitConverter.DoubleToUInt64Bits(value);");
        writer.WriteLine("if ((bits & 0x7FF0000000000000UL) == 0x7FF0000000000000UL && (bits & 0x000FFFFFFFFFFFFFUL) != 0) bits = 0x7FF8000000000000UL;");
        writer.WriteLine("return Static(\"$number(\\\"\" + bits.ToString(\"X16\", global::System.Globalization.CultureInfo.InvariantCulture) + \"\\\")\");");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("internal string Finish() => _builder.ToString();");
        writer.WriteLine();
        writer.WriteLine("private bool UnicodeEscape(char value)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("return Static(\"\\\\u\" + ((int)value).ToString(\"X4\", global::System.Globalization.CultureInfo.InvariantCulture));");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("private bool AppendScalar(char high, char low)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("if (_bytes > _maximumBytes - 4) return FailOutputLimit();");
        writer.WriteLine("_bytes += 4;");
        writer.WriteLine("_builder.Append(high);");
        writer.WriteLine("_builder.Append(low);");
        writer.WriteLine("return true;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("private bool AppendRaw(string value, bool enforceStringLimit)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("if (enforceStringLimit && value.Length > _maximumStringCodeUnits) return FailOutputLimit();");
        writer.WriteLine("int byteCount = 0;");
        writer.WriteLine("for (int index = 0; index < value.Length; index++)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("char character = value[index];");
        writer.WriteLine("if (character <= 0x7F) byteCount += 1;");
        writer.WriteLine("else if (character <= 0x7FF) byteCount += 2;");
        writer.WriteLine("else if (char.IsHighSurrogate(character))");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("if (index + 1 >= value.Length || !char.IsLowSurrogate(value[index + 1])) return FailInvalidUnicode();");
        writer.WriteLine("byteCount += 4;");
        writer.WriteLine("index++;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine("else if (char.IsLowSurrogate(character)) return FailInvalidUnicode();");
        writer.WriteLine("else byteCount += 3;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine("if (_bytes > _maximumBytes - byteCount) return FailOutputLimit();");
        writer.WriteLine("_bytes += byteCount;");
        writer.WriteLine("_builder.Append(value);");
        writer.WriteLine("return true;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("private bool FailInvalidUnicode()");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("Error = new TsonEncodeError.InvalidUnicode();");
        writer.WriteLine("return false;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("private bool FailOutputLimit()");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("Error = new TsonEncodeError.OutputLimitExceeded();");
        writer.WriteLine("return false;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("private static bool __tson_write_boolean(__TsonWriter writer, bool value, int indentation) => writer.Static(value ? \"true\" : \"false\");");
        writer.WriteLine("private static bool __tson_write_number(__TsonWriter writer, double value, int indentation) => writer.Number(value);");
        writer.WriteLine("private static bool __tson_write_string(__TsonWriter writer, string value, int indentation) => writer.String(value);");
        writer.WriteLine();
    }

    private static void EmitTsonEncodingPlan(
        CSharpTextWriter writer,
        MirTsonEncodingPlan plan,
        IReadOnlyDictionary<MirRecordTypeId, MirRecordDefinition> records)
    {
        string resultType = $"CopeResult<string, TsonEncodeError>";
        writer.WriteLine($"private static {resultType} {TsonEncodeMethodName(plan.Id)}({MapType(plan.RootType)} value)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"var writer = new __TsonWriter({plan.Limits.MaximumUtf8Bytes}, {plan.Limits.MaximumStringCodeUnits});");
        string prefix = MirTsonCanonicalText.BuildDocumentPrefix(plan);
        writer.WriteLine($"if (!writer.Static({CSharpLiteralWriter.Write(prefix)})");
        writer.Indent();
        writer.WriteLine($"|| !{TsonValueWriterName(plan.Id, plan.RootValuePlan)}(writer, value, 0)");
        writer.WriteLine("|| !writer.Static(\";\\n\"))");
        writer.Unindent();
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"return {resultType}.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine($"return {resultType}.Ok(writer.Finish());");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();

        foreach (MirTsonNominalPlan definition in plan.Definitions)
        {
            switch (definition)
            {
                case MirTsonRecordPlan record:
                    EmitTsonRecordWriter(writer, plan, record, records);
                    break;
                case MirTsonEnumPlan @enum:
                    EmitTsonEnumWriter(writer, plan, @enum);
                    break;
            }
        }
    }

    private static void EmitTsonRecordWriter(CSharpTextWriter writer, MirTsonEncodingPlan plan, MirTsonRecordPlan record, IReadOnlyDictionary<MirRecordTypeId, MirRecordDefinition> records)
    {
        writer.WriteLine($"private static bool {TsonValueWriterName(plan.Id, new MirTsonRecordValuePlan(record.RecordTypeId))}(__TsonWriter writer, {RecordTypeName(record.RecordTypeId)} value, int indentation)");
        writer.WriteLine("{");
        writer.Indent();
        if (record.Fields.Count == 0)
        {
            writer.WriteLine($"return writer.Static({CSharpLiteralWriter.Write($"$record.{record.Name}({{}})")});");
        }
        else
        {
            writer.WriteLine($"if (!writer.Static({CSharpLiteralWriter.Write($"$record.{record.Name}({{\n")}) ) return false;");
            MirRecordDefinition carrier = records[record.RecordTypeId];
            for (int index = 0; index < record.Fields.Count; index++)
            {
                MirTsonRecordFieldPlan field = record.Fields[index];
                MirRecordFieldDefinition carrierField = carrier.Fields[index];
                writer.WriteLine("if (!writer.Indent(indentation + 1)) return false;");
                writer.WriteLine($"if (!writer.Static({CSharpLiteralWriter.Write($"\"{field.Name}\": ")})) return false;");
                writer.WriteLine($"if (!{TsonValueWriterName(plan.Id, field.ValuePlan)}(writer, value.{RecordFieldName(carrierField.Id)}, indentation + 1)) return false;");
                writer.WriteLine("if (!writer.Static(\",\\n\")) return false;");
            }
            writer.WriteLine("if (!writer.Indent(indentation)) return false;");
            writer.WriteLine("return writer.Static(\"})\");");
        }
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void EmitTsonEnumWriter(CSharpTextWriter writer, MirTsonEncodingPlan plan, MirTsonEnumPlan @enum)
    {
        string methodName = TsonValueWriterName(plan.Id, new MirTsonEnumValuePlan(@enum.Name));
        string typeName = CSharpNameMangler.Mangle(@enum.Name);
        writer.WriteLine($"private static bool {methodName}(__TsonWriter writer, {typeName} value, int indentation)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("switch (value)");
        writer.WriteLine("{");
        writer.Indent();
        foreach (MirTsonEnumCasePlan @case in @enum.Cases)
        {
            string caseType = $"{typeName}.{CSharpNameMangler.Mangle(@case.Name)}";
            string variable = @case.Payloads.Count == 0 ? "" : " item";
            writer.WriteLine($"case {caseType}{variable}:");
            writer.Indent();
            if (@case.Payloads.Count == 0)
            {
                writer.WriteLine($"return writer.Static({CSharpLiteralWriter.Write($"{@enum.Name}.{@case.Name}")});");
            }
            else
            {
                writer.WriteLine($"if (!writer.Static({CSharpLiteralWriter.Write($"{@enum.Name}.{@case.Name}(\n")})) return false;");
                for (int index = 0; index < @case.Payloads.Count; index++)
                {
                    MirTsonEnumPayloadPlan payload = @case.Payloads[index];
                    writer.WriteLine("if (!writer.Indent(indentation + 1)) return false;");
                    writer.WriteLine($"if (!{TsonValueWriterName(plan.Id, payload.ValuePlan)}(writer, item.{CSharpNameMangler.Mangle(payload.Name)}, indentation + 1)) return false;");
                    writer.WriteLine(index + 1 < @case.Payloads.Count
                        ? "if (!writer.Static(\",\\n\")) return false;"
                        : "if (!writer.Static(\"\\n\")) return false;");
                }
                writer.WriteLine("if (!writer.Indent(indentation)) return false;");
                writer.WriteLine("return writer.Static(\")\");");
            }
            writer.Unindent();
        }
        writer.WriteLine("default:");
        writer.Indent();
        writer.WriteLine("throw new global::System.InvalidOperationException(\"Copeland C# backend invariant failure.\");");
        writer.Unindent();
        writer.Unindent();
        writer.WriteLine("}");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static string TsonEncodeMethodName(MirTsonEncodingPlanId id)
        => "__tson_encode_" + EncodeStableIdentity(id.Value);

    private static string TsonValueWriterName(MirTsonEncodingPlanId id, MirTsonValuePlan valuePlan)
        => valuePlan switch
        {
            MirTsonBooleanPlan => "__tson_write_boolean",
            MirTsonNumberPlan => "__tson_write_number",
            MirTsonStringPlan => "__tson_write_string",
            MirTsonRecordValuePlan record => "__tson_write_" + EncodeStableIdentity(id.Value + "_record_" + record.RecordTypeId.Value),
            MirTsonEnumValuePlan @enum => "__tson_write_" + EncodeStableIdentity(id.Value + "_enum_" + @enum.EnumName),
            _ => throw new InvalidOperationException("Unsupported validated TSON value plan."),
        };
    private static string MapType(MirType type) => type switch { MirType { Identifier: "number" } => "double", MirType { Identifier: "string" } => "string", MirType { Identifier: "boolean" } => "bool", MirType { Identifier: "void" } => "void", MirArrayType array => MapType(array.ElementType) + "[]", MirResultType result => $"CopeResult<{MapResultComponentType(result.SuccessType)}, {MapType(result.ErrorType)}>", MirRecordType record => RecordTypeName(record.RecordTypeId), MirTableType table => TableTypeName(table.TableId), MirTableRowType row => TableRowTypeName(row.RowTypeId), MirColumnType column => $"CopeColumn<{MapType(column.ElementType)}>", MirType named => CSharpNameMangler.Mangle(named.Identifier), _ => throw new InvalidOperationException("Unknown structured MIR type.") };
    private static string MapValueStorageType(MirType type) => type is MirNamedType { Identifier: "void" } ? "CopeUnit" : MapType(type);
    private static string MapResultComponentType(MirType type) => type is MirNamedType { Identifier: "void" } ? "CopeUnit" : MapType(type);

    private static bool ProgramUsesResult(MirProgram program) => EnumerateTypes(program).Any(MirTypeFacts.ContainsResult);

    private static bool ProgramUsesUnwrap(MirProgram program)
        => program.Functions.Any(function => function.Body.Any(StatementUsesUnwrap));

    private static bool StatementUsesUnwrap(MirStatement statement)
    {
        return statement switch
        {
            MirVariableDeclarationStatement declaration => ExpressionUsesUnwrap(declaration.Initializer),
            MirExpressionStatement expression => ExpressionUsesUnwrap(expression.Expression),
            MirReturnStatement { Expression: not null } returnStatement => ExpressionUsesUnwrap(returnStatement.Expression),
            MirIfStatement conditional =>
                ExpressionUsesUnwrap(conditional.Condition)
                || conditional.ThenStatements.Any(StatementUsesUnwrap)
                || (conditional.ElseStatements?.Any(StatementUsesUnwrap) ?? false),
            _ => false,
        };
    }

    private static bool ExpressionUsesUnwrap(MirExpression expression)
    {
        return expression switch
        {
            MirUnwrapExpression => true,
            MirAssignmentExpression assignment => ExpressionUsesUnwrap(assignment.Expression),
            MirUnaryExpression unary => ExpressionUsesUnwrap(unary.Operand),
            MirBinaryExpression binary => ExpressionUsesUnwrap(binary.Left) || ExpressionUsesUnwrap(binary.Right),
            MirCallExpression call => call.Arguments.Any(ExpressionUsesUnwrap),
            MirArrayExpression array => array.Elements.Any(ExpressionUsesUnwrap),
            MirRecordConstructionExpression construction => construction.Initializers.Any(initializer => ExpressionUsesUnwrap(initializer.Value)),
            MirRecordFieldAccessExpression access => ExpressionUsesUnwrap(access.Receiver),
            MirRecordWithExpression withExpression => ExpressionUsesUnwrap(withExpression.Source) || withExpression.Replacements.Any(replacement => ExpressionUsesUnwrap(replacement.Value)),
            MirTableColumnAccessExpression access => ExpressionUsesUnwrap(access.Receiver),
            MirTableRowAccessExpression access => ExpressionUsesUnwrap(access.Receiver) || ExpressionUsesUnwrap(access.Index),
            MirColumnElementAccessExpression access => ExpressionUsesUnwrap(access.Receiver) || ExpressionUsesUnwrap(access.Index),
            MirTableRowFieldAccessExpression access => ExpressionUsesUnwrap(access.Receiver),
            MirEnumValueExpression value => value.Arguments.Any(ExpressionUsesUnwrap),
            MirMatchExpression match => ExpressionUsesUnwrap(match.Scrutinee) || match.Arms.Any(arm => ExpressionUsesUnwrap(arm.Expression)),
            MirResultMatchExpression match => ExpressionUsesUnwrap(match.Scrutinee) || ExpressionUsesUnwrap(match.OkExpression) || ExpressionUsesUnwrap(match.ErrExpression),
            MirIfExpression conditional => ExpressionUsesUnwrap(conditional.Condition) || ExpressionUsesUnwrap(conditional.ThenExpression) || ExpressionUsesUnwrap(conditional.ElseExpression),
            MirOkExpression ok => ExpressionUsesUnwrap(ok.Payload),
            MirErrExpression err => ExpressionUsesUnwrap(err.Payload),
            MirPropagateExpression propagation => ExpressionUsesUnwrap(propagation.Operand),
            MirTryExpression tryExpression => ValueBlockUsesUnwrap(tryExpression.Protected) || ValueBlockUsesUnwrap(tryExpression.Handler),
            MirTsonEncodeExpression encode => ExpressionUsesUnwrap(encode.Operand),
            _ => false,
        };
    }

    private static bool ValueBlockUsesUnwrap(MirValueBlock block)
        => block.PrefixStatements.Any(StatementUsesUnwrap)
            || ExpressionUsesUnwrap(block.ValueExpression);
    private static IEnumerable<MirType> EnumerateTypes(MirProgram program)
    {
        foreach (var function in program.Functions) { yield return function.ReturnType; foreach (var parameter in function.Parameters) yield return parameter.Type; foreach (var local in function.Locals) yield return local.Type; }
        foreach (var @enum in program.Enums) foreach (var @case in @enum.Cases) foreach (var field in @case.PayloadFields) yield return field.Type;
        foreach (var record in program.Records) foreach (var field in record.Fields) yield return field.Type;
        foreach (var table in program.Tables)
        {
            foreach (var column in table.Columns)
            {
                yield return column.ElementType;
                foreach (var constant in column.Constants)
                {
                    foreach (var type in EnumerateTableConstantTypes(constant))
                    {
                        yield return type;
                    }
                }
            }
        }
    }

    private static bool ExpressionRequiresStatements(MirExpression expression)
    {
        return expression switch
        {
            MirRecordConstructionExpression => true,
            MirRecordWithExpression => true,
            MirResultMatchExpression => true,
            MirPropagateExpression => true,
            MirUnwrapExpression => true,
            MirTryExpression => true,
            MirAssignmentExpression assignment => ExpressionRequiresStatements(assignment.Expression),
            MirUnaryExpression unary => ExpressionRequiresStatements(unary.Operand),
            MirBinaryExpression binary => ExpressionRequiresStatements(binary.Left) || ExpressionRequiresStatements(binary.Right),
            MirCallExpression call => call.Arguments.Any(ExpressionRequiresStatements),
            MirArrayExpression array => array.Elements.Any(ExpressionRequiresStatements),
            MirRecordFieldAccessExpression access => ExpressionRequiresStatements(access.Receiver),
            MirTableColumnAccessExpression access => ExpressionRequiresStatements(access.Receiver),
            MirTableRowAccessExpression access => ExpressionRequiresStatements(access.Receiver) || ExpressionRequiresStatements(access.Index),
            MirColumnElementAccessExpression access => ExpressionRequiresStatements(access.Receiver) || ExpressionRequiresStatements(access.Index),
            MirTableRowFieldAccessExpression access => ExpressionRequiresStatements(access.Receiver),
            MirEnumValueExpression value => value.Arguments.Any(ExpressionRequiresStatements),
            MirMatchExpression match => ExpressionRequiresStatements(match.Scrutinee) || match.Arms.Any(arm => ExpressionRequiresStatements(arm.Expression)),
            MirIfExpression conditional => ExpressionRequiresStatements(conditional.Condition) || ExpressionRequiresStatements(conditional.ThenExpression) || ExpressionRequiresStatements(conditional.ElseExpression),
            MirOkExpression ok => ExpressionRequiresStatements(ok.Payload),
            MirErrExpression err => ExpressionRequiresStatements(err.Payload),
            MirTsonEncodeExpression encode => ExpressionRequiresStatements(encode.Operand),
            _ => false,
        };
    }

    private static string RecordTypeName(MirRecordTypeId id)
        => "__CopeRecord_" + EncodeStableIdentity(id.Value);

    private static string RecordFieldName(MirRecordFieldId id)
        => "__field_" + EncodeStableIdentity(id.Value);

    private static string TableTypeName(MirTableId id)
        => "__CopeTable_" + EncodeStableIdentity(id.Value);

    private static string TableRowTypeName(string rowTypeId)
        => "__CopeTableRow_" + EncodeStableIdentity(rowTypeId);

    private static string TableColumnTypeName(MirTableColumnId id)
        => "__CopeTableColumn_" + EncodeStableIdentity(id.Value);

    private static string TableSingletonName(MirTableId id)
        => "__cope_table_" + EncodeStableIdentity(id.Value);

    private static string TableStorageName(MirTableColumnId id)
        => "_column_" + EncodeStableIdentity(id.Value);

    private static string TableColumnPropertyName(MirTableColumnId id)
        => "__column_" + EncodeStableIdentity(id.Value);

    private static string TableReadMethodName(MirTableColumnId id)
        => "__read_" + EncodeStableIdentity(id.Value);

    private static string TableRowFieldName(MirTableColumnId id)
        => "__row_field_" + EncodeStableIdentity(id.Value);

    private static string TableRowFieldName(string fieldId)
        => "__row_field_" + EncodeStableIdentity(fieldId.Replace(".f", string.Empty, StringComparison.Ordinal));

    private static IEnumerable<MirType> EnumerateTableConstantTypes(MirTableConstant constant)
    {
        yield return constant.Type;
        switch (constant)
        {
            case MirTableRecordConstant record:
                foreach (var field in record.Fields)
                {
                    foreach (var type in EnumerateTableConstantTypes(field.Value))
                    {
                        yield return type;
                    }
                }
                break;
            case MirTableEnumConstant value:
                foreach (var payload in value.Payloads)
                {
                    foreach (var type in EnumerateTableConstantTypes(payload))
                    {
                        yield return type;
                    }
                }
                break;
            case MirTableResultConstant result:
                foreach (var type in EnumerateTableConstantTypes(result.Payload))
                {
                    yield return type;
                }
                break;
        }
    }

    private static string EncodeStableIdentity(string identity)
    {
        var encoded = new global::System.Text.StringBuilder(identity.Length);
        foreach (char character in identity)
        {
            if ((character >= 'a' && character <= 'z')
                || (character >= 'A' && character <= 'Z')
                || (character >= '0' && character <= '9'))
            {
                encoded.Append(character);
            }
            else
            {
                encoded.Append('_');
                encoded.Append(((int)character).ToString("X4", global::System.Globalization.CultureInfo.InvariantCulture));
            }
        }

        return encoded.ToString();
    }
    private static bool ContainsVoidResult(MirType type) => type switch { MirResultType result => result.SuccessType is MirNamedType { Identifier: "void" } || ContainsVoidResult(result.SuccessType) || ContainsVoidResult(result.ErrorType), MirArrayType array => ContainsVoidResult(array.ElementType), _ => false };
    private static List<string> CollectErrorNominalTypes(MirProgram program, IReadOnlySet<string> enumNames)
    {
        var names = new HashSet<string>(StringComparer.Ordinal); foreach (var type in EnumerateTypes(program)) Collect(type, names, enumNames); return names.OrderBy(name => name, StringComparer.Ordinal).ToList();
    }
    private static void Collect(MirType type, ISet<string> names, IReadOnlySet<string> enumNames)
    {
        switch (type) { case MirResultType result: CollectError(result.ErrorType, names, enumNames); Collect(result.SuccessType, names, enumNames); break; case MirArrayType array: Collect(array.ElementType, names, enumNames); break; }
    }
    private static void CollectError(MirType type, ISet<string> names, IReadOnlySet<string> enumNames)
    {
        switch (type) { case MirNamedType named when named.Identifier is not ("number" or "string" or "boolean" or "void" or "error") && !enumNames.Contains(named.Identifier): names.Add(named.Identifier); break; case MirResultType result: CollectError(result.ErrorType, names, enumNames); Collect(result.SuccessType, names, enumNames); break; case MirArrayType array: CollectError(array.ElementType, names, enumNames); break; }
    }
}
