using Copeland.TS.Mir;

namespace Copeland.TS.Backend.CSharp;

public static class CSharpBackend
{
    public static CSharpCompilation Emit(MirProgram program)
    {
        var diagnostics = new List<CSharpDiagnostic>();
        var writer = new CSharpTextWriter();
        var enumNames = program.Enums.Select(@enum => @enum.Name).ToHashSet(StringComparer.Ordinal);
        var usesResult = ProgramUsesResult(program);
        var needsUnit = EnumerateTypes(program).Any(ContainsVoidResult);
        var errorTypes = CollectErrorNominalTypes(program, enumNames);

        writer.WriteLine("// <auto-generated />"); writer.WriteLine("#nullable enable"); writer.WriteLine();
        writer.WriteLine("namespace Copeland.Generated;"); writer.WriteLine();
        if (needsUnit) EmitUnit(writer);
        if (usesResult) EmitResult(writer);
        foreach (var errorType in errorTypes) writer.WriteLine($"public readonly record struct {CSharpNameMangler.Mangle(errorType)};");
        if (errorTypes.Count > 0) writer.WriteLine();
        foreach (var mirEnum in program.Enums) EmitEnum(writer, mirEnum);
        if (program.Enums.Count > 0) writer.WriteLine();
        writer.WriteLine("public static class CopelandModule"); writer.WriteLine("{"); writer.Indent();
        foreach (var function in program.Functions) EmitFunction(writer, function, enumNames, diagnostics);
        writer.Unindent(); writer.WriteLine("}");
        return new CSharpCompilation(writer.ToString(), diagnostics);
    }

    private static void EmitUnit(CSharpTextWriter writer)
    {
        writer.WriteLine("public readonly record struct CopeUnit"); writer.WriteLine("{"); writer.Indent();
        writer.WriteLine("public static readonly CopeUnit Value = new();"); writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
    }

    private static void EmitResult(CSharpTextWriter writer)
    {
        writer.WriteLine("public readonly struct CopeResult<TValue, TError>"); writer.WriteLine("{"); writer.Indent();
        writer.WriteLine("private readonly TValue _value;"); writer.WriteLine("private readonly TError _error;"); writer.WriteLine("public bool IsOk { get; }"); writer.WriteLine();
        writer.WriteLine("public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException(\"Result has no value.\");");
        writer.WriteLine("public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException(\"Result has no error.\");"); writer.WriteLine();
        writer.WriteLine("private CopeResult(bool isOk, TValue value, TError error)"); writer.WriteLine("{"); writer.Indent();
        writer.WriteLine("IsOk = isOk;"); writer.WriteLine("_value = value;"); writer.WriteLine("_error = error;"); writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
        writer.WriteLine("public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);");
        writer.WriteLine("public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);");
        writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
    }

    private static void EmitEnum(CSharpTextWriter writer, MirEnum mirEnum)
    {
        var enumName = CSharpNameMangler.Mangle(mirEnum.Name); writer.WriteLine($"public abstract record {enumName}"); writer.WriteLine("{"); writer.Indent(); writer.WriteLine($"protected {enumName}()"); writer.WriteLine("{"); writer.WriteLine("}"); writer.WriteLine();
        foreach (var @case in mirEnum.Cases)
        {
            var caseName = CSharpNameMangler.Mangle(@case.Name);
            writer.WriteLine(@case.PayloadFields.Count == 0
                ? $"public sealed record {caseName} : {enumName};"
                : $"public sealed record {caseName}({string.Join(", ", @case.PayloadFields.Select(field => $"{MapType(field.Type)} {CSharpNameMangler.Mangle(field.Name)}"))}) : {enumName};");
            writer.WriteLine();
        }
        writer.Unindent(); writer.WriteLine("}");
    }

    private static void EmitFunction(CSharpTextWriter writer, MirFunction function, IReadOnlySet<string> enumNames, List<CSharpDiagnostic> diagnostics)
    {
        var returnType = MapType(function.ReturnType); var parameters = string.Join(", ", function.Parameters.Select(parameter => $"{MapType(parameter.Type)} {CSharpNameMangler.Mangle(parameter.Name)}"));
        writer.WriteLine($"public static {returnType} {CSharpNameMangler.Mangle(function.Name)}({parameters})"); writer.WriteLine("{"); writer.Indent();
        var tempIndex = 0;
        foreach (var statement in function.Body) EmitStatement(writer, statement, function, enumNames, ref tempIndex, diagnostics);
        writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
    }

    private static void EmitStatement(CSharpTextWriter writer, MirStatement statement, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        switch (statement)
        {
            case MirVariableDeclarationStatement declaration:
                writer.WriteLine($"{MapType(declaration.Local.Type)} {CSharpNameMangler.Mangle(declaration.Local.Name)} = {EmitExpression(writer, declaration.Initializer, function, enumNames, ref tempIndex, diagnostics)};"); break;
            case MirExpressionStatement expression:
                writer.WriteLine($"{EmitExpression(writer, expression.Expression, function, enumNames, ref tempIndex, diagnostics)};"); break;
            case MirReturnStatement { Expression: null }:
                writer.WriteLine("return;"); break;
            case MirReturnStatement returnStatement:
                writer.WriteLine($"return {EmitExpression(writer, returnStatement.Expression!, function, enumNames, ref tempIndex, diagnostics)};"); break;
            case MirIfStatement conditional:
                writer.WriteLine($"if ({EmitExpression(writer, conditional.Condition, function, enumNames, ref tempIndex, diagnostics)})"); writer.WriteLine("{"); writer.Indent(); foreach (var nested in conditional.ThenStatements) EmitStatement(writer, nested, function, enumNames, ref tempIndex, diagnostics); writer.Unindent(); writer.WriteLine("}");
                if (conditional.ElseStatements is not null) { writer.WriteLine("else"); writer.WriteLine("{"); writer.Indent(); foreach (var nested in conditional.ElseStatements) EmitStatement(writer, nested, function, enumNames, ref tempIndex, diagnostics); writer.Unindent(); writer.WriteLine("}"); } break;
            default: diagnostics.Add(new CSharpDiagnostic("COPE-CS-0001", $"Unsupported MIR statement: {statement.GetType().Name}")); break;
        }
    }

    private static string EmitExpression(CSharpTextWriter writer, MirExpression expression, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
        => expression switch
        {
            MirLiteralExpression literal => CSharpLiteralWriter.Write(literal.Value),
            MirUnitExpression => "CopeUnit.Value",
            MirVariableExpression variable => CSharpNameMangler.Mangle(variable.Name),
            MirAssignmentExpression assignment => $"{CSharpNameMangler.Mangle(assignment.Name)} = {EmitExpression(writer, assignment.Expression, function, enumNames, ref tempIndex, diagnostics)}",
            MirUnaryExpression unary => unary.Operator + EmitExpression(writer, unary.Operand, function, enumNames, ref tempIndex, diagnostics),
            MirBinaryExpression binary => $"({EmitExpression(writer, binary.Left, function, enumNames, ref tempIndex, diagnostics)} {(binary.Operator is "===" ? "==" : binary.Operator is "!==" ? "!=" : binary.Operator)} {EmitExpression(writer, binary.Right, function, enumNames, ref tempIndex, diagnostics)})",
            MirCallExpression call => $"{CSharpNameMangler.Mangle(call.FunctionName)}({string.Join(", ", EmitArguments(call.Arguments, writer, function, enumNames, ref tempIndex, diagnostics))})",
            MirArrayExpression array => $"new {MapType(array.Type)} {{ {string.Join(", ", EmitArguments(array.Elements, writer, function, enumNames, ref tempIndex, diagnostics))} }}",
            MirEnumValueExpression value => $"new {CSharpNameMangler.Mangle(value.EnumName)}.{CSharpNameMangler.Mangle(value.CaseName)}({string.Join(", ", EmitArguments(value.Arguments, writer, function, enumNames, ref tempIndex, diagnostics))})",
            MirMatchExpression match => EmitEnumMatch(writer, match, function, enumNames, ref tempIndex, diagnostics),
            MirIfExpression conditional => $"({EmitExpression(writer, conditional.Condition, function, enumNames, ref tempIndex, diagnostics)} ? {EmitExpression(writer, conditional.ThenExpression, function, enumNames, ref tempIndex, diagnostics)} : {EmitExpression(writer, conditional.ElseExpression, function, enumNames, ref tempIndex, diagnostics)})",
            MirOkExpression ok => $"CopeResult<{MapResultComponentType(((MirResultType)ok.Type).SuccessType)}, {MapType(((MirResultType)ok.Type).ErrorType)}>.Ok({EmitExpression(writer, ok.Payload, function, enumNames, ref tempIndex, diagnostics)})",
            MirErrExpression err => $"CopeResult<{MapResultComponentType(((MirResultType)err.Type).SuccessType)}, {MapType(((MirResultType)err.Type).ErrorType)}>.Err({EmitExpression(writer, err.Payload, function, enumNames, ref tempIndex, diagnostics)})",
            MirResultMatchExpression match => EmitResultMatch(writer, match, function, enumNames, ref tempIndex, diagnostics),
            MirPropagateExpression propagate => EmitPropagation(writer, propagate, function, enumNames, ref tempIndex, diagnostics),
            _ => UnsupportedExpression(expression, diagnostics)
        };

    private static string EmitPropagation(CSharpTextWriter writer, MirPropagateExpression propagation, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        if (function.ReturnType is not MirResultType functionResult || propagation.Operand.Type is not MirResultType operandResult || !MirTypeFacts.AreEquivalent(functionResult.ErrorType, operandResult.ErrorType))
        {
            diagnostics.Add(new CSharpDiagnostic("COPE-CS-0002", "Function-return propagation requires compatible Result error types.")); return "default!";
        }
        var temporary = $"__cope_tmp{tempIndex++}"; writer.WriteLine($"var {temporary} = {EmitExpression(writer, propagation.Operand, function, enumNames, ref tempIndex, diagnostics)};"); writer.WriteLine($"if (!{temporary}.IsOk)"); writer.WriteLine("{"); writer.Indent(); writer.WriteLine($"return CopeResult<{MapResultComponentType(functionResult.SuccessType)}, {MapType(functionResult.ErrorType)}>.Err({temporary}.Error);"); writer.Unindent(); writer.WriteLine("}"); return $"{temporary}.Value";
    }

    private static string EmitResultMatch(CSharpTextWriter writer, MirResultMatchExpression match, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        var resultTemporary = $"__cope_tmp{tempIndex++}"; var valueTemporary = $"__cope_tmp{tempIndex++}";
        writer.WriteLine($"var {resultTemporary} = {EmitExpression(writer, match.Scrutinee, function, enumNames, ref tempIndex, diagnostics)};"); writer.WriteLine($"{MapType(match.Type)} {valueTemporary};"); writer.WriteLine($"if ({resultTemporary}.IsOk)"); writer.WriteLine("{"); writer.Indent(); writer.WriteLine($"var {CSharpNameMangler.Mangle(match.OkBinding.Name)} = {resultTemporary}.Value;"); writer.WriteLine($"{valueTemporary} = {EmitExpression(writer, match.OkExpression, function, enumNames, ref tempIndex, diagnostics)};"); writer.Unindent(); writer.WriteLine("}"); writer.WriteLine("else"); writer.WriteLine("{"); writer.Indent(); writer.WriteLine($"var {CSharpNameMangler.Mangle(match.ErrBinding.Name)} = {resultTemporary}.Error;"); writer.WriteLine($"{valueTemporary} = {EmitExpression(writer, match.ErrExpression, function, enumNames, ref tempIndex, diagnostics)};"); writer.Unindent(); writer.WriteLine("}"); return valueTemporary;
    }

    private static string EmitEnumMatch(CSharpTextWriter writer, MirMatchExpression match, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        if (match.Scrutinee.Type is not MirType enumType || match.Scrutinee.Type is MirArrayType or MirResultType || !enumNames.Contains(enumType.Identifier)) return UnsupportedExpression(match, diagnostics);
        var scrutinee = EmitExpression(writer, match.Scrutinee, function, enumNames, ref tempIndex, diagnostics);
        var arms = new List<string>();
        foreach (var arm in match.Arms)
        {
            var pattern = arm.PayloadBindings.Count == 0 ? $"{CSharpNameMangler.Mangle(enumType.Identifier)}.{CSharpNameMangler.Mangle(arm.CaseName)} _" : $"{CSharpNameMangler.Mangle(enumType.Identifier)}.{CSharpNameMangler.Mangle(arm.CaseName)}({string.Join(", ", arm.PayloadBindings.Select(binding => $"var {CSharpNameMangler.Mangle(binding.Name)}"))})";
            arms.Add($"{pattern} => {EmitExpression(writer, arm.Expression, function, enumNames, ref tempIndex, diagnostics)}");
        }
        arms.Add("_ => throw new global::System.InvalidOperationException(\"Non-exhaustive match.\")");
        return $"{scrutinee} switch {{ {string.Join(", ", arms)} }}";
    }

    private static List<string> EmitArguments(IReadOnlyList<MirExpression> expressions, CSharpTextWriter writer, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        var values = new List<string>(expressions.Count);
        foreach (var expression in expressions) values.Add(EmitExpression(writer, expression, function, enumNames, ref tempIndex, diagnostics));
        return values;
    }

    private static string UnsupportedExpression(MirExpression expression, List<CSharpDiagnostic> diagnostics) { diagnostics.Add(new CSharpDiagnostic("COPE-CS-0001", $"Unsupported MIR expression: {expression.GetType().Name}")); return "default!"; }
    private static string MapType(MirType type) => type switch { MirType { Identifier: "number" } => "double", MirType { Identifier: "string" } => "string", MirType { Identifier: "boolean" } => "bool", MirType { Identifier: "void" } => "void", MirArrayType array => MapType(array.ElementType) + "[]", MirResultType result => $"CopeResult<{MapResultComponentType(result.SuccessType)}, {MapType(result.ErrorType)}>", MirType named => CSharpNameMangler.Mangle(named.Identifier), _ => throw new InvalidOperationException("Unknown structured MIR type.") };
    private static string MapResultComponentType(MirType type) => type is MirNamedType { Identifier: "void" } ? "CopeUnit" : MapType(type);

    private static bool ProgramUsesResult(MirProgram program) => EnumerateTypes(program).Any(MirTypeFacts.ContainsResult);
    private static IEnumerable<MirType> EnumerateTypes(MirProgram program)
    {
        foreach (var function in program.Functions) { yield return function.ReturnType; foreach (var parameter in function.Parameters) yield return parameter.Type; foreach (var local in function.Locals) yield return local.Type; }
        foreach (var @enum in program.Enums) foreach (var @case in @enum.Cases) foreach (var field in @case.PayloadFields) yield return field.Type;
    }
    private static bool ContainsVoidResult(MirType type) => type switch { MirResultType result => result.SuccessType is MirNamedType { Identifier: "void" } || ContainsVoidResult(result.SuccessType) || ContainsVoidResult(result.ErrorType), MirArrayType array => ContainsVoidResult(array.ElementType), _ => false };
    private static List<string> CollectErrorNominalTypes(MirProgram program, IReadOnlySet<string> enumNames)
    {
        var names = new HashSet<string>(StringComparer.Ordinal); foreach (var type in EnumerateTypes(program)) Collect(type, names, enumNames); return names.OrderBy(name => name, StringComparer.Ordinal).ToList();
    }
    private static void Collect(MirType type, ISet<string> names, IReadOnlySet<string> enumNames)
    {
        switch (type) { case MirResultType result: CollectError(result.ErrorType, names, enumNames); Collect(result.SuccessType, names, enumNames); break; case MirArrayType array: Collect(array.ElementType, names, enumNames); break; }
    }
    private static void CollectError(MirType type, ISet<string> names, IReadOnlySet<string> enumNames)
    {
        switch (type) { case MirNamedType named when named.Identifier is not ("number" or "string" or "boolean" or "void" or "error") && !enumNames.Contains(named.Identifier): names.Add(named.Identifier); break; case MirResultType result: CollectError(result.ErrorType, names, enumNames); Collect(result.SuccessType, names, enumNames); break; case MirArrayType array: CollectError(array.ElementType, names, enumNames); break; }
    }
}
