using Copeland.TS.Mir;

namespace Copeland.TS.Backend.CSharp;

public static class CSharpBackend
{
    private sealed class HandlerTransfer(string errorTemporary, string label)
    {
        public string ErrorTemporary { get; } = errorTemporary;
        public string Label { get; } = label;
    }

    private sealed class CSharpEmissionState
    {
        public Dictionary<MirHandlerId, HandlerTransfer> Handlers { get; } = [];
        public int TryIndex { get; set; }
    }

    private static readonly AsyncLocal<CSharpEmissionState?> CurrentEmissionState = new();

    public static CSharpCompilation Emit(MirProgram program)
    {
        var diagnostics = MirValidator.Validate(program)
            .Select(diagnostic => new CSharpDiagnostic("COPE-CS-0002", $"Invalid MIR: {diagnostic.Message}"))
            .ToList();
        if (diagnostics.Count > 0)
        {
            return new CSharpCompilation(string.Empty, diagnostics);
        }
        var writer = new CSharpTextWriter();
        var enumNames = program.Enums.Select(@enum => @enum.Name).ToHashSet(StringComparer.Ordinal);
        var usesResult = ProgramUsesResult(program);
        var usesUnwrap = ProgramUsesUnwrap(program);
        var needsUnit = EnumerateTypes(program).Any(ContainsVoidResult);
        var errorTypes = CollectErrorNominalTypes(program, enumNames);

        writer.WriteLine("// <auto-generated />"); writer.WriteLine("#nullable enable"); writer.WriteLine();
        writer.WriteLine("namespace Copeland.Generated;"); writer.WriteLine();
        if (needsUnit) EmitUnit(writer);
        if (usesResult) EmitResult(writer);
        foreach (var errorType in errorTypes) writer.WriteLine($"public readonly record struct {CSharpNameMangler.Mangle(errorType)};");
        if (errorTypes.Count > 0) writer.WriteLine();
        foreach (var mirEnum in program.Enums) EmitEnum(writer, mirEnum);
        if (program.Enums.Count > 0) writer.WriteLine();
        writer.WriteLine("public static class CopelandModule"); writer.WriteLine("{"); writer.Indent();
        if (usesUnwrap)
        {
            EmitUnwrapPanic(writer);
        }
        foreach (var function in program.Functions) EmitFunction(writer, function, enumNames, diagnostics);
        writer.Unindent(); writer.WriteLine("}");
        return new CSharpCompilation(writer.ToString(), diagnostics);
    }

    private static void EmitUnit(CSharpTextWriter writer)
    {
        writer.WriteLine("public readonly record struct CopeUnit"); writer.WriteLine("{"); writer.Indent();
        writer.WriteLine("public static readonly CopeUnit Value = new();"); writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
    }

    private static void EmitResult(CSharpTextWriter writer)
    {
        writer.WriteLine("public readonly struct CopeResult<TValue, TError>"); writer.WriteLine("{"); writer.Indent();
        writer.WriteLine("private readonly TValue _value;"); writer.WriteLine("private readonly TError _error;"); writer.WriteLine("public bool IsOk { get; }"); writer.WriteLine();
        writer.WriteLine("public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException(\"Result has no value.\");");
        writer.WriteLine("public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException(\"Result has no error.\");"); writer.WriteLine();
        writer.WriteLine("private CopeResult(bool isOk, TValue value, TError error)"); writer.WriteLine("{"); writer.Indent();
        writer.WriteLine("IsOk = isOk;"); writer.WriteLine("_value = value;"); writer.WriteLine("_error = error;"); writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
        writer.WriteLine("public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);");
        writer.WriteLine("public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);");
        writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
    }

    private static void EmitUnwrapPanic(CSharpTextWriter writer)
    {
        writer.WriteLine("private sealed class CopeUnwrapPanicException : global::System.Exception");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("public object? Error { get; }");
        writer.WriteLine();
        writer.WriteLine("public CopeUnwrapPanicException(object? error)");
        writer.WriteLine("    : base(\"COPE-PANIC-UNWRAP: Result unwrap encountered err\")");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("Error = error;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static void EmitEnum(CSharpTextWriter writer, MirEnum mirEnum)
    {
        var enumName = CSharpNameMangler.Mangle(mirEnum.Name); writer.WriteLine($"public abstract record {enumName}"); writer.WriteLine("{"); writer.Indent(); writer.WriteLine($"protected {enumName}()"); writer.WriteLine("{"); writer.WriteLine("}"); writer.WriteLine();
        foreach (var @case in mirEnum.Cases)
        {
            var caseName = CSharpNameMangler.Mangle(@case.Name);
            writer.WriteLine(@case.PayloadFields.Count == 0
                ? $"public sealed record {caseName} : {enumName};"
                : $"public sealed record {caseName}({string.Join(", ", @case.PayloadFields.Select(field => $"{MapType(field.Type)} {CSharpNameMangler.Mangle(field.Name)}"))}) : {enumName};");
            writer.WriteLine();
        }
        writer.Unindent(); writer.WriteLine("}");
    }

    private static void EmitFunction(CSharpTextWriter writer, MirFunction function, IReadOnlySet<string> enumNames, List<CSharpDiagnostic> diagnostics)
    {
        var returnType = MapType(function.ReturnType); var parameters = string.Join(", ", function.Parameters.Select(parameter => $"{MapType(parameter.Type)} {CSharpNameMangler.Mangle(parameter.Name)}"));
        writer.WriteLine($"public static {returnType} {CSharpNameMangler.Mangle(function.Name)}({parameters})"); writer.WriteLine("{"); writer.Indent();
        var tempIndex = 0;
        var previousState = CurrentEmissionState.Value;
        CurrentEmissionState.Value = new CSharpEmissionState();
        try
        {
            foreach (var statement in function.Body) EmitStatement(writer, statement, function, enumNames, ref tempIndex, diagnostics);
        }
        finally
        {
            CurrentEmissionState.Value = previousState;
        }
        writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
    }

    private static void EmitStatement(CSharpTextWriter writer, MirStatement statement, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        switch (statement)
        {
            case MirVariableDeclarationStatement declaration:
                writer.WriteLine($"{MapValueStorageType(declaration.Local.Type)} {CSharpNameMangler.Mangle(declaration.Local.Name)} = {EmitExpression(writer, declaration.Initializer, function, enumNames, ref tempIndex, diagnostics)};"); break;
            case MirExpressionStatement expression:
                writer.WriteLine($"{EmitExpression(writer, expression.Expression, function, enumNames, ref tempIndex, diagnostics)};"); break;
            case MirReturnStatement { Expression: null }:
                writer.WriteLine("return;"); break;
            case MirReturnStatement returnStatement:
                if (function.ReturnType.Identifier == "void")
                {
                    writer.WriteLine($"{EmitExpression(writer, returnStatement.Expression!, function, enumNames, ref tempIndex, diagnostics)};");
                    writer.WriteLine("return;");
                }
                else
                {
                    writer.WriteLine($"return {EmitExpression(writer, returnStatement.Expression!, function, enumNames, ref tempIndex, diagnostics)};");
                }
                break;
            case MirIfStatement conditional:
                writer.WriteLine($"if ({EmitExpression(writer, conditional.Condition, function, enumNames, ref tempIndex, diagnostics)})"); writer.WriteLine("{"); writer.Indent(); foreach (var nested in conditional.ThenStatements) EmitStatement(writer, nested, function, enumNames, ref tempIndex, diagnostics); writer.Unindent(); writer.WriteLine("}");
                if (conditional.ElseStatements is not null) { writer.WriteLine("else"); writer.WriteLine("{"); writer.Indent(); foreach (var nested in conditional.ElseStatements) EmitStatement(writer, nested, function, enumNames, ref tempIndex, diagnostics); writer.Unindent(); writer.WriteLine("}"); } break;
            default: diagnostics.Add(new CSharpDiagnostic("COPE-CS-0001", $"Unsupported MIR statement: {statement.GetType().Name}")); break;
        }
    }

    private static string EmitExpression(CSharpTextWriter writer, MirExpression expression, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
        => expression switch
        {
            MirLiteralExpression literal => CSharpLiteralWriter.Write(literal.Value),
            MirUnitExpression => "CopeUnit.Value",
            MirVariableExpression variable => CSharpNameMangler.Mangle(variable.Name),
            MirAssignmentExpression assignment => $"{CSharpNameMangler.Mangle(assignment.Name)} = {EmitExpression(writer, assignment.Expression, function, enumNames, ref tempIndex, diagnostics)}",
            MirUnaryExpression unary => unary.Operator + EmitExpression(writer, unary.Operand, function, enumNames, ref tempIndex, diagnostics),
            MirBinaryExpression binary => $"({EmitExpression(writer, binary.Left, function, enumNames, ref tempIndex, diagnostics)} {(binary.Operator is "===" ? "==" : binary.Operator is "!==" ? "!=" : binary.Operator)} {EmitExpression(writer, binary.Right, function, enumNames, ref tempIndex, diagnostics)})",
            MirCallExpression call => $"{CSharpNameMangler.Mangle(call.FunctionName)}({string.Join(", ", EmitArguments(call.Arguments, writer, function, enumNames, ref tempIndex, diagnostics))})",
            MirArrayExpression array => $"new {MapType(array.Type)} {{ {string.Join(", ", EmitArguments(array.Elements, writer, function, enumNames, ref tempIndex, diagnostics))} }}",
            MirEnumValueExpression value => $"new {CSharpNameMangler.Mangle(value.EnumName)}.{CSharpNameMangler.Mangle(value.CaseName)}({string.Join(", ", EmitArguments(value.Arguments, writer, function, enumNames, ref tempIndex, diagnostics))})",
            MirMatchExpression match => EmitEnumMatch(writer, match, function, enumNames, ref tempIndex, diagnostics),
            MirIfExpression conditional => $"({EmitExpression(writer, conditional.Condition, function, enumNames, ref tempIndex, diagnostics)} ? {EmitExpression(writer, conditional.ThenExpression, function, enumNames, ref tempIndex, diagnostics)} : {EmitExpression(writer, conditional.ElseExpression, function, enumNames, ref tempIndex, diagnostics)})",
            MirOkExpression ok => $"CopeResult<{MapResultComponentType(((MirResultType)ok.Type).SuccessType)}, {MapType(((MirResultType)ok.Type).ErrorType)}>.Ok({EmitExpression(writer, ok.Payload, function, enumNames, ref tempIndex, diagnostics)})",
            MirErrExpression err => $"CopeResult<{MapResultComponentType(((MirResultType)err.Type).SuccessType)}, {MapType(((MirResultType)err.Type).ErrorType)}>.Err({EmitExpression(writer, err.Payload, function, enumNames, ref tempIndex, diagnostics)})",
            MirResultMatchExpression match => EmitResultMatch(writer, match, function, enumNames, ref tempIndex, diagnostics),
            MirPropagateExpression propagate => EmitPropagation(writer, propagate, function, enumNames, ref tempIndex, diagnostics),
            MirUnwrapExpression unwrap => EmitUnwrap(writer, unwrap, function, enumNames, ref tempIndex, diagnostics),
            MirTryExpression tryExpression => EmitTryExcept(writer, tryExpression, function, enumNames, ref tempIndex, diagnostics),
            _ => UnsupportedExpression(expression, diagnostics)
        };

    private static string EmitPropagation(CSharpTextWriter writer, MirPropagateExpression propagation, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        if (propagation.Target is MirPropagationTarget.LexicalExcept lexical)
        {
            var state = CurrentEmissionState.Value;
            if (state is null || !state.Handlers.TryGetValue(lexical.HandlerId, out var handler))
            {
                diagnostics.Add(new CSharpDiagnostic("COPE-CS-0002", $"Lexical except propagation target '{lexical.HandlerId}' is not active."));
                return "default!";
            }

            var temporary = $"__cope_tmp{tempIndex++}";
            writer.WriteLine($"var {temporary} = {EmitExpression(writer, propagation.Operand, function, enumNames, ref tempIndex, diagnostics)};");
            writer.WriteLine($"if (!{temporary}.IsOk)");
            writer.WriteLine("{");
            writer.Indent();
            writer.WriteLine($"{handler.ErrorTemporary} = {temporary}.Error;");
            writer.WriteLine($"goto {handler.Label};");
            writer.Unindent();
            writer.WriteLine("}");
            return $"{temporary}.Value";
        }

        if (function.ReturnType is not MirResultType functionResult || propagation.Operand.Type is not MirResultType operandResult || !MirTypeFacts.AreEquivalent(functionResult.ErrorType, operandResult.ErrorType))
        {
            diagnostics.Add(new CSharpDiagnostic("COPE-CS-0002", "Function-return propagation requires compatible Result error types.")); return "default!";
        }
        var functionTemporary = $"__cope_tmp{tempIndex++}"; writer.WriteLine($"var {functionTemporary} = {EmitExpression(writer, propagation.Operand, function, enumNames, ref tempIndex, diagnostics)};"); writer.WriteLine($"if (!{functionTemporary}.IsOk)"); writer.WriteLine("{"); writer.Indent(); writer.WriteLine($"return CopeResult<{MapResultComponentType(functionResult.SuccessType)}, {MapType(functionResult.ErrorType)}>.Err({functionTemporary}.Error);"); writer.Unindent(); writer.WriteLine("}"); return $"{functionTemporary}.Value";
    }

    private static string EmitUnwrap(CSharpTextWriter writer, MirUnwrapExpression unwrap, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        if (unwrap.Operand.Type is not MirResultType resultType || !MirTypeFacts.AreEquivalent(unwrap.Type, resultType.SuccessType))
        {
            diagnostics.Add(new CSharpDiagnostic("COPE-CS-0002", "Result unwrap requires a Result operand and its success type."));
            return "default!";
        }

        string temporary = $"__cope_tmp{tempIndex++}";
        writer.WriteLine($"var {temporary} = {EmitExpression(writer, unwrap.Operand, function, enumNames, ref tempIndex, diagnostics)};");
        writer.WriteLine($"if (!{temporary}.IsOk)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"throw new CopeUnwrapPanicException({temporary}.Error);");
        writer.Unindent();
        writer.WriteLine("}");
        return $"{temporary}.Value";
    }

    private static string EmitTryExcept(CSharpTextWriter writer, MirTryExpression tryExpression, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        var state = CurrentEmissionState.Value;
        if (state is null)
        {
            diagnostics.Add(new CSharpDiagnostic("COPE-CS-0002", "Try/except emission requires a function-local emission state."));
            return "default!";
        }

        if (state.Handlers.ContainsKey(tryExpression.HandlerId))
        {
            diagnostics.Add(new CSharpDiagnostic("COPE-CS-0002", $"Duplicate active try handler identity '{tryExpression.HandlerId}'."));
            return "default!";
        }

        var index = state.TryIndex++;
        var suffix = $"h{tryExpression.HandlerId.Value}_{index}";
        var resultTemporary = $"__cope_try_result_{suffix}";
        var errorTemporary = $"__cope_try_error_{suffix}";
        var handlerLabel = $"__cope_try_handler_{suffix}";
        var joinLabel = $"__cope_try_join_{suffix}";

        writer.WriteLine($"{MapValueStorageType(tryExpression.Type)} {resultTemporary};");
        writer.WriteLine($"{MapType(tryExpression.HandledErrorType)} {errorTemporary} = default!;");
        state.Handlers.Add(tryExpression.HandlerId, new HandlerTransfer(errorTemporary, handlerLabel));
        EmitTryValueBlock(writer, tryExpression.Protected, resultTemporary, joinLabel, function, enumNames, ref tempIndex, diagnostics);
        state.Handlers.Remove(tryExpression.HandlerId);
        writer.WriteLine($"{handlerLabel}:");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"var {CSharpNameMangler.Mangle(tryExpression.HandlerBinding.Name)} = {errorTemporary};");
        EmitTryValueBlock(writer, tryExpression.Handler, resultTemporary, joinLabel, function, enumNames, ref tempIndex, diagnostics);
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine($"{joinLabel}:");
        return resultTemporary;
    }

    private static void EmitTryValueBlock(CSharpTextWriter writer, MirValueBlock block, string resultTemporary, string joinLabel, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        writer.WriteLine("{");
        writer.Indent();
        foreach (var statement in block.PrefixStatements)
        {
            if (statement is MirExpressionStatement expressionStatement)
            {
                writer.WriteLine($"_ = {EmitExpression(writer, expressionStatement.Expression, function, enumNames, ref tempIndex, diagnostics)};");
            }
            else
            {
                EmitStatement(writer, statement, function, enumNames, ref tempIndex, diagnostics);
            }
        }

        writer.WriteLine($"{resultTemporary} = {EmitExpression(writer, block.ValueExpression, function, enumNames, ref tempIndex, diagnostics)};");
        writer.WriteLine($"goto {joinLabel};");
        writer.Unindent();
        writer.WriteLine("}");
    }

    private static string EmitResultMatch(CSharpTextWriter writer, MirResultMatchExpression match, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        var resultTemporary = $"__cope_tmp{tempIndex++}"; var valueTemporary = $"__cope_tmp{tempIndex++}";
        writer.WriteLine($"var {resultTemporary} = {EmitExpression(writer, match.Scrutinee, function, enumNames, ref tempIndex, diagnostics)};"); writer.WriteLine($"{MapType(match.Type)} {valueTemporary};"); writer.WriteLine($"if ({resultTemporary}.IsOk)"); writer.WriteLine("{"); writer.Indent(); writer.WriteLine($"var {CSharpNameMangler.Mangle(match.OkBinding.Name)} = {resultTemporary}.Value;"); writer.WriteLine($"{valueTemporary} = {EmitExpression(writer, match.OkExpression, function, enumNames, ref tempIndex, diagnostics)};"); writer.Unindent(); writer.WriteLine("}"); writer.WriteLine("else"); writer.WriteLine("{"); writer.Indent(); writer.WriteLine($"var {CSharpNameMangler.Mangle(match.ErrBinding.Name)} = {resultTemporary}.Error;"); writer.WriteLine($"{valueTemporary} = {EmitExpression(writer, match.ErrExpression, function, enumNames, ref tempIndex, diagnostics)};"); writer.Unindent(); writer.WriteLine("}"); return valueTemporary;
    }

    private static string EmitEnumMatch(CSharpTextWriter writer, MirMatchExpression match, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        if (match.Scrutinee.Type is not MirType enumType || match.Scrutinee.Type is MirArrayType or MirResultType || !enumNames.Contains(enumType.Identifier)) return UnsupportedExpression(match, diagnostics);
        var scrutinee = EmitExpression(writer, match.Scrutinee, function, enumNames, ref tempIndex, diagnostics);
        var arms = new List<string>();
        foreach (var arm in match.Arms)
        {
            var pattern = arm.PayloadBindings.Count == 0 ? $"{CSharpNameMangler.Mangle(enumType.Identifier)}.{CSharpNameMangler.Mangle(arm.CaseName)} _" : $"{CSharpNameMangler.Mangle(enumType.Identifier)}.{CSharpNameMangler.Mangle(arm.CaseName)}({string.Join(", ", arm.PayloadBindings.Select(binding => $"var {CSharpNameMangler.Mangle(binding.Name)}"))})";
            arms.Add($"{pattern} => {EmitExpression(writer, arm.Expression, function, enumNames, ref tempIndex, diagnostics)}");
        }
        arms.Add("_ => throw new global::System.InvalidOperationException(\"Non-exhaustive match.\")");
        return $"{scrutinee} switch {{ {string.Join(", ", arms)} }}";
    }

    private static List<string> EmitArguments(IReadOnlyList<MirExpression> expressions, CSharpTextWriter writer, MirFunction function, IReadOnlySet<string> enumNames, ref int tempIndex, List<CSharpDiagnostic> diagnostics)
    {
        var values = new List<string>(expressions.Count);
        foreach (var expression in expressions) values.Add(EmitExpression(writer, expression, function, enumNames, ref tempIndex, diagnostics));
        return values;
    }

    private static string UnsupportedExpression(MirExpression expression, List<CSharpDiagnostic> diagnostics) { diagnostics.Add(new CSharpDiagnostic("COPE-CS-0001", $"Unsupported MIR expression: {expression.GetType().Name}")); return "default!"; }
    private static string MapType(MirType type) => type switch { MirType { Identifier: "number" } => "double", MirType { Identifier: "string" } => "string", MirType { Identifier: "boolean" } => "bool", MirType { Identifier: "void" } => "void", MirArrayType array => MapType(array.ElementType) + "[]", MirResultType result => $"CopeResult<{MapResultComponentType(result.SuccessType)}, {MapType(result.ErrorType)}>", MirType named => CSharpNameMangler.Mangle(named.Identifier), _ => throw new InvalidOperationException("Unknown structured MIR type.") };
    private static string MapValueStorageType(MirType type) => type is MirNamedType { Identifier: "void" } ? "CopeUnit" : MapType(type);
    private static string MapResultComponentType(MirType type) => type is MirNamedType { Identifier: "void" } ? "CopeUnit" : MapType(type);

    private static bool ProgramUsesResult(MirProgram program) => EnumerateTypes(program).Any(MirTypeFacts.ContainsResult);

    private static bool ProgramUsesUnwrap(MirProgram program)
        => program.Functions.Any(function => function.Body.Any(StatementUsesUnwrap));

    private static bool StatementUsesUnwrap(MirStatement statement)
    {
        return statement switch
        {
            MirVariableDeclarationStatement declaration => ExpressionUsesUnwrap(declaration.Initializer),
            MirExpressionStatement expression => ExpressionUsesUnwrap(expression.Expression),
            MirReturnStatement { Expression: not null } returnStatement => ExpressionUsesUnwrap(returnStatement.Expression),
            MirIfStatement conditional =>
                ExpressionUsesUnwrap(conditional.Condition)
                || conditional.ThenStatements.Any(StatementUsesUnwrap)
                || (conditional.ElseStatements?.Any(StatementUsesUnwrap) ?? false),
            _ => false,
        };
    }

    private static bool ExpressionUsesUnwrap(MirExpression expression)
    {
        return expression switch
        {
            MirUnwrapExpression => true,
            MirAssignmentExpression assignment => ExpressionUsesUnwrap(assignment.Expression),
            MirUnaryExpression unary => ExpressionUsesUnwrap(unary.Operand),
            MirBinaryExpression binary => ExpressionUsesUnwrap(binary.Left) || ExpressionUsesUnwrap(binary.Right),
            MirCallExpression call => call.Arguments.Any(ExpressionUsesUnwrap),
            MirArrayExpression array => array.Elements.Any(ExpressionUsesUnwrap),
            MirEnumValueExpression value => value.Arguments.Any(ExpressionUsesUnwrap),
            MirMatchExpression match => ExpressionUsesUnwrap(match.Scrutinee) || match.Arms.Any(arm => ExpressionUsesUnwrap(arm.Expression)),
            MirResultMatchExpression match => ExpressionUsesUnwrap(match.Scrutinee) || ExpressionUsesUnwrap(match.OkExpression) || ExpressionUsesUnwrap(match.ErrExpression),
            MirIfExpression conditional => ExpressionUsesUnwrap(conditional.Condition) || ExpressionUsesUnwrap(conditional.ThenExpression) || ExpressionUsesUnwrap(conditional.ElseExpression),
            MirOkExpression ok => ExpressionUsesUnwrap(ok.Payload),
            MirErrExpression err => ExpressionUsesUnwrap(err.Payload),
            MirPropagateExpression propagation => ExpressionUsesUnwrap(propagation.Operand),
            MirTryExpression tryExpression => ValueBlockUsesUnwrap(tryExpression.Protected) || ValueBlockUsesUnwrap(tryExpression.Handler),
            _ => false,
        };
    }

    private static bool ValueBlockUsesUnwrap(MirValueBlock block)
        => block.PrefixStatements.Any(StatementUsesUnwrap)
            || ExpressionUsesUnwrap(block.ValueExpression);
    private static IEnumerable<MirType> EnumerateTypes(MirProgram program)
    {
        foreach (var function in program.Functions) { yield return function.ReturnType; foreach (var parameter in function.Parameters) yield return parameter.Type; foreach (var local in function.Locals) yield return local.Type; }
        foreach (var @enum in program.Enums) foreach (var @case in @enum.Cases) foreach (var field in @case.PayloadFields) yield return field.Type;
    }
    private static bool ContainsVoidResult(MirType type) => type switch { MirResultType result => result.SuccessType is MirNamedType { Identifier: "void" } || ContainsVoidResult(result.SuccessType) || ContainsVoidResult(result.ErrorType), MirArrayType array => ContainsVoidResult(array.ElementType), _ => false };
    private static List<string> CollectErrorNominalTypes(MirProgram program, IReadOnlySet<string> enumNames)
    {
        var names = new HashSet<string>(StringComparer.Ordinal); foreach (var type in EnumerateTypes(program)) Collect(type, names, enumNames); return names.OrderBy(name => name, StringComparer.Ordinal).ToList();
    }
    private static void Collect(MirType type, ISet<string> names, IReadOnlySet<string> enumNames)
    {
        switch (type) { case MirResultType result: CollectError(result.ErrorType, names, enumNames); Collect(result.SuccessType, names, enumNames); break; case MirArrayType array: Collect(array.ElementType, names, enumNames); break; }
    }
    private static void CollectError(MirType type, ISet<string> names, IReadOnlySet<string> enumNames)
    {
        switch (type) { case MirNamedType named when named.Identifier is not ("number" or "string" or "boolean" or "void" or "error") && !enumNames.Contains(named.Identifier): names.Add(named.Identifier); break; case MirResultType result: CollectError(result.ErrorType, names, enumNames); Collect(result.SuccessType, names, enumNames); break; case MirArrayType array: CollectError(array.ElementType, names, enumNames); break; }
    }
}
