using System.Globalization;
using System.Reflection;
using System.Collections.Immutable;
using Copeland.TS.Mir;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using RoslynCSharpCompilation = Microsoft.CodeAnalysis.CSharp.CSharpCompilation;

namespace Copeland.TS.Backend.CSharp;

/// <summary>Read-only rendering bridge over the exact, generated query result columns.</summary>
public interface ITypedQueryResult
{
    int RowCount { get; }
    object? GetValue(int rowIndex, int columnIndex);
}

public sealed record CSharpQuerySourceArtifact(string StableId, string HintName, string SourceText);

/// <summary>
/// Bounded Roslyn generator. Its input is already-resolved Copeland C# source;
/// it does not inspect project symbols or bind TableScript expressions.
/// </summary>
[Generator]
internal sealed class CopelandQueryGenerator(CSharpQuerySourceArtifact artifact) : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
        => context.RegisterPostInitializationOutput(output => output.AddSource(artifact.HintName, SourceText.From(artifact.SourceText, System.Text.Encoding.UTF8)));
}

public static class CSharpTableQueryMaterializer
{
    public static CSharpQuerySourceArtifact CreateArtifact(MirTableQueryArtifact query)
        => new(query.StableId, "CopelandQuery_" + query.StableId + ".g.cs", WriteSource(query));

    public static ITypedQueryResult Execute(MirProgram program, MirTableQueryArtifact query)
    {
        CSharpCompilation emitted = CSharpBackend.Emit(program);
        if (emitted.Diagnostics.Count > 0)
        {
            throw new CSharpQueryMaterializationException(emitted.Diagnostics[0].Message);
        }

        CSharpQuerySourceArtifact source = CreateArtifact(query);
        SyntaxTree baseTree = CSharpSyntaxTree.ParseText(emitted.SourceText);
        RoslynCSharpCompilation baseCompilation = RoslynCSharpCompilation.Create(
            "CopelandQuery_" + query.StableId,
            [baseTree],
            TrustedPlatformReferences().Append(MetadataReference.CreateFromFile(typeof(ITypedQueryResult).Assembly.Location)),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new CopelandQueryGenerator(source).AsSourceGenerator());
        driver = driver.RunGeneratorsAndUpdateCompilation(baseCompilation, out Compilation updatedCompilation, out ImmutableArray<Diagnostic> generatorDiagnostics);
        Diagnostic? failure = generatorDiagnostics.Concat(updatedCompilation.GetDiagnostics()).FirstOrDefault(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
        if (failure is not null)
        {
            throw new CSharpQueryMaterializationException(failure.GetMessage(CultureInfo.InvariantCulture));
        }

        using var assemblyBytes = new MemoryStream();
        Microsoft.CodeAnalysis.Emit.EmitResult result = updatedCompilation.Emit(assemblyBytes);
        if (!result.Success)
        {
            Diagnostic diagnostic = result.Diagnostics.First(item => item.Severity == DiagnosticSeverity.Error);
            throw new CSharpQueryMaterializationException(diagnostic.GetMessage(CultureInfo.InvariantCulture));
        }

        Assembly assembly = Assembly.Load(assemblyBytes.ToArray());
        string typeName = "Copeland.Generated.__CopelandQuery_" + query.StableId;
        Type type = assembly.GetType(typeName) ?? throw new CSharpQueryMaterializationException("Generated query entry type was not found.");
        MethodInfo execute = type.GetMethod("Execute", BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Static)
            ?? throw new CSharpQueryMaterializationException("Generated query Execute entry was not found.");
        return execute.Invoke(null, null) as ITypedQueryResult
            ?? throw new CSharpQueryMaterializationException("Generated query did not return the typed result contract.");
    }

    private static IEnumerable<MetadataReference> TrustedPlatformReferences()
        => ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") ?? string.Empty)
            .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
            .Select(path => MetadataReference.CreateFromFile(path));

    private static string WriteSource(MirTableQueryArtifact query)
    {
        var writer = new QueryWriter();
        string id = query.StableId;
        string resultType = "__CopelandQueryResult_" + id;
        string queryType = "__CopelandQuery_" + id;
        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line("using System.Linq;");
        writer.Line("namespace Copeland.Generated;");
        writer.Line();
        WriteResultType(writer, query, resultType);
        writer.Line();
        writer.Line("internal static class " + queryType);
        writer.Open();
        if (query.Aggregates.Count > 0) WriteAggregateTypes(writer, query);
        writer.Line("internal static global::Copeland.TS.Backend.CSharp.ITypedQueryResult Execute()");
        writer.Open();
        writer.Line("var table = CopelandModule.__CopelandQueryTable_" + Encode(query.SourceRelationId.Value) + ";");
        WriteExecution(writer, query, resultType);
        writer.Close();
        writer.Close();
        return writer.ToString();
    }

    private static void WriteResultType(QueryWriter writer, MirTableQueryArtifact query, string resultType)
    {
        writer.Line("internal sealed class " + resultType + " : global::Copeland.TS.Backend.CSharp.ITypedQueryResult");
        writer.Open();
        foreach (MirTableQueryResultColumn column in query.ResultColumns)
        {
            writer.Line("internal " + MapType(column.Type) + "[] " + ColumnProperty(column.ValueIndex) + " { get; }");
        }
        writer.Line();
        writer.Line("internal " + resultType + "(" + string.Join(", ", query.ResultColumns.Select(column => MapType(column.Type) + "[] c" + column.ValueIndex)) + ")");
        writer.Open();
        foreach (MirTableQueryResultColumn column in query.ResultColumns) writer.Line(ColumnProperty(column.ValueIndex) + " = c" + column.ValueIndex + ";");
        writer.Close();
        writer.Line("public int RowCount => " + (query.ResultColumns.Count == 0 ? "0" : ColumnProperty(0) + ".Length") + ";");
        writer.Line("public object? GetValue(int rowIndex, int columnIndex)");
        writer.Open();
        writer.Line("return columnIndex switch");
        writer.Open();
        foreach (MirTableQueryResultColumn column in query.ResultColumns) writer.Line(column.ValueIndex + " => " + ColumnProperty(column.ValueIndex) + "[rowIndex],");
        writer.Line("_ => throw new global::System.ArgumentOutOfRangeException(nameof(columnIndex)),");
        writer.Close(";");
        writer.Close();
        writer.Close();
    }

    private static void WriteExecution(QueryWriter writer, MirTableQueryArtifact query, string resultType)
    {
        if (query.Aggregates.Count == 0)
        {
            foreach (MirTableQueryResultColumn result in query.ResultColumns) writer.Line("var c" + result.ValueIndex + " = new global::System.Collections.Generic.List<" + MapType(result.Type) + ">();");
            foreach (MirTableQueryOrderTerm term in query.Ordering.Where(term => term.SourceIndex is not null)) writer.Line("var o" + term.SourceIndex + " = new global::System.Collections.Generic.List<" + MapType(term.Type) + ">();");
            writer.Line("for (int sourceIndex = 0; sourceIndex < table.Count; sourceIndex++)");
            writer.Open();
            WriteSourceValues(writer, query);
            if (query.PredicateCSharp is not null) writer.Line("if (!(" + query.PredicateCSharp + ")) continue;");
            foreach (MirTableQueryProjection projection in query.Projection) writer.Line("c" + ResultIndex(query, projection.Name) + ".Add(__q" + projection.SourceIndex + ");");
            foreach (MirTableQueryOrderTerm term in query.Ordering.Where(term => term.SourceIndex is not null)) writer.Line("o" + term.SourceIndex + ".Add(__q" + term.SourceIndex + ");");
            writer.Close();
            WriteOrderAndPage(writer, query, resultType, "c", writer);
            return;
        }

        writer.Line("var groups = new global::System.Collections.Generic.List<__Group>();");
        if (query.GroupKeys.Count == 0) writer.Line("groups.Add(new __Group(0));");
        else writer.Line("var groupIndex = new global::System.Collections.Generic.Dictionary<__Key, __Group>();");
        writer.Line("for (int sourceIndex = 0; sourceIndex < table.Count; sourceIndex++)");
        writer.Open();
        WriteSourceValues(writer, query);
        if (query.PredicateCSharp is not null) writer.Line("if (!(" + query.PredicateCSharp + ")) continue;");
        if (query.GroupKeys.Count > 0)
        {
            writer.Line("var key = new __Key(" + string.Join(", ", query.GroupKeys.Select(key => "__q" + key.SourceIndex)) + ");");
            writer.Line("if (!groupIndex.TryGetValue(key, out __Group? group))");
            writer.Open();
            writer.Line("group = new __Group(sourceIndex, key);");
            writer.Line("groupIndex.Add(key, group);");
            writer.Line("groups.Add(group);");
            writer.Close();
        }
        else writer.Line("__Group group = groups[0];");
        foreach (MirTableQueryAggregate aggregate in query.Aggregates) WriteAccumulatorAdd(writer, query, aggregate);
        writer.Close();
        foreach (MirTableQueryResultColumn result in query.ResultColumns) writer.Line("var c" + result.ValueIndex + " = new global::System.Collections.Generic.List<" + MapType(result.Type) + ">();");
        writer.Line("foreach (__Group group in groups)");
        writer.Open();
        foreach (MirTableQueryGroupKey key in query.GroupKeys) writer.Line("c" + ResultIndex(query, key.Name) + ".Add(group.Key" + key.SourceIndex + ");");
        foreach (MirTableQueryAggregate aggregate in query.Aggregates) writer.Line("c" + ResultIndex(query, aggregate.Name) + ".Add(" + AggregateValue(query, aggregate) + ");");
        writer.Close();
        WriteOrderAndPage(writer, query, resultType, "c", writer);
    }

    private static void WriteSourceValues(QueryWriter writer, MirTableQueryArtifact query)
    {
        foreach (MirTableQueryColumn column in query.SourceColumns)
            writer.Line("var __q" + column.SourceIndex + " = table.__read_" + Encode(column.Id.Value) + "(sourceIndex);");
    }

    private static void WriteAggregateTypes(QueryWriter writer, MirTableQueryArtifact query)
    {
        if (query.GroupKeys.Count > 0)
        {
            writer.Line("private readonly record struct __Key(" + string.Join(", ", query.GroupKeys.Select(key => MapType(query.SourceColumns[key.SourceIndex].Type) + " Key" + key.SourceIndex)) + ");");
        }
        writer.Line("private sealed class __Group");
        writer.Open();
        writer.Line("internal int FirstSourceIndex { get; }");
        if (query.GroupKeys.Count > 0)
        {
            foreach (MirTableQueryGroupKey key in query.GroupKeys) writer.Line("internal " + MapType(query.SourceColumns[key.SourceIndex].Type) + " Key" + key.SourceIndex + " => Key.Key" + key.SourceIndex + ";");
            writer.Line("internal __Key Key { get; }");
            writer.Line("internal __Group(int firstSourceIndex, __Key key) { FirstSourceIndex = firstSourceIndex; Key = key; }");
        }
        else writer.Line("internal __Group(int firstSourceIndex) { FirstSourceIndex = firstSourceIndex; }");
        foreach (MirTableQueryAggregate aggregate in query.Aggregates)
        {
            string field = "A" + AggregateIndex(query, aggregate);
            switch (aggregate.Kind)
            {
                case MirTableQueryAggregateKind.Count: writer.Line("internal int " + field + ";"); break;
                case MirTableQueryAggregateKind.Sum: writer.Line("internal " + MapType(aggregate.Type) + " " + field + ";"); break;
                case MirTableQueryAggregateKind.Average: writer.Line("internal double " + field + "Total;"); writer.Line("internal int " + field + "Count;"); break;
                case MirTableQueryAggregateKind.Min:
                case MirTableQueryAggregateKind.Max: writer.Line("internal bool " + field + "HasValue;"); writer.Line("internal " + MapType(aggregate.Type) + " " + field + " = default!;"); break;
            }
        }
        writer.Close();
    }

    private static void WriteAccumulatorAdd(QueryWriter writer, MirTableQueryArtifact query, MirTableQueryAggregate aggregate)
    {
        string field = "A" + AggregateIndex(query, aggregate);
        string value = aggregate.InputIndex < 0 ? "default" : "__q" + aggregate.InputIndex;
        switch (aggregate.Kind)
        {
            case MirTableQueryAggregateKind.Count: writer.Line("group." + field + "++;"); break;
            case MirTableQueryAggregateKind.Sum: writer.Line("group." + field + " += " + value + ";"); break;
            case MirTableQueryAggregateKind.Average: writer.Line("group." + field + "Total += " + value + ";"); writer.Line("group." + field + "Count++;"); break;
            case MirTableQueryAggregateKind.Min: writer.Line("if (!group." + field + "HasValue || global::System.Collections.Generic.Comparer<" + MapType(aggregate.Type) + ">.Default.Compare(" + value + ", group." + field + ") < 0) { group." + field + " = " + value + "; group." + field + "HasValue = true; }"); break;
            case MirTableQueryAggregateKind.Max: writer.Line("if (!group." + field + "HasValue || global::System.Collections.Generic.Comparer<" + MapType(aggregate.Type) + ">.Default.Compare(" + value + ", group." + field + ") > 0) { group." + field + " = " + value + "; group." + field + "HasValue = true; }"); break;
        }
    }

    private static string AggregateValue(MirTableQueryArtifact query, MirTableQueryAggregate aggregate)
    {
        string field = "group.A" + AggregateIndex(query, aggregate);
        return aggregate.Kind switch
        {
            MirTableQueryAggregateKind.Count => field,
            MirTableQueryAggregateKind.Sum => field,
            MirTableQueryAggregateKind.Average => field + "Count == 0 ? throw new global::System.InvalidOperationException(\"Aggregate 'average' is not defined for empty input. Use count() or sum(), or filter only when a value exists.\") : " + field + "Total / " + field + "Count",
            MirTableQueryAggregateKind.Min => field + "HasValue ? " + field + " : throw new global::System.InvalidOperationException(\"Aggregate 'min' is not defined for empty input. Use count() or sum(), or filter only when a value exists.\")",
            MirTableQueryAggregateKind.Max => field + "HasValue ? " + field + " : throw new global::System.InvalidOperationException(\"Aggregate 'max' is not defined for empty input. Use count() or sum(), or filter only when a value exists.\")",
            _ => throw new InvalidOperationException("Unknown aggregate."),
        };
    }

    private static void WriteOrderAndPage(QueryWriter writer, MirTableQueryArtifact query, string resultType, string prefix, QueryWriter _)
    {
        writer.Line("var order = global::System.Linq.Enumerable.Range(0, " + prefix + "0.Count).ToList();");
        if (query.Ordering.Count > 0)
        {
            writer.Line("order.Sort((left, right) =>");
            writer.Open();
            foreach (var entry in query.Ordering.Select((term, index) => new { Term = term, Index = index }))
            {
                MirTableQueryOrderTerm term = entry.Term;
                string values = term.SourceIndex is null ? prefix + term.ValueIndex : "o" + term.SourceIndex;
                writer.Line("int comparison" + entry.Index + " = global::System.Collections.Generic.Comparer<" + MapType(term.Type) + ">.Default.Compare(" + values + "[left], " + values + "[right]);");
                writer.Line("if (comparison" + entry.Index + " != 0) return " + (term.Descending ? "-comparison" : "comparison") + entry.Index + ";");
            }
            writer.Line("return left.CompareTo(right);");
            writer.Close(");");
        }
        writer.Line("var page = order.Skip(" + query.Skip + ").Take(" + query.Take + ").ToArray();");
        foreach (MirTableQueryResultColumn result in query.ResultColumns) writer.Line("var output" + result.ValueIndex + " = new " + MapType(result.Type) + "[page.Length];");
        writer.Line("for (int index = 0; index < page.Length; index++)");
        writer.Open();
        foreach (MirTableQueryResultColumn result in query.ResultColumns) writer.Line("output" + result.ValueIndex + "[index] = " + prefix + result.ValueIndex + "[page[index]];");
        writer.Close();
        writer.Line("return new " + resultType + "(" + string.Join(", ", query.ResultColumns.Select(column => "output" + column.ValueIndex)) + ");");
    }

    private static int ResultIndex(MirTableQueryArtifact query, string name) => query.ResultColumns.Single(column => column.Name == name).ValueIndex;
    private static int AggregateIndex(MirTableQueryArtifact query, MirTableQueryAggregate aggregate)
    {
        for (int index = 0; index < query.Aggregates.Count; index += 1)
        {
            if (ReferenceEquals(query.Aggregates[index], aggregate) || query.Aggregates[index] == aggregate) return index;
        }
        throw new InvalidOperationException("Aggregate is not part of the query artifact.");
    }
    private static string ColumnProperty(int index) => "Column" + index;
    private static string MapType(MirType type) => type switch
    {
        MirType { Identifier: "int" } => "int",
        MirType { Identifier: "float" or "number" } => "double",
        MirType { Identifier: "string" } => "string",
        MirType { Identifier: "boolean" } => "bool",
        MirType named => named.Identifier,
    };
    private static string Encode(string identity)
    {
        var result = new System.Text.StringBuilder(identity.Length);
        foreach (char character in identity) result.Append(char.IsLetterOrDigit(character) ? character : "_" + ((int)character).ToString("X4", CultureInfo.InvariantCulture));
        return result.ToString();
    }
}

public sealed class CSharpQueryMaterializationException(string message) : Exception(message);

/// <summary>
/// Deprecated parity-only execution helper for the former CLI-private plan.
/// Roslyn remains in compiler/backend infrastructure, never in the CLI.
/// </summary>
public static class CSharpLegacyQueryExecutor
{
    public static Array ExecuteArray(string source, string functionName)
    {
        SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(source);
        RoslynCSharpCompilation compilation = RoslynCSharpCompilation.Create(
            "CopelandLegacyQuery",
            [syntaxTree],
            ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") ?? string.Empty)
                .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
                .Select(path => MetadataReference.CreateFromFile(path)),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        using var assemblyBytes = new MemoryStream();
        Microsoft.CodeAnalysis.Emit.EmitResult result = compilation.Emit(assemblyBytes);
        if (!result.Success)
        {
            Diagnostic diagnostic = result.Diagnostics.First(item => item.Severity == DiagnosticSeverity.Error);
            throw new CSharpQueryMaterializationException(diagnostic.GetMessage(CultureInfo.InvariantCulture));
        }
        Assembly assembly = Assembly.Load(assemblyBytes.ToArray());
        Type module = assembly.GetType("Copeland.Generated.CopelandModule")
            ?? throw new CSharpQueryMaterializationException("Generated Copeland module was not found.");
        MethodInfo method = module.GetMethod(functionName, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static)
            ?? throw new CSharpQueryMaterializationException("Generated query method was not found.");
        return method.Invoke(null, null) as Array
            ?? throw new CSharpQueryMaterializationException("Generated query did not return a row array.");
    }
}

internal sealed class QueryWriter
{
    private readonly System.Text.StringBuilder _text = new();
    private int _indent;
    public void Line(string text = "") => _text.Append(' ', _indent * 4).AppendLine(text);
    public void Open() { Line("{"); _indent += 1; }
    public void Close(string suffix = "") { _indent -= 1; Line("}" + suffix); }
    public override string ToString() => _text.ToString();
}
