<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Dominatus.Audio.Aurelian</AssemblyName>
    <RootNamespace>Dominatus.Audio.Aurelian</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Aurelian/Aurelian.Audio/Aurelian.Audio.csproj" />
    <ProjectReference Include="../../../reference/dominatus/src/Dominatus.Actuators.Audio/Dominatus.Actuators.Audio.csproj" />
  </ItemGroup>
</Project>
