using Aurelian.Shaders.Language.Ast;
using Aurelian.Shaders.Language.Diagnostics;
using Aurelian.Shaders.Language.Emission.Hlsl;
using Aurelian.Shaders.Language.Parsing;
using Aurelian.Shaders.Language.Validation;
using Xunit;

namespace Aurelian.Shaders.Tests;

public sealed class HlslEmissionM0Tests
{
    [Fact]
    public void HlslEmitter_EmitSmokeTriangleFixture_ProducesHlsl()
    {
        var emission = ParseValidateEmitSmokeTriangle();

        Assert.True(emission.Hlsl.Length > 0);
        Assert.Contains("// Generated by Aurelian SDSL-V HLSL M0.", emission.Hlsl);
    }

    [Fact]
    public void HlslEmitter_EmitSmokeTriangleFixture_HasNoDiagnostics()
    {
        var emission = ParseValidateEmitSmokeTriangle();

        Assert.True(emission.Success, FormatDiagnostics(emission.Diagnostics));
        Assert.Empty(emission.Diagnostics);
    }

    [Fact]
    public void HlslEmitter_EmitSmokeTriangleFixture_ContainsRecordStructs()
    {
        var emission = ParseValidateEmitSmokeTriangle();

        Assert.Contains("struct VertexInput", emission.Hlsl);
        Assert.Contains("float3 Position : POSITION;", emission.Hlsl);
        Assert.Contains("float4 Color : COLOR0;", emission.Hlsl);
        Assert.Contains("struct VertexOutput", emission.Hlsl);
    }

    [Fact]
    public void HlslEmitter_EmitSmokeTriangleFixture_ContainsStageFunctions()
    {
        var emission = ParseValidateEmitSmokeTriangle();

        Assert.Contains("VertexOutput VSMain(VertexInput input)", emission.Hlsl);
        Assert.Contains("VertexOutput output;", emission.Hlsl);
        Assert.Contains("output.Position = float4(input.Position, 1.0);", emission.Hlsl);
        Assert.Contains("output.Color = input.Color;", emission.Hlsl);
        Assert.Contains("return output;", emission.Hlsl);
        Assert.Contains("float4 PSMain(VertexOutput input)", emission.Hlsl);
        Assert.Contains("return input.Color;", emission.Hlsl);
    }

    [Fact]
    public void HlslEmitter_UnsupportedFlowDeclaration_ReportsDiagnostic()
    {
        var module = new SdslvModule(
            Namespace: null,
            Uses: [],
            Declarations:
            [
                new SdslvFlowDecl(
                    "UnsupportedFlow",
                    Parameters: [],
                    ReturnType: new SdslvNamedTypeRef(new SdslvPath("void")),
                    Board: null,
                    States: [])
            ]);

        var emission = HlslEmitter.EmitModule(module);

        Assert.False(emission.Success);
        Assert.Contains(emission.Diagnostics, diagnostic =>
            diagnostic.Code == HlslEmissionDiagnosticCodes.UnsupportedDeclarationForHlslM0 &&
            diagnostic.Phase == SdslvDiagnosticPhase.Emission &&
            diagnostic.Severity == SdslvDiagnosticSeverity.Error);
    }

    private static HlslEmissionResult ParseValidateEmitSmokeTriangle()
    {
        var source = ReadFixture("smoke_triangle.sdslv");
        var parse = SdslvParser.ParseModule(source);
        Assert.True(parse.Success, FormatDiagnostics(parse.Diagnostics));

        var validation = SdslvValidator.ValidateModule(parse.Module!);
        Assert.True(validation.Success, FormatDiagnostics(validation.Diagnostics));

        return HlslEmitter.EmitModule(parse.Module!);
    }

    private static string ReadFixture(string name)
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "Sdslv", name);
        if (File.Exists(path))
        {
            return File.ReadAllText(path);
        }

        path = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "Fixtures", "Sdslv", name));
        return File.ReadAllText(path);
    }

    private static string FormatDiagnostics(IEnumerable<SdslvDiagnostic> diagnostics) =>
        string.Join(Environment.NewLine, diagnostics.Select(diagnostic => $"{diagnostic.Code}: {diagnostic.Message}"));
}
