using Aurelian.Shaders.Language.Artifacts;
using Aurelian.Shaders.Language.Diagnostics;
using Aurelian.Shaders.Language.Validation;
using Xunit;

namespace Aurelian.Shaders.Tests;

public sealed class SdslvArtifactM0Tests
{
    [Fact]
    public void SdslvShaderArtifactEmitter_EmitSmokeTriangleFixture_Succeeds()
    {
        var artifact = EmitSmokeTriangle();

        Assert.True(artifact.Success, FormatDiagnostics(artifact.Diagnostics));
        Assert.Equal("aurelian.sdslv.artifact/0", artifact.FormatVersion);
        Assert.Equal("Aurelian SDSL-V", artifact.Language);
        Assert.DoesNotContain(artifact.Diagnostics, x => x.Severity == SdslvDiagnosticSeverity.Error);
    }

    [Fact]
    public void SdslvShaderArtifactEmitter_EmitSmokeTriangleFixture_IncludesSourceHash()
    {
        var source = ReadFixture("smoke_triangle.sdslv");
        var first = SdslvShaderSourceHash.ComputeSha256(source);
        var second = SdslvShaderSourceHash.ComputeSha256(source);
        var artifact = EmitSmokeTriangle();

        Assert.Equal("SHA-256", artifact.SourceHash.Algorithm);
        Assert.Equal(first, second);
        Assert.Equal(first, artifact.SourceHash);
        Assert.Equal(64, artifact.SourceHash.Value.Length);
        Assert.Matches("^[0-9a-f]{64}$", artifact.SourceHash.Value);
    }

    [Fact]
    public void SdslvShaderArtifactEmitter_EmitSmokeTriangleFixture_CollectsStageEntryPoints()
    {
        var artifact = EmitSmokeTriangle();

        Assert.Collection(
            artifact.Stages,
            stage =>
            {
                Assert.Equal("VSMain", stage.EntryPoint);
                Assert.Equal(SdslvShaderStageKind.Vertex, stage.Stage);
                Assert.Equal("vs_6_0", stage.Profile);
            },
            stage =>
            {
                Assert.Equal("PSMain", stage.EntryPoint);
                Assert.Equal(SdslvShaderStageKind.Pixel, stage.Stage);
                Assert.Equal("ps_6_0", stage.Profile);
            });
    }

    [Fact]
    public void SdslvShaderArtifactEmitter_EmitSmokeTriangleFixture_ContainsHlsl()
    {
        var artifact = EmitSmokeTriangle();

        Assert.Contains("// Generated by Aurelian SDSL-V HLSL M0.", artifact.Hlsl);
        Assert.Contains("VertexOutput VSMain(VertexInput input)", artifact.Hlsl);
        Assert.Contains("float4 PSMain(VertexOutput input)", artifact.Hlsl);
    }

    [Fact]
    public void SdslvShaderArtifactJsonWriter_WriteManifest_IsDeterministic()
    {
        var artifact = EmitSmokeTriangle();

        var first = SdslvShaderArtifactJsonWriter.WriteManifest(artifact);
        var second = SdslvShaderArtifactJsonWriter.WriteManifest(artifact);

        Assert.Equal(first, second);
        Assert.Contains("\"formatVersion\"", first);
        Assert.Contains("\"sourceHash\"", first);
        Assert.Contains("\"stages\"", first);
        Assert.Contains("\"hlsl\"", first);
        Assert.Contains("\"success\": true", first);
    }

    [Fact]
    public void SdslvShaderArtifactEmitter_InvalidSource_ReturnsDiagnosticsAndFailure()
    {
        var artifact = SdslvShaderArtifactEmitter.Emit(new SdslvShaderSource(
            "invalid.sdslv",
            "record Surface { Color: float4; Color: float3; }"));

        Assert.False(artifact.Success);
        Assert.Empty(artifact.Hlsl);
        Assert.Contains(artifact.Diagnostics, diagnostic =>
            diagnostic.Code == SdslvValidator.DuplicateFieldCode &&
            diagnostic.Phase == SdslvDiagnosticPhase.Validation &&
            diagnostic.Severity == SdslvDiagnosticSeverity.Error);
    }

    private static SdslvShaderArtifact EmitSmokeTriangle() => SdslvShaderArtifactEmitter.Emit(
        new SdslvShaderSource("Fixtures/Sdslv/smoke_triangle.sdslv", ReadFixture("smoke_triangle.sdslv")));

    private static string ReadFixture(string name)
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "Sdslv", name);
        if (File.Exists(path))
        {
            return File.ReadAllText(path);
        }

        path = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "Fixtures", "Sdslv", name));
        return File.ReadAllText(path);
    }

    private static string FormatDiagnostics(IEnumerable<SdslvDiagnostic> diagnostics) =>
        string.Join(Environment.NewLine, diagnostics.Select(diagnostic => $"{diagnostic.Code}: {diagnostic.Message}"));
}
