// TEMPLATE-TYPE-SYNTAX-M0 canonical project template.
// Typed project metadata lowers to ProjectTree only at the filesystem boundary.

type ProjectName = string;
type TargetFramework = string;

interface CopelandBootstrapProject {
    name: ProjectName;
    target: TargetFramework;
}

record StandardCopelandProject {
    name: ProjectName;
    target: TargetFramework;
}

export template<
    type TProject extends CopelandBootstrapProject = StandardCopelandProject,
    static name: ProjectName,
    static target: TargetFramework = "net10.0"
> BootstrapTemplate: DotNetSolution {
    const packageVersion = "0.1.0-preview.1";
    const projectType = nameOf<TProject>();
    const projectFile = `${name}.csproj`;

    const projectDefinition: ProjectFile = csProjectFile(
        projectFile,
        <Project Sdk="Microsoft.NET.Sdk">
            <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>{target}</TargetFramework>
                <RootNamespace>{name}</RootNamespace>
                <ImplicitUsings>enable</ImplicitUsings>
                <Nullable>enable</Nullable>
                <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
                <CopelandRequiredVersion>{packageVersion}</CopelandRequiredVersion>
            </PropertyGroup>
            <ItemGroup>
                <PackageReference
                    Include="Copeland.TS.Sdk"
                    Version={packageVersion}
                    PrivateAssets="all"
                />
                <CopelandNpmContract Include="contracts/lodash-es.json" />
            </ItemGroup>
        </Project>
    );

    const lodash: NpmDependency = npmDependency("lodash-es", "4.18.1");
    const packageManifest: NpmPackageManifest =
        npmPackageManifest(name, packageVersion, [lodash]);
    const sources: CopelandSourceSet = sourceSet(["src/**", "tests/**"]);
    const projectTypes: CopelandProjectTypeSet = projectTypeSet(["TextDocuments"]);
    const workspace: TypeScriptWorkspace = typeScriptWorkspace(
        `./${projectFile}`,
        sources,
        projectTypes
    );

    // The public quickstart enters the materialization output directly, so the
    // single project is intentionally rooted beside its solution file.
    const project: DotNetProject = dotNetProject("", [
        projectDefinition,
        jsonFile("package.json", packageManifest),
        workspaceFile("tsconfig.tsx", workspace),
        sourceFile("Program.cs", `Console.WriteLine(${name}.Copeland.CopelandProject.greeting("Copeland"));
Console.WriteLine("lodash-es says: helloFromNpm");
`),
        textFile(".copeland/project-type.txt", `${projectType}\n`),
        textFile("contracts/lodash-es.json", `{
  "schemaVersion": 1,
  "package": "lodash-es",
  "version": "4.18.1",
  "materialized": true,
  "exports": []
}
`),
        sourceFile("src/Program.ts", `using System;
using ${name};

export enum GreetingStyle { Friendly, Formal }

export record Greeting { recipient: string; message: string; }

export function greeting(name: string): string {
    return String.Concat(Helper.Decorate(name), " through System.String");
}
`),
        sourceFile("src/GreetingDocument.tsx", `import { Greeting, GreetingStyle } from "./Program";

export function greetingDocument(name: string): Document {
    const style: GreetingStyle = GreetingStyle.Friendly;
    const message: string = match style {
        Friendly => "Hello",
        Formal => "Greetings",
    };
    const initial: Greeting = { recipient: name, message };
    const updated: Greeting = initial with { recipient: "Copeland" };
    return <Document><Paragraph>{updated.message}, {updated.recipient}</Paragraph></Document>;
}
`),
        sourceFile("src/Helper.cs", `namespace ${name};

public static class Helper
{
    public static string Decorate(string value)
    {
        return $"C# says hello to {value}";
    }
}
`),
        testFile("tests/GreetingDocument.tsxtest", `using Xunit;

enum TestStyle { Friendly, Formal }
record TestGreeting { message: string; recipient: string; }

[Fact]
export function enum_match_and_with_work(): void {
    const style: TestStyle = TestStyle.Friendly;
    const message: string = match style { Friendly => "Hello", Formal => "Greetings" };
    const initial: TestGreeting = { message, recipient: "Ada" };
    const updated: TestGreeting = initial with { recipient: "Copeland" };
    Assert.True(updated.message == "Hello");
}
`)
    ]);

    return dotNetSolution(name, project, [
        slnxFile(`${name}.slnx`, projectFile),
        textFile("README.md", `# ${name}

A ${projectType} Copeland TS + .NET project generated by BootstrapTemplate.

Run npm install, dotnet build, dotnet test, then dotnet run.
`)
    ]);
}
