using Aurelian.Shaders.Language.Ast;
using System.Globalization;
using System.Text;
using Aurelian.Shaders.Language.Diagnostics;

namespace Aurelian.Shaders.Language.VdMir.Emission.Hlsl;

public sealed record VdMirHlslEmissionResult(
    string Hlsl,
    IReadOnlyList<VdMirDiagnostic> Diagnostics)
{
    public bool Success => Diagnostics.All(x => x.Severity != SdslvDiagnosticSeverity.Error);
}

public static class VdMirHlslEmitter
{
    public static VdMirHlslEmissionResult EmitModule(VdMirModule module)
    {
        ArgumentNullException.ThrowIfNull(module);

        var emitter = new Emitter(module);
        return emitter.Emit();
    }

    private sealed class Emitter(VdMirModule module)
    {
        private readonly StringBuilder _builder = new();
        private readonly List<VdMirDiagnostic> _diagnostics = [];
        private int _indent;

        public VdMirHlslEmissionResult Emit()
        {
            WriteLine("// Generated by Aurelian VD-MIR HLSL M0.");
            if (module.Namespace is not null)
            {
                WriteLine($"// namespace {module.Namespace}");
            }

            if (module.Namespace is not null || module.Structs.Count > 0 || module.EntryPoints.Count > 0)
            {
                WriteLine();
            }

            foreach (var aggregate in module.Structs)
            {
                EmitStruct(aggregate);
                WriteLine();
            }

            foreach (var entryPoint in module.EntryPoints)
            {
                EmitEntryPoint(entryPoint);
                WriteLine();
            }

            return new VdMirHlslEmissionResult(_builder.ToString(), _diagnostics);
        }

        private void EmitStruct(VdMirStruct aggregate)
        {
            WriteLine($"struct {aggregate.Name} {{");
            Indent();
            foreach (var field in aggregate.Fields)
            {
                var semantic = MapSemantic(field.Semantic);
                if (semantic is null)
                {
                    WriteLine($"{MapType(field.Type)} {field.Name};");
                }
                else
                {
                    WriteLine($"{MapType(field.Type)} {field.Name} : {semantic};");
                }
            }

            Outdent();
            WriteLine("};");
        }

        private void EmitEntryPoint(VdMirEntryPoint entryPoint)
        {
            var parameters = string.Join(", ", entryPoint.Parameters.Select(parameter => $"{MapType(parameter.Type)} {parameter.Name}"));
            var returnSemantic = MapSemantic(entryPoint.ReturnSemantic);
            if (returnSemantic is null)
            {
                WriteLine($"{MapType(entryPoint.ReturnType)} {entryPoint.Name}({parameters})");
            }
            else
            {
                WriteLine($"{MapType(entryPoint.ReturnType)} {entryPoint.Name}({parameters}) : {returnSemantic}");
            }

            WriteLine("{");
            Indent();
            foreach (var statement in entryPoint.Statements)
            {
                EmitStatement(statement);
            }

            Outdent();
            WriteLine("}");
        }

        private void EmitStatement(VdMirStatement statement)
        {
            switch (statement)
            {
                case VdMirLocalStatement local:
                    if (local.Initializer is null)
                    {
                        WriteLine($"{MapType(local.Type)} {local.Name};");
                    }
                    else
                    {
                        WriteLine($"{MapType(local.Type)} {local.Name} = {EmitExpression(local.Initializer)};");
                    }

                    break;
                case VdMirAssignStatement assign:
                    WriteLine($"{EmitExpression(assign.Target)} = {EmitExpression(assign.Value)};");
                    break;
                case VdMirReturnStatement ret:
                    WriteLine($"return {EmitExpression(ret.Value)};");
                    break;
                case VdMirExpressionStatement expression when expression.Value is VdMirIdentifierExpression identifier && string.IsNullOrEmpty(identifier.Name):
                    WriteLine(";");
                    break;
                case VdMirExpressionStatement expression:
                    WriteLine($"{EmitExpression(expression.Value)};");
                    break;
                default:
                    Error(
                        VdMirDiagnosticCodes.UnsupportedStatement,
                        $"VD-MIR HLSL M0 does not recognize statement shape '{statement.GetType().Name}'.",
                        statement.Span);
                    break;
            }
        }

        private string EmitExpression(VdMirExpression expression)
        {
            return expression switch
            {
                VdMirIdentifierExpression identifier => identifier.Name,
                VdMirIntegerLiteralExpression integer => integer.Value,
                VdMirFloatLiteralExpression floating => floating.Value,
                VdMirBoolLiteralExpression boolean => boolean.Value ? "true" : "false",
                VdMirFieldAccessExpression fieldAccess => $"{EmitExpression(fieldAccess.Base)}.{fieldAccess.Field}",
                VdMirCallExpression call => $"{EmitExpression(call.Callee)}({string.Join(", ", call.Arguments.Select(EmitExpression))})",
                VdMirBinaryExpression binary => $"({EmitExpression(binary.Left)} {MapBinaryOperator(binary.Operator)} {EmitExpression(binary.Right)})",
                VdMirUnaryExpression unary => $"{MapUnaryOperator(unary.Operator)}{EmitExpression(unary.Operand)}",
                _ => UnsupportedExpression(expression),
            };
        }

        private string UnsupportedExpression(VdMirExpression expression)
        {
            Error(
                VdMirDiagnosticCodes.UnsupportedExpression,
                $"VD-MIR HLSL M0 does not support expression shape '{expression.GetType().Name}'.",
                expression.Span);
            return "/* unsupported */";
        }

        private string MapType(VdMirType type)
        {
            return type switch
            {
                VdMirVoidType => "void",
                VdMirScalarType scalar => scalar.DisplayName,
                VdMirVectorType vector => vector.DisplayName,
                VdMirMatrixType matrix => matrix.DisplayName,
                VdMirStructType structure => structure.Name,
                _ => UnsupportedType(type),
            };
        }

        private string UnsupportedType(VdMirType type)
        {
            Error(
                VdMirDiagnosticCodes.UnsupportedType,
                $"VD-MIR HLSL M0 does not recognize type shape '{type.GetType().Name}'.",
                VdMirSpanFromType(type));
            return "/* unsupported-type */";
        }

        private static string? MapSemantic(VdMirSemanticKind semantic) => semantic switch
        {
            VdMirSemanticKind.Position => "POSITION",
            VdMirSemanticKind.Color0 => "COLOR0",
            VdMirSemanticKind.SvPosition => "SV_Position",
            VdMirSemanticKind.SvTarget0 => "SV_Target0",
            _ => null,
        };

        private static string MapBinaryOperator(SdslvBinaryOperator op) => op switch
        {
            SdslvBinaryOperator.Add => "+",
            SdslvBinaryOperator.Subtract => "-",
            SdslvBinaryOperator.Multiply => "*",
            SdslvBinaryOperator.Divide => "/",
            SdslvBinaryOperator.Modulo => "%",
            SdslvBinaryOperator.LogicalOr => "||",
            SdslvBinaryOperator.LogicalAnd => "&&",
            SdslvBinaryOperator.Equal => "==",
            SdslvBinaryOperator.NotEqual => "!=",
            SdslvBinaryOperator.Less => "<",
            SdslvBinaryOperator.LessEqual => "<=",
            SdslvBinaryOperator.Greater => ">",
            SdslvBinaryOperator.GreaterEqual => ">=",
            _ => "/* unsupported-op */",
        };

        private static string MapUnaryOperator(SdslvUnaryOperator op) => op switch
        {
            SdslvUnaryOperator.Negate => "-",
            SdslvUnaryOperator.Not => "!",
            _ => "/* unsupported-unary */",
        };

        private static Ast.SdslvSpan VdMirSpanFromType(VdMirType type)
        {
            _ = type;
            return Ast.SdslvSpan.Unknown;
        }

        private void WriteLine(string text = "")
        {
            if (text.Length > 0)
            {
                _builder.Append(new string(' ', _indent * 4));
            }

            _builder.AppendLine(text);
        }

        private void Indent() => _indent++;

        private void Outdent() => _indent = Math.Max(0, _indent - 1);

        private void Error(string code, string message, Ast.SdslvSpan span)
        {
            _diagnostics.Add(new VdMirDiagnostic(
                code,
                SdslvDiagnosticSeverity.Error,
                message,
                span));
        }
    }
}
