using Aurelian.Shaders.Language.Ast;
using Aurelian.Shaders.Language.Diagnostics;
using Aurelian.Shaders.Language.Emission.Hlsl;
using Aurelian.Shaders.Language.Parsing;
using Aurelian.Shaders.Language.Validation;
using Aurelian.Shaders.Language.VdMir;
using Aurelian.Shaders.Language.VdMir.Emission.Hlsl;
using Aurelian.Shaders.Language.VdMir.Lowering;
using Xunit;

namespace Aurelian.Shaders.Tests;

public sealed class VdMirHlslEmitterTests
{
    [Fact]
    public void VdMirHlslEmitter_CanEmitSmokeTriangleHlsl()
    {
        var emission = EmitSmokeTriangle();

        Assert.True(emission.Success, FormatDiagnostics(emission.Diagnostics));
        Assert.Contains("// Generated by Aurelian VD-MIR HLSL M0.", emission.Hlsl);
    }

    [Fact]
    public void VdMirHlslEmitter_EmitsVertexEntryPoint()
    {
        var emission = EmitSmokeTriangle();

        Assert.Contains("VertexOutput VSMain(VertexInput input)", emission.Hlsl);
        Assert.Contains("output.Position = float4(input.Position, 1.0);", emission.Hlsl);
    }

    [Fact]
    public void VdMirHlslEmitter_EmitsPixelEntryPoint()
    {
        var emission = EmitSmokeTriangle();

        Assert.Contains("float4 PSMain(VertexOutput input) : SV_Target0", emission.Hlsl);
        Assert.Contains("return input.Color;", emission.Hlsl);
    }

    [Fact]
    public void VdMirHlslEmitter_KeepsHlslSemanticsInBackend()
    {
        var module = LowerSmokeTriangle();
        var emission = VdMirHlslEmitter.EmitModule(module);

        Assert.Contains(module.Structs.SelectMany(x => x.Fields), field => field.Semantic == VdMirSemanticKind.SvPosition);
        Assert.Contains(module.Structs.SelectMany(x => x.Fields), field => field.Semantic == VdMirSemanticKind.Color0);
        Assert.Contains("SV_Position", emission.Hlsl);
        Assert.Contains("COLOR0", emission.Hlsl);
    }

    [Fact]
    public void VdMirHlslEmitter_DoesNotRequireDxc()
    {
        var references = typeof(VdMirHlslEmitter).Assembly.GetReferencedAssemblies().Select(reference => reference.Name).ToArray();

        Assert.DoesNotContain("Aurelian.Graphics", references);
        Assert.DoesNotContain("Silk.NET.Vulkan", references);
    }

    [Fact]
    public void M14a_DirectHlslPathStillWorks()
    {
        var source = ReadFixture("smoke_triangle.sdslv");
        var parse = SdslvParser.ParseModule(source);
        Assert.True(parse.Success, FormatSourceDiagnostics(parse.Diagnostics));

        var validation = SdslvValidator.ValidateModule(parse.Module!);
        Assert.True(validation.Success, FormatSourceDiagnostics(validation.Diagnostics));

        var directEmission = HlslEmitter.EmitModule(parse.Module!);
        var vdMirEmission = EmitSmokeTriangle();

        Assert.True(directEmission.Success, FormatSourceDiagnostics(directEmission.Diagnostics));
        Assert.Contains("VertexOutput VSMain(VertexInput input)", directEmission.Hlsl);
        Assert.Contains("float4 PSMain(VertexOutput input)", directEmission.Hlsl);
        Assert.Contains("output.Position = float4(input.Position, 1.0);", vdMirEmission.Hlsl);
        Assert.Contains("return input.Color;", vdMirEmission.Hlsl);
    }

    private static VdMirModule LowerSmokeTriangle()
    {
        var source = ReadFixture("smoke_triangle.sdslv");
        var parse = SdslvParser.ParseModule(source);
        Assert.True(parse.Success, FormatSourceDiagnostics(parse.Diagnostics));

        var validation = SdslvValidator.ValidateModule(parse.Module!);
        Assert.True(validation.Success, FormatSourceDiagnostics(validation.Diagnostics));

        return VdMirM0Lowerer.LowerModule(parse.Module!);
    }

    private static VdMirHlslEmissionResult EmitSmokeTriangle() =>
        VdMirHlslEmitter.EmitModule(LowerSmokeTriangle());

    private static string ReadFixture(string name)
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "Sdslv", name);
        if (File.Exists(path))
        {
            return File.ReadAllText(path);
        }

        path = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "Fixtures", "Sdslv", name));
        return File.ReadAllText(path);
    }

    private static string FormatDiagnostics(IEnumerable<VdMirDiagnostic> diagnostics) =>
        string.Join(Environment.NewLine, diagnostics.Select(diagnostic => $"{diagnostic.Code}: {diagnostic.Message}"));

    private static string FormatSourceDiagnostics(IEnumerable<SdslvDiagnostic> diagnostics) =>
        string.Join(Environment.NewLine, diagnostics.Select(diagnostic => $"{diagnostic.Code}: {diagnostic.Message}"));
}
