<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Copeland/Copeland.TS/Copeland.TS.csproj" />
    <ProjectReference Include="../../src/Copeland/Copeland.TS.Backend.CSharp/Copeland.TS.Backend.CSharp.csproj" />
  </ItemGroup>
</Project>