// <auto-generated />
#nullable enable

namespace Copeland.Generated;

internal static class CopeArray
{
    public static T[] Create<T>(int length)
    {
        if (length < 0)
        {
            throw new global::System.ArgumentOutOfRangeException(nameof(length), "Copeland mutable array length cannot be negative.");
        }
        return new T[length];
    }
    public static T Get<T>(T[] values, int index)
    {
        if (index < 0 || index >= values.Length)
        {
            throw new global::System.IndexOutOfRangeException("Copeland array index is out of bounds.");
        }
        return values[index];
    }
    public static T Set<T>(T[] values, int index, T value)
    {
        if (index < 0 || index >= values.Length)
        {
            throw new global::System.IndexOutOfRangeException("Copeland array index is out of bounds.");
        }
        values[index] = value;
        return value;
    }
}

public readonly struct CopeResult<TValue, TError>
{
    private readonly TValue _value;
    private readonly TError _error;
    public bool IsOk { get; }

    public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException("Result has no value.");
    public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException("Result has no error.");

    private CopeResult(bool isOk, TValue value, TError error)
    {
        IsOk = isOk;
        _value = value;
        _error = error;
    }

    public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);
    public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);
}

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(double value0, double value1)
    {
        __field_r1_002Ef0 = value0;
        __field_r1_002Ef1 = value1;
    }

    internal double __field_r1_002Ef0 { get; }

    internal double __field_r1_002Ef1 { get; }
}

public sealed class __CopeRecord_r2
{
    internal __CopeRecord_r2(int value0, int value1)
    {
        __field_r2_002Ef0 = value0;
        __field_r2_002Ef1 = value1;
    }

    internal int __field_r2_002Ef0 { get; }

    internal int __field_r2_002Ef1 { get; }
}

public sealed class __CopeRecord_r3
{
    internal __CopeRecord_r3(string value0, int value1, double value2)
    {
        __field_r3_002Ef0 = value0;
        __field_r3_002Ef1 = value1;
        __field_r3_002Ef2 = value2;
    }

    internal string __field_r3_002Ef0 { get; }

    internal int __field_r3_002Ef1 { get; }

    internal double __field_r3_002Ef2 { get; }
}

public sealed class __CopeRecord_r6
{
    internal __CopeRecord_r6(string value0, string value1, double value2)
    {
        __field_r6_002Ef0 = value0;
        __field_r6_002Ef1 = value1;
        __field_r6_002Ef2 = value2;
    }

    public string __field_r6_002Ef0 { get; }

    internal string __field_r6_002Ef1 { get; }

    public double __field_r6_002Ef2 { get; }
}

public sealed class __CopeRecord_r4
{
    internal __CopeRecord_r4(string value0, string value1, __CopeRecord_r1 value2)
    {
        __field_r4_002Ef0 = value0;
        __field_r4_002Ef1 = value1;
        __field_r4_002Ef2 = value2;
    }

    internal string __field_r4_002Ef0 { get; }

    internal string __field_r4_002Ef1 { get; }

    internal __CopeRecord_r1 __field_r4_002Ef2 { get; }
}

public sealed class __CopeRecord_r5
{
    internal __CopeRecord_r5(int value0, __CopeRecord_r4 value1, __CopeRecord_r3[] value2, __CopeRecord_r6 value3, Fulfillment value4)
    {
        __field_r5_002Ef0 = value0;
        __field_r5_002Ef1 = value1;
        __field_r5_002Ef2 = value2;
        __field_r5_002Ef3 = value3;
        __field_r5_002Ef4 = value4;
    }

    internal int __field_r5_002Ef0 { get; }

    internal __CopeRecord_r4 __field_r5_002Ef1 { get; }

    internal __CopeRecord_r3[] __field_r5_002Ef2 { get; }

    internal __CopeRecord_r6 __field_r5_002Ef3 { get; }

    internal Fulfillment __field_r5_002Ef4 { get; }
}

public sealed class __CopeRecord_r7
{
    internal __CopeRecord_r7(int value0, int value1)
    {
        __field_r7_002Ef0 = value0;
        __field_r7_002Ef1 = value1;
    }

    internal int __field_r7_002Ef0 { get; }

    internal int __field_r7_002Ef1 { get; }
}

public sealed class __CopeRecord_r8
{
    internal __CopeRecord_r8(string value0, __CopeRecord_r7 value1)
    {
        __field_r8_002Ef0 = value0;
        __field_r8_002Ef1 = value1;
    }

    internal string __field_r8_002Ef0 { get; }

    internal __CopeRecord_r7 __field_r8_002Ef1 { get; }
}

public sealed class __CopeRecord_r9
{
    internal __CopeRecord_r9(int value0, int value1)
    {
        __field_r9_002Ef0 = value0;
        __field_r9_002Ef1 = value1;
    }

    internal int __field_r9_002Ef0 { get; }

    internal int __field_r9_002Ef1 { get; }
}

public sealed class __CopeRecord_r10
{
    internal __CopeRecord_r10(int value0, int value1)
    {
        __field_r10_002Ef0 = value0;
        __field_r10_002Ef1 = value1;
    }

    internal int __field_r10_002Ef0 { get; }

    internal int __field_r10_002Ef1 { get; }
}


public abstract record Fulfillment
{
    protected Fulfillment()
    {
    }

    public sealed record Pending : Fulfillment;

    public sealed record Packed(int attempts) : Fulfillment;

    public sealed record Shipped(string tracking, __CopeRecord_r1 position) : Fulfillment;

    public sealed record Rejected(string reason) : Fulfillment;

}

public static class CopelandModule
{
    private sealed class CopeUnwrapPanicException : global::System.Exception
    {
        public object? Error { get; }

        public CopeUnwrapPanicException(object? error)
            : base("COPE-PANIC-UNWRAP: Result unwrap encountered err")
        {
            Error = error;
        }
    }

    public static CopeResult<__CopeRecord_r6, string> Parcel__constructor(string code, double weight)
    {
        if ((weight < 0.0))
        {
            return CopeResult<__CopeRecord_r6, string>.Err("weight must be nonnegative");
        }
        var __cope_record_init_0 = code;
        var __cope_record_init_1 = Parcel__normalize(code);
        var __cope_record_init_2 = weight;
        return CopeResult<__CopeRecord_r6, string>.Ok(new __CopeRecord_r6(__cope_record_init_0, __cope_record_init_1, __cope_record_init_2));
    }

    public static string Parcel__normalize(string code)
    {
        return code;
    }

    public static __CopeRecord_r6 Parcel__adjust(__CopeRecord_r6 parcel, double delta)
    {
        var __cope_record_source_0 = parcel;
        var __cope_record_replacement_1 = ((parcel).__field_r6_002Ef2 + delta);
        return new __CopeRecord_r6(__cope_record_source_0.__field_r6_002Ef0, __cope_record_source_0.__field_r6_002Ef1, __cope_record_replacement_1);
    }

    public static double lineTotal(__CopeRecord_r3 line)
    {
        return (((double)(line).__field_r3_002Ef1) * (line).__field_r3_002Ef2);
    }

    public static double orderTotal(__CopeRecord_r5 order)
    {
        double total = 0.0;
        foreach (__CopeRecord_r3 line in (order).__field_r5_002Ef2)
        {
            total = (total + lineTotal(line));
        }
        return total;
    }

    public static CopeResult<int, string> validateQuantity(int quantity)
    {
        if ((quantity < 1))
        {
            return CopeResult<int, string>.Err("quantity must be positive");
        }
        return CopeResult<int, string>.Ok(quantity);
    }

    public static CopeResult<__CopeRecord_r3, string> reserve(__CopeRecord_r3 line)
    {
        var __cope_tmp0 = validateQuantity((line).__field_r3_002Ef1);
        if (!__cope_tmp0.IsOk)
        {
            return CopeResult<__CopeRecord_r3, string>.Err(__cope_tmp0.Error);
        }
        int quantity = __cope_tmp0.Value;
        var __cope_record_source_1 = line;
        var __cope_record_replacement_2 = quantity;
        return CopeResult<__CopeRecord_r3, string>.Ok(new __CopeRecord_r3(__cope_record_source_1.__field_r3_002Ef0, __cope_record_replacement_2, __cope_record_source_1.__field_r3_002Ef2));
    }

    public static string describe(Fulfillment status)
    {
        return status switch { Fulfillment.Pending _ => "pending", Fulfillment.Packed(var attempts) => "packed", Fulfillment.Shipped(var tracking, var position) => tracking, Fulfillment.Rejected(var reason) => reason, _ => throw new global::System.InvalidOperationException("Non-exhaustive match.") };
    }

    public static __CopeRecord_r8 identity__record_copeland_inferred_record_ordered_4_name_16_primitive_string_8_position_83_record_copeland_inferred_record_ordered_1_x_13_primitive_int_1_y_13_primitive_int______24A9BE5A43158CFC(__CopeRecord_r8 value)
    {
        return value;
    }

    public static int moveLocalItem()
    {
        var __cope_record_init_0 = "sample";
        var __cope_record_init_1 = 1;
        var __cope_record_init_2 = 2;
        var __cope_record_init_3 = new __CopeRecord_r7(__cope_record_init_1, __cope_record_init_2);
        __CopeRecord_r8 item = new __CopeRecord_r8(__cope_record_init_0, __cope_record_init_3);
        var __cope_record_init_4 = "peer";
        var __cope_record_init_5 = 3;
        var __cope_record_init_6 = 4;
        var __cope_record_init_7 = new __CopeRecord_r7(__cope_record_init_5, __cope_record_init_6);
        var __cope_argument_8 = new __CopeRecord_r8(__cope_record_init_4, __cope_record_init_7);
        __CopeRecord_r8 peer = identity__record_copeland_inferred_record_ordered_4_name_16_primitive_string_8_position_83_record_copeland_inferred_record_ordered_1_x_13_primitive_int_1_y_13_primitive_int______24A9BE5A43158CFC(__cope_argument_8);
        var __cope_record_source_9 = item;
        var __cope_record_source_10 = (item).__field_r8_002Ef1;
        var __cope_record_replacement_11 = ((peer).__field_r8_002Ef1).__field_r7_002Ef0;
        var __cope_record_replacement_12 = new __CopeRecord_r7(__cope_record_replacement_11, __cope_record_source_10.__field_r7_002Ef1);
        __CopeRecord_r8 moved = new __CopeRecord_r8(__cope_record_source_9.__field_r8_002Ef0, __cope_record_replacement_12);
        return (((moved).__field_r8_002Ef1).__field_r7_002Ef0 + ((moved).__field_r8_002Ef1).__field_r7_002Ef1);
    }

    public static int orderedShapePressure()
    {
        var __cope_record_init_0 = 1;
        var __cope_record_init_1 = 2;
        __CopeRecord_r7 a = new __CopeRecord_r7(__cope_record_init_0, __cope_record_init_1);
        var __cope_record_init_2 = 3;
        var __cope_record_init_3 = 4;
        __CopeRecord_r7 b = new __CopeRecord_r7(__cope_record_init_2, __cope_record_init_3);
        var __cope_record_init_4 = 4;
        var __cope_record_init_5 = 3;
        __CopeRecord_r9 c = new __CopeRecord_r9(__cope_record_init_4, __cope_record_init_5);
        return (((a).__field_r7_002Ef0 + (b).__field_r7_002Ef1) + (c).__field_r9_002Ef1);
    }

    public static CopeResult<__CopeRecord_r2, string> makeLocalResult(bool valid)
    {
        if (valid)
        {
            var __cope_record_init_0 = 20;
            var __cope_record_init_1 = 22;
            return CopeResult<__CopeRecord_r2, string>.Ok(new __CopeRecord_r2(__cope_record_init_0, __cope_record_init_1));
        }
        return CopeResult<__CopeRecord_r2, string>.Err("missing");
    }

    public static int readLocalResult()
    {
        var __cope_tmp0 = makeLocalResult(true);
        int __cope_tmp1;
        if (__cope_tmp0.IsOk)
        {
            var value = __cope_tmp0.Value;
            __cope_tmp1 = ((value).__field_r2_002Ef0 + (value).__field_r2_002Ef1);
        }
        else
        {
            var error = __cope_tmp0.Error;
            __cope_tmp1 = 0;
        }
        return __cope_tmp1;
    }

    public static int evaluationTrace(int[] buffer, int value)
    {
        CopeArray.Set(buffer, checked((int)0), ((CopeArray.Get(buffer, checked((int)0)) * 10) + value));
        return value;
    }

    public static int evaluationOrder()
    {
        int[] buffer = CopeArray.Create<int>(checked((int)1));
        var __cope_record_init_0 = evaluationTrace(buffer, 1);
        var __cope_record_init_1 = evaluationTrace(buffer, 2);
        __CopeRecord_r10 value = new __CopeRecord_r10(__cope_record_init_0, __cope_record_init_1);
        var __cope_record_source_2 = value;
        var __cope_record_replacement_3 = evaluationTrace(buffer, 3);
        var __cope_record_replacement_4 = evaluationTrace(buffer, 4);
        __CopeRecord_r10 moved = new __CopeRecord_r10(__cope_record_replacement_3, __cope_record_replacement_4);
        return ((CopeArray.Get(buffer, checked((int)0)) + (moved).__field_r10_002Ef0) + (moved).__field_r10_002Ef1);
    }

    public static double coordinateTotal__record_Position__D9FBFA8340216B5C(__CopeRecord_r1 value)
    {
        return ((value).__field_r1_002Ef0 + (value).__field_r1_002Ef1);
    }

    public static double Parcel__identity__primitive_number__FDC3F3A4758964FC(double value)
    {
        return value;
    }

    public static double publicWeight__record_Parcel__8EF3EF46C3C17BEA(__CopeRecord_r6 value)
    {
        return (value).__field_r6_002Ef2;
    }

    public static double main()
    {
        var __cope_record_init_0 = "Ada";
        var __cope_record_init_1 = "west";
        var __cope_record_init_2 = 5.0;
        var __cope_record_init_3 = 8.0;
        var __cope_record_init_4 = new __CopeRecord_r1(__cope_record_init_2, __cope_record_init_3);
        __CopeRecord_r4 customer = new __CopeRecord_r4(__cope_record_init_0, __cope_record_init_1, __cope_record_init_4);
        var __cope_record_init_5 = "A";
        var __cope_record_init_6 = 2;
        var __cope_record_init_7 = 10.5;
        __CopeRecord_r3 first = new __CopeRecord_r3(__cope_record_init_5, __cope_record_init_6, __cope_record_init_7);
        var __cope_record_init_8 = "B";
        var __cope_record_init_9 = 1;
        var __cope_record_init_10 = 4.0;
        __CopeRecord_r3 second = new __CopeRecord_r3(__cope_record_init_8, __cope_record_init_9, __cope_record_init_10);
        var __cope_tmp11 = Parcel__constructor("PKG-7", 10.0);
        if (!__cope_tmp11.IsOk)
        {
            throw new CopeUnwrapPanicException(__cope_tmp11.Error);
        }
        __CopeRecord_r6 parcel = __cope_tmp11.Value;
        __CopeRecord_r6 adjusted = Parcel__adjust(parcel, 2.0);
        var __cope_record_init_12 = 7;
        var __cope_record_init_13 = customer;
        var __cope_record_init_14 = new __CopeRecord_r3[] { first, second };
        var __cope_record_init_15 = adjusted;
        var __cope_record_init_16 = new Fulfillment.Packed(1);
        __CopeRecord_r5 order = new __CopeRecord_r5(__cope_record_init_12, __cope_record_init_13, __cope_record_init_14, __cope_record_init_15, __cope_record_init_16);
        var __cope_tmp17 = reserve(first);
        if (!__cope_tmp17.IsOk)
        {
            throw new CopeUnwrapPanicException(__cope_tmp17.Error);
        }
        __CopeRecord_r3 reserved = __cope_tmp17.Value;
        string status = describe((order).__field_r5_002Ef4);
        var __cope_record_init_18 = 5.0;
        var __cope_record_init_19 = 8.0;
        var __cope_argument_20 = new __CopeRecord_r1(__cope_record_init_18, __cope_record_init_19);
        double namedBoundary = coordinateTotal__record_Position__D9FBFA8340216B5C(__cope_argument_20);
        return ((((((((orderTotal(order) + ((double)(reserved).__field_r3_002Ef1)) + namedBoundary) + ((double)moveLocalItem())) + ((double)orderedShapePressure())) + ((double)readLocalResult())) + ((double)evaluationOrder())) + ((double)status.Length)) + Parcel__identity__primitive_number__FDC3F3A4758964FC(publicWeight__record_Parcel__8EF3EF46C3C17BEA(adjusted)));
    }

}
