namespace Copeland.TS.Syntax;

public enum SyntaxKind
{
    // Special
    BadToken,
    EndOfFileToken,

    // Trivia
    WhitespaceTrivia,
    LineBreakTrivia,
    SingleLineCommentTrivia,
    MultiLineCommentTrivia,

    // Literals / identifiers
    IdentifierToken,
    NumberToken,
    StringToken,

    // Punctuation
    OpenParenToken,
    CloseParenToken,
    OpenBraceToken,
    CloseBraceToken,
    OpenBracketToken,
    CloseBracketToken,
    CommaToken,
    DotToken,
    ColonToken,
    SemicolonToken,
    QuestionToken,

    // Operators
    PlusToken,
    MinusToken,
    StarToken,
    SlashToken,
    PercentToken,
    BangToken,
    EqualsToken,
    LessToken,
    LessOrEqualsToken,
    GreaterToken,
    GreaterOrEqualsToken,
    EqualsEqualsToken,
    BangEqualsToken,
    EqualsEqualsEqualsToken,
    BangEqualsEqualsToken,
    AmpersandAmpersandToken,
    PipePipeToken,
    ArrowToken,

    // Keywords
    ConstKeyword,
    LetKeyword,
    FunctionKeyword,
    EnumKeyword,
    RecordKeyword,
    TableKeyword,
    ColumnKeyword,
    MatchKeyword,
    ReturnKeyword,
    IfKeyword,
    ElseKeyword,
    WhileKeyword,
    ForKeyword,
    TrueKeyword,
    FalseKeyword,
    NullKeyword,
    NumberKeyword,
    StringKeyword,
    BooleanKeyword,
    VoidKeyword,
    VarKeyword,
    WithKeyword,
    TryKeyword,
    ExceptKeyword,
    BreakKeyword,
    ContinueKeyword,

    // Nodes
    CompilationUnit,
    GlobalStatementMember,
    FunctionDeclaration,
    EnumDeclaration,
    EnumCase,
    EnumPayloadField,
    RecordDeclaration,
    RecordField,
    TableDeclaration,
    TableAssetClause,
    TableColumn,
    Parameter,
    PredefinedType,
    IdentifierType,
    ArrayType,
    ParenthesizedType,
    ResultType,
    QualifiedRowType,
    ColumnType,
    BlockStatement,
    VariableDeclarationStatement,
    ExpressionStatement,
    IfStatement,
    WhileStatement,
    ForStatement,
    ReturnStatement,
    NestedRecordDeclarationStatement,
    NestedTableDeclarationStatement,
    NameExpression,
    LiteralExpression,
    ParenthesizedExpression,
    UnaryExpression,
    BinaryExpression,
    AssignmentExpression,
    CallExpression,
    MemberAccessExpression,
    IndexExpression,
    ArrayLiteralExpression,
    PropagateExpression,
    UnwrapExpression,
    ObjectLiteralExpression,
    ObjectProperty,
    WithExpression,
    MatchExpression,
    IfExpression,
    TryExceptExpression,
    TryValueBlock,
    MatchArm,
    MatchPattern,
    MissingExpression,
}
