using Machina.Layout.Compilation;
using Machina.Layout.Diagnostics;
using Machina.Layout.Frames;
using Machina.Layout.Geometry;
using Machina.Layout.Resolving;
using Machina.Layout.Rows;
using Xunit;

namespace Machina.Layout.Tests;

public sealed class GridArrangeTests
{
    [Fact] public void FixedGridSingleCell() { var r = Resolve(new[] { Row("root", new RootFrame(), arrange: Grid(new[] { new FixedGridTrack(100.0) }, new[] { new FixedGridTrack(50.0) })), Row("a", new CellFrame(0, 0), "root") }, new Rect(0, 0, 300, 200)); AssertRect(r.Nodes["a"].Rect, 0, 0, 100, 50); }
    [Fact] public void FixedGridPadding() { var r = Resolve(new[] { Row("root", new RootFrame(), arrange: new GridArrange(new[] { new FixedGridTrack(100.0) }, new[] { new FixedGridTrack(50.0) }, Padding: new EdgeInsets(6, 7, 8, 5))), Row("a", new CellFrame(0, 0), "root") }, new Rect(0, 0, 300, 200)); AssertRect(r.Nodes["a"].Rect, 5, 6, 100, 50); }
    [Fact] public void FixedGridGaps() { var r = Resolve(new[] { Row("root", new RootFrame(), arrange: new GridArrange(new GridTrack[] { new FixedGridTrack(100), new FixedGridTrack(50) }, new GridTrack[] { new FixedGridTrack(40), new FixedGridTrack(30) }, 10, 5)), Row("a", new CellFrame(0, 0), "root"), Row("b", new CellFrame(1, 0), "root"), Row("c", new CellFrame(0, 1), "root") }); AssertRect(r.Nodes["a"].Rect, 0, 0, 100, 40); AssertRect(r.Nodes["b"].Rect, 110, 0, 50, 40); AssertRect(r.Nodes["c"].Rect, 0, 45, 100, 30); }
    [Fact] public void FillColumns() { var r = Resolve(new[] { Row("root", new RootFrame(), arrange: Grid(new GridTrack[] { new FixedGridTrack(100), new FillGridTrack(1), new FillGridTrack(3) }, new[] { new FixedGridTrack(50) })), Row("a", new CellFrame(0, 0), "root"), Row("b", new CellFrame(1, 0), "root"), Row("c", new CellFrame(2, 0), "root") }, new Rect(0, 0, 400, 100)); AssertRect(r.Nodes["a"].Rect, 0, 0, 100, 50); AssertRect(r.Nodes["b"].Rect, 100, 0, 75, 50); AssertRect(r.Nodes["c"].Rect, 175, 0, 225, 50); }
    [Fact] public void FillRows() { var r = Resolve(new[] { Row("root", new RootFrame(), arrange: Grid(new[] { new FixedGridTrack(50) }, new GridTrack[] { new FixedGridTrack(100), new FillGridTrack(1), new FillGridTrack(3) })), Row("a", new CellFrame(0, 0), "root"), Row("b", new CellFrame(0, 1), "root"), Row("c", new CellFrame(0, 2), "root") }, new Rect(0, 0, 100, 400)); AssertRect(r.Nodes["a"].Rect, 0, 0, 50, 100); AssertRect(r.Nodes["b"].Rect, 0, 100, 50, 75); AssertRect(r.Nodes["c"].Rect, 0, 175, 50, 225); }
    [Fact] public void GapsReduceFill() { var r = Resolve(new[] { Row("root", new RootFrame(), arrange: new GridArrange(new GridTrack[] { new FixedGridTrack(100), new FillGridTrack(), new FillGridTrack() }, new[] { new FixedGridTrack(50) }, 10, 0)), Row("a", new CellFrame(0, 0), "root"), Row("b", new CellFrame(1, 0), "root"), Row("c", new CellFrame(2, 0), "root") }, new Rect(0, 0, 420, 100)); AssertRect(r.Nodes["a"].Rect, 0, 0, 100, 50); AssertRect(r.Nodes["b"].Rect, 110, 0, 150, 50); AssertRect(r.Nodes["c"].Rect, 270, 0, 150, 50); }
    [Fact] public void CellColumnSpan() { var r = Resolve(new[] { Row("root", new RootFrame(), arrange: new GridArrange(new GridTrack[] { new FixedGridTrack(100), new FixedGridTrack(50), new FixedGridTrack(25) }, new[] { new FixedGridTrack(10) }, 10, 0)), Row("a", new CellFrame(0, 0, 2, 1), "root") }); AssertRect(r.Nodes["a"].Rect, 0, 0, 160, 10); }
    [Fact] public void CellRowSpan() { var r = Resolve(new[] { Row("root", new RootFrame(), arrange: new GridArrange(new[] { new FixedGridTrack(10) }, new GridTrack[] { new FixedGridTrack(20), new FixedGridTrack(30), new FixedGridTrack(40) }, 0, 5)), Row("a", new CellFrame(0, 1, 1, 2), "root") }); AssertRect(r.Nodes["a"].Rect, 0, 25, 10, 75); }
    [Fact] public void CellSpansBothAxes() { var r = Resolve(new[] { Row("root", new RootFrame(), arrange: new GridArrange(new GridTrack[] { new FixedGridTrack(50), new FixedGridTrack(60), new FixedGridTrack(70) }, new GridTrack[] { new FixedGridTrack(10), new FixedGridTrack(20), new FixedGridTrack(30) }, 5, 2)), Row("a", new CellFrame(1, 1, 2, 2), "root") }); AssertRect(r.Nodes["a"].Rect, 55, 12, 135, 52); }
    [Fact] public void OrderPreservedPlacementByCell() { var r = Resolve(new[] { Row("root", new RootFrame(), arrange: new GridArrange(new GridTrack[] { new FixedGridTrack(10), new FixedGridTrack(20) }, new[] { new FixedGridTrack(10) })), Row("a", new CellFrame(1, 0), "root", order: 0), Row("b", new CellFrame(0, 0), "root", order: 1) }); Assert.Equal("a", r.Children["root"][0].Value); Assert.Equal("b", r.Children["root"][1].Value); AssertRect(r.Nodes["a"].Rect, 10, 0, 20, 10); AssertRect(r.Nodes["b"].Rect, 0, 0, 10, 10); }
    [Fact] public void CellDirectResolveRejected() { AssertLayoutError("CellFrameWithoutGrid", () => FrameResolver.ResolveFrame(new Rect(0, 0, 10, 10), new CellFrame(0, 0))); }
    [Fact] public void CellOutsideGridRejected() { AssertLayoutError("CellFrameWithoutGrid", () => Resolve(new[] { Row("root", new RootFrame()), Row("a", new CellFrame(0, 0), "root") })); }
    [Fact] public void AbsoluteInsideGridRejected() { AssertLayoutError("InvalidGridChildFrame", () => Resolve(new[] { Row("root", new RootFrame(), arrange: Grid(new[] { new FixedGridTrack(10) }, new[] { new FixedGridTrack(10) })), Row("a", new AbsoluteFrame(0, 0, 1, 1), "root") })); }
    [Fact] public void FixedInsideGridRejected() { AssertLayoutError("InvalidGridChildFrame", () => Resolve(new[] { Row("root", new RootFrame(), arrange: Grid(new[] { new FixedGridTrack(10) }, new[] { new FixedGridTrack(10) })), Row("a", new FixedFrame(1, 1), "root") })); }
    [Fact] public void EmptyColumnsRejected() { AssertLayoutError("InvalidGridColumns", () => Resolve(new[] { Row("root", new RootFrame(), arrange: new GridArrange(Array.Empty<GridTrack>(), new[] { new FixedGridTrack(10) })) })); }
    [Fact] public void EmptyRowsRejected() { AssertLayoutError("InvalidGridRows", () => Resolve(new[] { Row("root", new RootFrame(), arrange: new GridArrange(new[] { new FixedGridTrack(10) }, Array.Empty<GridTrack>())) })); }
    [Fact] public void InvalidGapRejected() { AssertLayoutError("InvalidGridGap", () => Resolve(new[] { Row("root", new RootFrame(), arrange: new GridArrange(new[] { new FixedGridTrack(10) }, new[] { new FixedGridTrack(10) }, -1, 0)) })); }
    [Fact] public void InvalidFixedTrackSizeRejected() { AssertLayoutError("InvalidGridTrackSize", () => Resolve(new[] { Row("root", new RootFrame(), arrange: Grid(new[] { new FixedGridTrack(-1) }, new[] { new FixedGridTrack(10) })) })); }
    [Fact] public void InvalidFillTrackWeightRejected() { AssertLayoutError("InvalidGridTrackWeight", () => Resolve(new[] { Row("root", new RootFrame(), arrange: Grid(new GridTrack[] { new FillGridTrack(0) }, new[] { new FixedGridTrack(10) })) })); }
    [Fact] public void NegativeContentRejected() { AssertLayoutError("NegativeGridContentSize", () => Resolve(new[] { Row("root", new RootFrame(), arrange: new GridArrange(new[] { new FixedGridTrack(1) }, new[] { new FixedGridTrack(1) }, Padding: new EdgeInsets(100, 0, 100, 0))) }, new Rect(0, 0, 100, 100))); }
    [Fact] public void NegativeRemainingRejected() { AssertLayoutError("NegativeGridRemainingSpace", () => Resolve(new[] { Row("root", new RootFrame(), arrange: new GridArrange(new GridTrack[] { new FixedGridTrack(200), new FixedGridTrack(200) }, new[] { new FixedGridTrack(10) }, 10, 0)) }, new Rect(0, 0, 300, 100))); }
    [Fact] public void InvalidCellFrameRejected() { AssertLayoutError("InvalidCellFrame", () => Resolve(new[] { Row("root", new RootFrame(), arrange: Grid(new[] { new FixedGridTrack(10) }, new[] { new FixedGridTrack(10) })), Row("a", new CellFrame(-1, 0), "root") })); }
    [Fact] public void CellOutOfRangeRejected() { AssertLayoutError("GridCellOutOfRange", () => Resolve(new[] { Row("root", new RootFrame(), arrange: Grid(new GridTrack[] { new FixedGridTrack(10), new FixedGridTrack(10) }, new[] { new FixedGridTrack(10) })), Row("a", new CellFrame(1, 0, 2, 1), "root") })); }

    private static GridArrange Grid(IReadOnlyList<GridTrack> c, IReadOnlyList<GridTrack> r) => new(c, r);
    private static Documents.ResolvedLayoutDocument Resolve(LayoutRow[] rows, Rect? root = null) => LayoutDocumentResolver.ResolveLayoutDocument(LayoutCompiler.CompileLayoutRows(rows), root ?? new Rect(0, 0, 300, 100));
    private static LayoutRow Row(string id, FrameSpec frame, string? parent = null, int order = 0, ArrangeSpec? arrange = null) => new(id, frame, parent is null ? (NodeId?)null : new NodeId(parent), order, 0, null, null, null, null, arrange);
    private static void AssertRect(Rect actual, double x, double y, double width, double height) { Assert.Equal(x, actual.X); Assert.Equal(y, actual.Y); Assert.Equal(width, actual.Width); Assert.Equal(height, actual.Height); }
    private static LayoutError AssertLayoutError(string expectedCode, Action action) { var e = Assert.Throws<LayoutError>(action); Assert.Equal(expectedCode, e.Code); return e; }
}
