// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public delegate double __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4(double value0);

public static class CopelandModule
{
    public static double increment(double value)
    {
        return (value + 1.0);
    }

    public static double apply(__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 operation, double value)
    {
        return operation(value);
    }

    public static __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 provide()
    {
        return (__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4)increment;
    }

    public static double identity__primitive_number__8F3BAE8FF0D9F338(double value)
    {
        return value;
    }

    public static double main()
    {
        __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 first = (__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4)increment;
        __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 second = (__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4)identity__primitive_number__8F3BAE8FF0D9F338;
        __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 supplied = provide();
        return (apply(first, 20.0) + second(supplied(20.0)));
    }

}
