// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public static class CopelandModule
{
    // Private test seam: never reachable from authored Copeland code.
    private static global::System.Action? __cope_batch_item_entered_for_testing = null;
    private static int __cope_batch_max_degree_for_testing = 0;

    public static int expensive(int value)
    {
        int result = value;
        {
            int i = 0;
            for (; (i < 1000); i = (i + 1))
            {
                result = ((result * 31) + i);
            }
        }
        return result;
    }

    public static int[] cheap(int[] input)
    {
        int[] __cope_batch_input_0 = input;
        int[] __cope_batch_output_0 = new int[__cope_batch_input_0.Length];
        var __cope_batch_failures_0 = new global::System.Collections.Concurrent.ConcurrentDictionary<int, global::System.Exception>();
        var __cope_batch_options_0 = new global::System.Threading.Tasks.ParallelOptions();
        if (__cope_batch_max_degree_for_testing > 0)
        {
            __cope_batch_options_0.MaxDegreeOfParallelism = __cope_batch_max_degree_for_testing;
        }
        global::System.Threading.Tasks.Parallel.For(0, __cope_batch_input_0.Length, __cope_batch_options_0, __cope_batch_index_0 =>
        {
            try
            {
                __cope_batch_item_entered_for_testing?.Invoke();
                int item = __cope_batch_input_0[__cope_batch_index_0];
                __cope_batch_output_0[__cope_batch_index_0] = (item * 2);
            }
            catch (global::System.Exception exception)
            {
                __cope_batch_failures_0.TryAdd(__cope_batch_index_0, exception);
            }
        });
        if (!__cope_batch_failures_0.IsEmpty)
        {
            var __cope_batch_failure_index = int.MaxValue;
            foreach (int __cope_batch_candidate in __cope_batch_failures_0.Keys)
            {
                if (__cope_batch_candidate < __cope_batch_failure_index) __cope_batch_failure_index = __cope_batch_candidate;
            }
            throw new global::System.InvalidOperationException($"COPE-BATCH-FAILURE index {__cope_batch_failure_index}", __cope_batch_failures_0[__cope_batch_failure_index]);
        }
        return __cope_batch_output_0;
    }

    public static int[] costly(int[] input)
    {
        int[] __cope_batch_input_0 = input;
        int[] __cope_batch_output_0 = new int[__cope_batch_input_0.Length];
        var __cope_batch_failures_0 = new global::System.Collections.Concurrent.ConcurrentDictionary<int, global::System.Exception>();
        var __cope_batch_options_0 = new global::System.Threading.Tasks.ParallelOptions();
        if (__cope_batch_max_degree_for_testing > 0)
        {
            __cope_batch_options_0.MaxDegreeOfParallelism = __cope_batch_max_degree_for_testing;
        }
        global::System.Threading.Tasks.Parallel.For(0, __cope_batch_input_0.Length, __cope_batch_options_0, __cope_batch_index_0 =>
        {
            try
            {
                __cope_batch_item_entered_for_testing?.Invoke();
                int item = __cope_batch_input_0[__cope_batch_index_0];
                __cope_batch_output_0[__cope_batch_index_0] = expensive(item);
            }
            catch (global::System.Exception exception)
            {
                __cope_batch_failures_0.TryAdd(__cope_batch_index_0, exception);
            }
        });
        if (!__cope_batch_failures_0.IsEmpty)
        {
            var __cope_batch_failure_index = int.MaxValue;
            foreach (int __cope_batch_candidate in __cope_batch_failures_0.Keys)
            {
                if (__cope_batch_candidate < __cope_batch_failure_index) __cope_batch_failure_index = __cope_batch_candidate;
            }
            throw new global::System.InvalidOperationException($"COPE-BATCH-FAILURE index {__cope_batch_failure_index}", __cope_batch_failures_0[__cope_batch_failure_index]);
        }
        return __cope_batch_output_0;
    }

}
