// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public readonly struct CopeResult<TValue, TError>
{
    private readonly TValue _value;
    private readonly TError _error;
    public bool IsOk { get; }

    public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException("Result has no value.");
    public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException("Result has no error.");

    private CopeResult(bool isOk, TValue value, TError error)
    {
        IsOk = isOk;
        _value = value;
        _error = error;
    }

    public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);
    public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);
}

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(string value0)
    {
        __field_r1_002Ef0 = value0;
    }

    internal string __field_r1_002Ef0 { get; }
}

public sealed class __CopeRecord_r2
{
    internal __CopeRecord_r2(bool value0, double value1, Mode value2)
    {
        __field_r2_002Ef0 = value0;
        __field_r2_002Ef1 = value1;
        __field_r2_002Ef2 = value2;
    }

    internal bool __field_r2_002Ef0 { get; }

    internal double __field_r2_002Ef1 { get; }

    internal Mode __field_r2_002Ef2 { get; }
}


public abstract record TsonEncodeError
{
    protected TsonEncodeError()
    {
    }

    public sealed record InvalidUnicode : TsonEncodeError;

    public sealed record OutputLimitExceeded : TsonEncodeError;

}
public abstract record Mode
{
    protected Mode()
    {
    }

    public sealed record Off : Mode;

    public sealed record Named(__CopeRecord_r1 detail) : Mode;

}

public static class CopelandModule
{
    private sealed class __TsonWriter
    {
        private readonly global::System.Text.StringBuilder _builder = new();
        private readonly int _maximumBytes;
        private readonly int _maximumStringCodeUnits;
        private int _bytes;
        internal TsonEncodeError? Error { get; private set; }

        internal __TsonWriter(int maximumBytes, int maximumStringCodeUnits)
        {
            _maximumBytes = maximumBytes;
            _maximumStringCodeUnits = maximumStringCodeUnits;
        }

        internal bool Static(string value) => AppendRaw(value, false);

        internal bool Indent(int level)
        {
            return Static(new string(' ', level * 4));
        }

        internal bool String(string value)
        {
            if (value.Length > _maximumStringCodeUnits)
            {
                return FailOutputLimit();
            }
            for (int index = 0; index < value.Length; index++)
            {
                char character = value[index];
                if (char.IsHighSurrogate(character))
                {
                    if (index + 1 >= value.Length || !char.IsLowSurrogate(value[index + 1])) return FailInvalidUnicode();
                    index++;
                }
                else if (char.IsLowSurrogate(character)) return FailInvalidUnicode();
            }
            if (!Static("\"")) return false;
            for (int index = 0; index < value.Length; index++)
            {
                char character = value[index];
                switch (character)
                {
                    case '"': if (!Static("\\\"")) return false; break;
                    case '\\': if (!Static("\\\\")) return false; break;
                    case '\b': if (!Static("\\b")) return false; break;
                    case '\f': if (!Static("\\f")) return false; break;
                    case '\n': if (!Static("\\n")) return false; break;
                    case '\r': if (!Static("\\r")) return false; break;
                    case '\t': if (!Static("\\t")) return false; break;
                    case '\u2028': if (!UnicodeEscape(character)) return false; break;
                    case '\u2029': if (!UnicodeEscape(character)) return false; break;
                    default:
                        if (character < ' ') { if (!UnicodeEscape(character)) return false; }
                        else if (char.IsHighSurrogate(character))
                        {
                            if (index + 1 >= value.Length || !char.IsLowSurrogate(value[index + 1])) return FailInvalidUnicode();
                            if (!AppendScalar(character, value[++index])) return false;
                        }
                        else if (char.IsLowSurrogate(character)) return FailInvalidUnicode();
                        else if (!AppendRaw(character.ToString(), false)) return false;
                        break;
                }
            }
            return Static("\"");
        }

        internal bool Number(double value)
        {
            ulong bits = global::System.BitConverter.DoubleToUInt64Bits(value);
            if ((bits & 0x7FF0000000000000UL) == 0x7FF0000000000000UL && (bits & 0x000FFFFFFFFFFFFFUL) != 0) bits = 0x7FF8000000000000UL;
            return Static("$number(\"" + bits.ToString("X16", global::System.Globalization.CultureInfo.InvariantCulture) + "\")");
        }

        internal string Finish() => _builder.ToString();

        private bool UnicodeEscape(char value)
        {
            return Static("\\u" + ((int)value).ToString("X4", global::System.Globalization.CultureInfo.InvariantCulture));
        }

        private bool AppendScalar(char high, char low)
        {
            if (_bytes > _maximumBytes - 4) return FailOutputLimit();
            _bytes += 4;
            _builder.Append(high);
            _builder.Append(low);
            return true;
        }

        private bool AppendRaw(string value, bool enforceStringLimit)
        {
            if (enforceStringLimit && value.Length > _maximumStringCodeUnits) return FailOutputLimit();
            int byteCount = 0;
            for (int index = 0; index < value.Length; index++)
            {
                char character = value[index];
                if (character <= 0x7F) byteCount += 1;
                else if (character <= 0x7FF) byteCount += 2;
                else if (char.IsHighSurrogate(character))
                {
                    if (index + 1 >= value.Length || !char.IsLowSurrogate(value[index + 1])) return FailInvalidUnicode();
                    byteCount += 4;
                    index++;
                }
                else if (char.IsLowSurrogate(character)) return FailInvalidUnicode();
                else byteCount += 3;
            }
            if (_bytes > _maximumBytes - byteCount) return FailOutputLimit();
            _bytes += byteCount;
            _builder.Append(value);
            return true;
        }

        private bool FailInvalidUnicode()
        {
            Error = new TsonEncodeError.InvalidUnicode();
            return false;
        }

        private bool FailOutputLimit()
        {
            Error = new TsonEncodeError.OutputLimitExceeded();
            return false;
        }
    }

    private static bool __tson_write_boolean(__TsonWriter writer, bool value, int indentation) => writer.Static(value ? "true" : "false");
    private static bool __tson_write_number(__TsonWriter writer, double value, int indentation) => writer.Number(value);
    private static bool __tson_write_string(__TsonWriter writer, string value, int indentation) => writer.String(value);

    private static CopeResult<string, TsonEncodeError> __tson_encode_tson0(__CopeRecord_r2 value)
    {
        var writer = new __TsonWriter(1048576, 262144);
        if (!writer.Static("const $schema: string = \"copeland://corpus/runtime-encoding\";\n\nrecord Detail {\n    label: string;\n}\n\nenum Mode {\n    Off,\n    Named(detail: Detail),\n}\n\nrecord Settings {\n    enabled: boolean;\n    count: number;\n    mode: Mode;\n}\n\nconst $value = ")
            || !__tson_write_tson0_005Frecord_005Fr2(writer, value, 0)
            || !writer.Static(";\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        return CopeResult<string, TsonEncodeError>.Ok(writer.Finish());
    }

    private static bool __tson_write_tson0_005Frecord_005Fr1(__TsonWriter writer, __CopeRecord_r1 value, int indentation)
    {
        if (!writer.Static("$record.Detail({\n") ) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"label\": ")) return false;
        if (!__tson_write_string(writer, value.__field_r1_002Ef0, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation)) return false;
        return writer.Static("})");
    }

    private static bool __tson_write_tson0_005Fenum_005FMode(__TsonWriter writer, Mode value, int indentation)
    {
        switch (value)
        {
            case Mode.Off:
                return writer.Static("Mode.Off");
            case Mode.Named item:
                if (!writer.Static("Mode.Named(\n")) return false;
                if (!writer.Indent(indentation + 1)) return false;
                if (!__tson_write_tson0_005Frecord_005Fr1(writer, item.detail, indentation + 1)) return false;
                if (!writer.Static("\n")) return false;
                if (!writer.Indent(indentation)) return false;
                return writer.Static(")");
            default:
                throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        }
    }

    private static bool __tson_write_tson0_005Frecord_005Fr2(__TsonWriter writer, __CopeRecord_r2 value, int indentation)
    {
        if (!writer.Static("$record.Settings({\n") ) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"enabled\": ")) return false;
        if (!__tson_write_boolean(writer, value.__field_r2_002Ef0, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"count\": ")) return false;
        if (!__tson_write_number(writer, value.__field_r2_002Ef1, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"mode\": ")) return false;
        if (!__tson_write_tson0_005Fenum_005FMode(writer, value.__field_r2_002Ef2, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation)) return false;
        return writer.Static("})");
    }

    public static CopeResult<string, TsonEncodeError> encode()
    {
        var __cope_record_init_0 = true;
        var __cope_record_init_1 = -0.0;
        var __cope_record_init_2 = "snow 雪 😀";
        var __cope_argument_3 = new __CopeRecord_r1(__cope_record_init_2);
        var __cope_record_init_4 = new Mode.Named(__cope_argument_3);
        __CopeRecord_r2 loaded = new __CopeRecord_r2(__cope_record_init_0, __cope_record_init_1, __cope_record_init_4);
        return __tson_encode_tson0(loaded);
    }

}
