using System.Text;
using Copeland.TS.Gpu.VdMir;

namespace Copeland.TS.Gpu.Wgsl;

/// <summary>Serializes the prepared subset; no binding allocation or semantic resolution.</summary>
internal sealed class WgslGraphicsEmitter
{
    private readonly StringBuilder _text = new();
    private readonly List<WgslSourceMapping> _mappings = [];
    private int _line = 1;

    public static (string Code, IReadOnlyList<WgslSourceMapping> Mappings) Emit(WgslPreparedModule module)
    {
        var emitter = new WgslGraphicsEmitter();
        emitter.Line($"// Generated by {WgslGraphicsBackend.CompatibilityVersion}. Do not edit.");
        foreach (var structure in module.Structures)
        {
            emitter.Line($"struct {structure.Name} {{");
            foreach (var field in structure.Fields)
            {
                var attributes = new List<string>();
                if (field.Location is not null) attributes.Add($"@location({field.Location})");
                if (field.Builtin is not null) attributes.Add($"@builtin({field.Builtin})");
                if (field.Interpolation is not null) attributes.Add($"@interpolate({field.Interpolation})");
                if (field.Alignment is not null) attributes.Add($"@align({field.Alignment})");
                if (field.Size is not null) attributes.Add($"@size({field.Size})");
                string prefix = attributes.Count == 0 ? "" : string.Join(" ", attributes) + " ";
                emitter.Line($"    {prefix}{field.Name}: {field.Type},");
            }
            emitter.Line("}");
            emitter.Line("");
        }
        foreach (var resource in module.Resources)
        {
            string addressSpace = resource.Uniform ? "<uniform>" : "";
            emitter.Line($"@group({resource.Group}) @binding({resource.Binding}) var{addressSpace} {resource.Name}: {resource.Type};");
        }
        foreach (var prepared in module.Functions)
        {
            emitter.Line("");
            var function = prepared.Function;
            emitter.Map(function.Source);
            if (prepared.Stage is not null)
            {
                emitter.Line(prepared.Stage == VdMirGraphicsStage.Vertex ? "@vertex" : "@fragment");
            }
            string parameters = string.Join(", ", function.Parameters.Select(parameter => $"{parameter.Name}: {parameter.Type}"));
            emitter.Line($"fn {function.Name}({parameters}) -> {function.ReturnType} {{");
            emitter.Statements(function.Statements, 1);
            emitter.Line("}");
        }
        return (emitter._text.ToString(), emitter._mappings);
    }

    private void Statements(IReadOnlyList<VdMirStatement> statements, int indentation)
    {
        string prefix = new(' ', indentation * 4);
        foreach (var statement in statements)
        {
            Map(statement.Source);
            switch (statement.Kind)
            {
                case "local":
                    string keyword = statement.Mutable ? "var" : "let";
                    Line($"{prefix}{keyword} {statement.Name}: {statement.Type} = {Expression(statement.Expression!)};");
                    break;
                case "assign":
                    Line($"{prefix}{statement.Name} = {Expression(statement.Expression!)};");
                    break;
                case "return":
                    Line($"{prefix}return {Expression(statement.Expression!)};");
                    break;
                case "break":
                case "discard":
                    Line($"{prefix}{statement.Kind};");
                    break;
                case "for":
                    var initializer = statement.Initializer!;
                    var increment = statement.Increment!;
                    string loopKeyword = initializer.Mutable ? "var" : "let";
                    Line($"{prefix}for ({loopKeyword} {initializer.Name}: {initializer.Type} = {Expression(initializer.Expression!)}; {Expression(statement.Expression!)}; {increment.Name} = {Expression(increment.Expression!)}) {{");
                    Statements(statement.Body ?? [], indentation + 1);
                    Line($"{prefix}}}");
                    break;
                case "if":
                    Line($"{prefix}if ({Expression(statement.Expression!)}) {{");
                    Statements(statement.Body ?? [], indentation + 1);
                    if (statement.ElseBody?.Count > 0)
                    {
                        Line($"{prefix}}} else {{");
                        Statements(statement.ElseBody, indentation + 1);
                    }
                    Line($"{prefix}}}");
                    break;
                case "block":
                    Line($"{prefix}{{");
                    Statements(statement.Body ?? [], indentation + 1);
                    Line($"{prefix}}}");
                    break;
                default:
                    throw new InvalidOperationException("Preparation admitted an unsupported statement.");
            }
        }
    }

    private static string Expression(VdMirExpression expression)
    {
        return expression.Kind switch
        {
            "name" or "literal" => expression.Value!,
            "field" => $"{Expression(expression.Operands![0])}.{expression.Value}",
            "call" => $"{expression.Value}({string.Join(", ", expression.Operands!.Select(Expression))})",
            "binary" => $"({Expression(expression.Operands![0])} {expression.Value} {Expression(expression.Operands[1])})",
            "unary" => $"({expression.Value}{Expression(expression.Operands![0])})",
            _ => throw new InvalidOperationException("Preparation admitted an unsupported expression."),
        };
    }

    private void Map(VdMirSourceSpan source) => _mappings.Add(new WgslSourceMapping(_line, source));
    private void Line(string text)
    {
        _text.Append(text).Append('\n');
        _line++;
    }
}
