// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public readonly struct CopeResult<TValue, TError>
{
    private readonly TValue _value;
    private readonly TError _error;
    public bool IsOk { get; }

    public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException("Result has no value.");
    public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException("Result has no error.");

    private CopeResult(bool isOk, TValue value, TError error)
    {
        IsOk = isOk;
        _value = value;
        _error = error;
    }

    public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);
    public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);
}

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(double value0, double value1)
    {
        __field_r1_002Ef0 = value0;
        __field_r1_002Ef1 = value1;
    }

    internal double __field_r1_002Ef0 { get; }

    internal double __field_r1_002Ef1 { get; }
}


public abstract record TableBoundsError
{
    protected TableBoundsError()
    {
    }

    public sealed record InvalidIndex(double index) : TableBoundsError;

    public sealed record OutOfBounds(double index, double rowCount) : TableBoundsError;

}
public abstract record ReadingState
{
    protected ReadingState()
    {
    }

    public sealed record Missing : ReadingState;

    public sealed record Present(double value) : ReadingState;

    public sealed record Flagged(string reason) : ReadingState;

}

public abstract class CopeColumn<T>
{
    internal abstract int Count { get; }
    internal abstract CopeResult<T, TableBoundsError> Get(double index);
}

public sealed class __CopeTableColumn_t1_002Ec0 : CopeColumn<string>
{
    private readonly string[] _values;
    internal override int Count => _values.Length;

    internal __CopeTableColumn_t1_002Ec0(string[] values)
    {
        _values = values;
    }

    internal override CopeResult<string, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<string, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 4)
        {
            return CopeResult<string, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 4.0));
        }
        return CopeResult<string, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t1_002Ec1 : CopeColumn<int>
{
    private readonly int[] _values;
    internal override int Count => _values.Length;

    internal __CopeTableColumn_t1_002Ec1(int[] values)
    {
        _values = values;
    }

    internal override CopeResult<int, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<int, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 4)
        {
            return CopeResult<int, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 4.0));
        }
        return CopeResult<int, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t1_002Ec2 : CopeColumn<__CopeRecord_r1>
{
    private readonly __CopeRecord_r1[] _values;
    internal override int Count => _values.Length;

    internal __CopeTableColumn_t1_002Ec2(__CopeRecord_r1[] values)
    {
        _values = values;
    }

    internal override CopeResult<__CopeRecord_r1, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<__CopeRecord_r1, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 4)
        {
            return CopeResult<__CopeRecord_r1, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 4.0));
        }
        return CopeResult<__CopeRecord_r1, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t1_002Ec3 : CopeColumn<ReadingState>
{
    private readonly ReadingState[] _values;
    internal override int Count => _values.Length;

    internal __CopeTableColumn_t1_002Ec3(ReadingState[] values)
    {
        _values = values;
    }

    internal override CopeResult<ReadingState, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<ReadingState, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 4)
        {
            return CopeResult<ReadingState, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 4.0));
        }
        return CopeResult<ReadingState, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t1_002Ec4 : CopeColumn<CopeResult<double, string>>
{
    private readonly CopeResult<double, string>[] _values;
    internal override int Count => _values.Length;

    internal __CopeTableColumn_t1_002Ec4(CopeResult<double, string>[] values)
    {
        _values = values;
    }

    internal override CopeResult<CopeResult<double, string>, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<CopeResult<double, string>, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 4)
        {
            return CopeResult<CopeResult<double, string>, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 4.0));
        }
        return CopeResult<CopeResult<double, string>, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableRow_t1_002Erow
{
    private readonly __CopeTable_t1 _table;
    private readonly int _index;

    internal __CopeTableRow_t1_002Erow(__CopeTable_t1 table, int index)
    {
        _table = table;
        _index = index;
    }

    internal string __row_field_t1_002Ec0 => _table.__read_t1_002Ec0(_index);

    internal int __row_field_t1_002Ec1 => _table.__read_t1_002Ec1(_index);

    internal __CopeRecord_r1 __row_field_t1_002Ec2 => _table.__read_t1_002Ec2(_index);

    internal ReadingState __row_field_t1_002Ec3 => _table.__read_t1_002Ec3(_index);

    internal CopeResult<double, string> __row_field_t1_002Ec4 => _table.__read_t1_002Ec4(_index);
}

public sealed class __CopeTable_t1
{
    internal int Count => 4;

    private readonly string[] _column_t1_002Ec0;
    private readonly int[] _column_t1_002Ec1;
    private readonly __CopeRecord_r1[] _column_t1_002Ec2;
    private readonly ReadingState[] _column_t1_002Ec3;
    private readonly CopeResult<double, string>[] _column_t1_002Ec4;

    private __CopeTable_t1(string[] values0, int[] values1, __CopeRecord_r1[] values2, ReadingState[] values3, CopeResult<double, string>[] values4)
    {
        _column_t1_002Ec0 = values0;
        __column_t1_002Ec0 = new __CopeTableColumn_t1_002Ec0(values0);
        _column_t1_002Ec1 = values1;
        __column_t1_002Ec1 = new __CopeTableColumn_t1_002Ec1(values1);
        _column_t1_002Ec2 = values2;
        __column_t1_002Ec2 = new __CopeTableColumn_t1_002Ec2(values2);
        _column_t1_002Ec3 = values3;
        __column_t1_002Ec3 = new __CopeTableColumn_t1_002Ec3(values3);
        _column_t1_002Ec4 = values4;
        __column_t1_002Ec4 = new __CopeTableColumn_t1_002Ec4(values4);
    }

    internal static __CopeTable_t1 Create()
    {
        return new __CopeTable_t1(
            new string[] { "north", "south", "east", "west" },
            new int[] { 1, 2, 3, 4 },
            new __CopeRecord_r1[] { new __CopeRecord_r1(1.0, 2.0), new __CopeRecord_r1(3.0, 4.0), new __CopeRecord_r1(5.0, 6.0), new __CopeRecord_r1(7.0, 8.0) },
            new ReadingState[] { new ReadingState.Present(10.0), new ReadingState.Present(20.0), new ReadingState.Missing(), new ReadingState.Flagged("sensor") },
            new CopeResult<double, string>[] { CopeResult<double, string>.Ok(10.0), CopeResult<double, string>.Ok(20.0), CopeResult<double, string>.Err("missing"), CopeResult<double, string>.Err("flagged") }
        );
    }

    internal __CopeTableColumn_t1_002Ec0 __column_t1_002Ec0 { get; }

    internal string __read_t1_002Ec0(int index) => _column_t1_002Ec0[index];

    internal __CopeTableColumn_t1_002Ec1 __column_t1_002Ec1 { get; }

    internal int __read_t1_002Ec1(int index) => _column_t1_002Ec1[index];

    internal __CopeTableColumn_t1_002Ec2 __column_t1_002Ec2 { get; }

    internal __CopeRecord_r1 __read_t1_002Ec2(int index) => _column_t1_002Ec2[index];

    internal __CopeTableColumn_t1_002Ec3 __column_t1_002Ec3 { get; }

    internal ReadingState __read_t1_002Ec3(int index) => _column_t1_002Ec3[index];

    internal __CopeTableColumn_t1_002Ec4 __column_t1_002Ec4 { get; }

    internal CopeResult<double, string> __read_t1_002Ec4(int index) => _column_t1_002Ec4[index];

    internal CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError> GetRow(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 4)
        {
            return CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 4.0));
        }
        return CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError>.Ok(new __CopeTableRow_t1_002Erow(this, (int)index));
    }
}

public static class CopelandModule
{
    private static readonly __CopeTable_t1 __cope_table_t1 = __CopeTable_t1.Create();

    private sealed class CopeUnwrapPanicException : global::System.Exception
    {
        public object? Error { get; }

        public CopeUnwrapPanicException(object? error)
            : base("COPE-PANIC-UNWRAP: Result unwrap encountered err")
        {
            Error = error;
        }
    }

    public static double stateValue(ReadingState value)
    {
        return value switch { ReadingState.Missing _ => 0.0, ReadingState.Present(var reading) => reading, ReadingState.Flagged(var reason) => ((double)reason.Length), _ => throw new global::System.InvalidOperationException("Non-exhaustive match.") };
    }

    public static double acceptedValue(CopeResult<double, string> value)
    {
        var __cope_tmp0 = value;
        double __cope_tmp1;
        if (__cope_tmp0.IsOk)
        {
            var reading = __cope_tmp0.Value;
            __cope_tmp1 = reading;
        }
        else
        {
            var error = __cope_tmp0.Error;
            __cope_tmp1 = ((double)0);
        }
        return __cope_tmp1;
    }

    public static CopeResult<double, TableBoundsError> rowScore(int index)
    {
        var __cope_tmp0 = __cope_table_t1.GetRow(index);
        if (!__cope_tmp0.IsOk)
        {
            return CopeResult<double, TableBoundsError>.Err(__cope_tmp0.Error);
        }
        __CopeTableRow_t1_002Erow row = __cope_tmp0.Value;
        double pointScore = ((row.__row_field_t1_002Ec2).__field_r1_002Ef0 + (row.__row_field_t1_002Ec2).__field_r1_002Ef1);
        return CopeResult<double, TableBoundsError>.Ok((((((double)row.__row_field_t1_002Ec1) + pointScore) + stateValue(row.__row_field_t1_002Ec3)) + acceptedValue(row.__row_field_t1_002Ec4)));
    }

    public static double columnScore()
    {
        int index = 0;
        double total = 0.0;
        while ((index < 4))
        {
            var __cope_tmp0 = __cope_table_t1.__column_t1_002Ec1.Get(index);
            if (!__cope_tmp0.IsOk)
            {
                throw new CopeUnwrapPanicException(__cope_tmp0.Error);
            }
            var __cope_operand_1 = (total + ((double)__cope_tmp0.Value));
            var __cope_tmp2 = __cope_table_t1.__column_t1_002Ec2.Get(index);
            if (!__cope_tmp2.IsOk)
            {
                throw new CopeUnwrapPanicException(__cope_tmp2.Error);
            }
            var __cope_operand_3 = (__cope_tmp2.Value).__field_r1_002Ef0;
            total = (__cope_operand_1 + __cope_operand_3);
            index = (index + 1);
        }
        return total;
    }

    public static double boundsScore(int index)
    {
        var __cope_tmp0 = __cope_table_t1.__column_t1_002Ec1.Get(index);
        double __cope_tmp1;
        if (__cope_tmp0.IsOk)
        {
            var value = __cope_tmp0.Value;
            __cope_tmp1 = ((double)value);
        }
        else
        {
            var error = __cope_tmp0.Error;
            __cope_tmp1 = error switch { TableBoundsError.InvalidIndex(var value) => ((double)100), TableBoundsError.OutOfBounds(var value, var rowCount) => rowCount, _ => throw new global::System.InvalidOperationException("Non-exhaustive match.") };
        }
        return __cope_tmp1;
    }

    public static double repeatedAccess()
    {
        var __cope_tmp0 = __cope_table_t1.GetRow(0);
        if (!__cope_tmp0.IsOk)
        {
            throw new CopeUnwrapPanicException(__cope_tmp0.Error);
        }
        __CopeTableRow_t1_002Erow first = __cope_tmp0.Value;
        var __cope_tmp1 = __cope_table_t1.GetRow(1);
        if (!__cope_tmp1.IsOk)
        {
            throw new CopeUnwrapPanicException(__cope_tmp1.Error);
        }
        __CopeTableRow_t1_002Erow second = __cope_tmp1.Value;
        var __cope_tmp2 = __cope_table_t1.GetRow(2);
        if (!__cope_tmp2.IsOk)
        {
            throw new CopeUnwrapPanicException(__cope_tmp2.Error);
        }
        __CopeTableRow_t1_002Erow third = __cope_tmp2.Value;
        var __cope_tmp3 = __cope_table_t1.GetRow(3);
        if (!__cope_tmp3.IsOk)
        {
            throw new CopeUnwrapPanicException(__cope_tmp3.Error);
        }
        __CopeTableRow_t1_002Erow fourth = __cope_tmp3.Value;
        return ((((((((first.__row_field_t1_002Ec2).__field_r1_002Ef0 + (second.__row_field_t1_002Ec2).__field_r1_002Ef0) + (third.__row_field_t1_002Ec2).__field_r1_002Ef0) + (fourth.__row_field_t1_002Ec2).__field_r1_002Ef0) + stateValue(first.__row_field_t1_002Ec3)) + stateValue(second.__row_field_t1_002Ec3)) + stateValue(third.__row_field_t1_002Ec3)) + stateValue(fourth.__row_field_t1_002Ec3));
    }

    public static double main()
    {
        var __cope_tmp0 = rowScore(0);
        if (!__cope_tmp0.IsOk)
        {
            throw new CopeUnwrapPanicException(__cope_tmp0.Error);
        }
        var __cope_operand_1 = __cope_tmp0.Value;
        var __cope_tmp2 = rowScore(1);
        if (!__cope_tmp2.IsOk)
        {
            throw new CopeUnwrapPanicException(__cope_tmp2.Error);
        }
        var __cope_operand_3 = __cope_tmp2.Value;
        var __cope_operand_4 = (__cope_operand_1 + __cope_operand_3);
        var __cope_tmp5 = rowScore(2);
        if (!__cope_tmp5.IsOk)
        {
            throw new CopeUnwrapPanicException(__cope_tmp5.Error);
        }
        var __cope_operand_6 = __cope_tmp5.Value;
        var __cope_operand_7 = (__cope_operand_4 + __cope_operand_6);
        var __cope_tmp8 = rowScore(3);
        if (!__cope_tmp8.IsOk)
        {
            throw new CopeUnwrapPanicException(__cope_tmp8.Error);
        }
        var __cope_operand_9 = __cope_tmp8.Value;
        var __cope_operand_10 = (__cope_operand_7 + __cope_operand_9);
        var __cope_operand_11 = columnScore();
        var __cope_operand_12 = (__cope_operand_10 + __cope_operand_11);
        var __cope_operand_13 = boundsScore(99);
        var __cope_operand_14 = (__cope_operand_12 + __cope_operand_13);
        var __cope_operand_15 = repeatedAccess();
        return (__cope_operand_14 + __cope_operand_15);
    }

}
