// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(string value0)
    {
        __field_r1_002Ef0 = value0;
    }

    internal string __field_r1_002Ef0 { get; }
}

public sealed class __CopeRecord_r2
{
    internal __CopeRecord_r2(double[] value0, double[] value1, __CopeRecord_r1[] value2, State[] value3, double[][] value4)
    {
        __field_r2_002Ef0 = value0;
        __field_r2_002Ef1 = value1;
        __field_r2_002Ef2 = value2;
        __field_r2_002Ef3 = value3;
        __field_r2_002Ef4 = value4;
    }

    internal double[] __field_r2_002Ef0 { get; }

    internal double[] __field_r2_002Ef1 { get; }

    internal __CopeRecord_r1[] __field_r2_002Ef2 { get; }

    internal State[] __field_r2_002Ef3 { get; }

    internal double[][] __field_r2_002Ef4 { get; }
}


public abstract record State
{
    protected State()
    {
    }

    public sealed record Off : State;

    public sealed record On(double value) : State;

}

public static class CopelandModule
{
    public static __CopeRecord_r2 load()
    {
        var __cope_record_init_0 = new double[] {  };
        var __cope_record_init_1 = new double[] { 0.0, -0.0, 3.0 };
        var __cope_record_init_2 = "first";
        var __cope_argument_3 = new __CopeRecord_r1(__cope_record_init_2);
        var __cope_record_init_4 = "second";
        var __cope_argument_5 = new __CopeRecord_r1(__cope_record_init_4);
        var __cope_record_init_6 = new __CopeRecord_r1[] { __cope_argument_3, __cope_argument_5 };
        var __cope_record_init_7 = new State[] { new State.Off(), new State.On(3.0) };
        var __cope_record_init_8 = new double[][] { new double[] {  }, new double[] { 1.0, 2.0 } };
        __CopeRecord_r2 batch = new __CopeRecord_r2(__cope_record_init_0, __cope_record_init_1, __cope_record_init_6, __cope_record_init_7, __cope_record_init_8);
        return batch;
    }

}
