// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public readonly struct CopeResult<TValue, TError>
{
    private readonly TValue _value;
    private readonly TError _error;
    public bool IsOk { get; }

    public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException("Result has no value.");
    public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException("Result has no error.");

    private CopeResult(bool isOk, TValue value, TError error)
    {
        IsOk = isOk;
        _value = value;
        _error = error;
    }

    public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);
    public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);
}

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(string value0)
    {
        __field_r1_002Ef0 = value0;
    }

    internal string __field_r1_002Ef0 { get; }
}


public abstract record TsonEncodeError
{
    protected TsonEncodeError()
    {
    }

    public sealed record InvalidUnicode : TsonEncodeError;

    public sealed record OutputLimitExceeded : TsonEncodeError;

}
public abstract record TableBoundsError
{
    protected TableBoundsError()
    {
    }

    public sealed record InvalidIndex(double index) : TableBoundsError;

    public sealed record OutOfBounds(double index, double rowCount) : TableBoundsError;

}
public abstract record State
{
    protected State()
    {
    }

    public sealed record Off : State;

    public sealed record Named(string label) : State;

}

public abstract class CopeColumn<T>
{
    internal abstract CopeResult<T, TableBoundsError> Get(double index);
}

public sealed class __CopeTableColumn_t1_002Ec0 : CopeColumn<bool>
{
    private readonly bool[] _values;

    internal __CopeTableColumn_t1_002Ec0(bool[] values)
    {
        _values = values;
    }

    internal override CopeResult<bool, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<bool, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 0)
        {
            return CopeResult<bool, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 0.0));
        }
        return CopeResult<bool, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t1_002Ec1 : CopeColumn<string>
{
    private readonly string[] _values;

    internal __CopeTableColumn_t1_002Ec1(string[] values)
    {
        _values = values;
    }

    internal override CopeResult<string, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<string, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 0)
        {
            return CopeResult<string, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 0.0));
        }
        return CopeResult<string, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableRow_t1_002Erow
{
    private readonly __CopeTable_t1 _table;
    private readonly int _index;

    internal __CopeTableRow_t1_002Erow(__CopeTable_t1 table, int index)
    {
        _table = table;
        _index = index;
    }

    internal bool __row_field_t1_002Ec0 => _table.__read_t1_002Ec0(_index);

    internal string __row_field_t1_002Ec1 => _table.__read_t1_002Ec1(_index);
}

public sealed class __CopeTable_t1
{
    private readonly bool[] _column_t1_002Ec0;
    private readonly string[] _column_t1_002Ec1;

    private __CopeTable_t1(bool[] values0, string[] values1)
    {
        _column_t1_002Ec0 = values0;
        __column_t1_002Ec0 = new __CopeTableColumn_t1_002Ec0(values0);
        _column_t1_002Ec1 = values1;
        __column_t1_002Ec1 = new __CopeTableColumn_t1_002Ec1(values1);
    }

    internal static __CopeTable_t1 Create()
    {
        return new __CopeTable_t1(
            new bool[] {  },
            new string[] {  }
        );
    }

    internal __CopeTableColumn_t1_002Ec0 __column_t1_002Ec0 { get; }

    internal bool __read_t1_002Ec0(int index) => _column_t1_002Ec0[index];
    internal bool[] __tson_values_t1_002Ec0() => _column_t1_002Ec0;

    internal __CopeTableColumn_t1_002Ec1 __column_t1_002Ec1 { get; }

    internal string __read_t1_002Ec1(int index) => _column_t1_002Ec1[index];
    internal string[] __tson_values_t1_002Ec1() => _column_t1_002Ec1;

    internal CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError> GetRow(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 0)
        {
            return CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 0.0));
        }
        return CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError>.Ok(new __CopeTableRow_t1_002Erow(this, (int)index));
    }
}

public sealed class __CopeTableColumn_t2_002Ec0 : CopeColumn<bool>
{
    private readonly bool[] _values;

    internal __CopeTableColumn_t2_002Ec0(bool[] values)
    {
        _values = values;
    }

    internal override CopeResult<bool, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<bool, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 5)
        {
            return CopeResult<bool, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 5.0));
        }
        return CopeResult<bool, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t2_002Ec1 : CopeColumn<double>
{
    private readonly double[] _values;

    internal __CopeTableColumn_t2_002Ec1(double[] values)
    {
        _values = values;
    }

    internal override CopeResult<double, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<double, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 5)
        {
            return CopeResult<double, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 5.0));
        }
        return CopeResult<double, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t2_002Ec2 : CopeColumn<__CopeRecord_r1>
{
    private readonly __CopeRecord_r1[] _values;

    internal __CopeTableColumn_t2_002Ec2(__CopeRecord_r1[] values)
    {
        _values = values;
    }

    internal override CopeResult<__CopeRecord_r1, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<__CopeRecord_r1, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 5)
        {
            return CopeResult<__CopeRecord_r1, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 5.0));
        }
        return CopeResult<__CopeRecord_r1, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t2_002Ec3 : CopeColumn<State>
{
    private readonly State[] _values;

    internal __CopeTableColumn_t2_002Ec3(State[] values)
    {
        _values = values;
    }

    internal override CopeResult<State, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<State, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 5)
        {
            return CopeResult<State, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 5.0));
        }
        return CopeResult<State, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t2_002Ec4 : CopeColumn<double[][]>
{
    private readonly double[][][] _values;

    internal __CopeTableColumn_t2_002Ec4(double[][][] values)
    {
        _values = values;
    }

    internal override CopeResult<double[][], TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<double[][], TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 5)
        {
            return CopeResult<double[][], TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 5.0));
        }
        return CopeResult<double[][], TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableRow_t2_002Erow
{
    private readonly __CopeTable_t2 _table;
    private readonly int _index;

    internal __CopeTableRow_t2_002Erow(__CopeTable_t2 table, int index)
    {
        _table = table;
        _index = index;
    }

    internal bool __row_field_t2_002Ec0 => _table.__read_t2_002Ec0(_index);

    internal double __row_field_t2_002Ec1 => _table.__read_t2_002Ec1(_index);

    internal __CopeRecord_r1 __row_field_t2_002Ec2 => _table.__read_t2_002Ec2(_index);

    internal State __row_field_t2_002Ec3 => _table.__read_t2_002Ec3(_index);

    internal double[][] __row_field_t2_002Ec4 => _table.__read_t2_002Ec4(_index);
}

public sealed class __CopeTable_t2
{
    private readonly bool[] _column_t2_002Ec0;
    private readonly double[] _column_t2_002Ec1;
    private readonly __CopeRecord_r1[] _column_t2_002Ec2;
    private readonly State[] _column_t2_002Ec3;
    private readonly double[][][] _column_t2_002Ec4;

    private __CopeTable_t2(bool[] values0, double[] values1, __CopeRecord_r1[] values2, State[] values3, double[][][] values4)
    {
        _column_t2_002Ec0 = values0;
        __column_t2_002Ec0 = new __CopeTableColumn_t2_002Ec0(values0);
        _column_t2_002Ec1 = values1;
        __column_t2_002Ec1 = new __CopeTableColumn_t2_002Ec1(values1);
        _column_t2_002Ec2 = values2;
        __column_t2_002Ec2 = new __CopeTableColumn_t2_002Ec2(values2);
        _column_t2_002Ec3 = values3;
        __column_t2_002Ec3 = new __CopeTableColumn_t2_002Ec3(values3);
        _column_t2_002Ec4 = values4;
        __column_t2_002Ec4 = new __CopeTableColumn_t2_002Ec4(values4);
    }

    internal static __CopeTable_t2 Create()
    {
        return new __CopeTable_t2(
            new bool[] { true, false, true, false, true },
            new double[] { 0.0, -0.0, 1.5, global::System.BitConverter.UInt64BitsToDouble(0x7FF8000000000000UL), global::System.Double.NegativeInfinity },
            new __CopeRecord_r1[] { new __CopeRecord_r1("plain"), new __CopeRecord_r1("quote \" slash \\ newline\n"), new __CopeRecord_r1("雪"), new __CopeRecord_r1("😀"), new __CopeRecord_r1("𐐷") },
            new State[] { new State.Off(), new State.Named("payload"), new State.Named("雪"), new State.Off(), new State.Named("array") },
            new double[][][] { new double[][] {  }, new double[][] { new double[] { 1.0, 2.0 }, new double[] {  } }, new double[][] { new double[] {  }, new double[] { 0.0 } }, new double[][] { new double[] { global::System.Double.PositiveInfinity } }, new double[][] { new double[] { global::System.BitConverter.UInt64BitsToDouble(0x7FF8000000000000UL) } } }
        );
    }

    internal __CopeTableColumn_t2_002Ec0 __column_t2_002Ec0 { get; }

    internal bool __read_t2_002Ec0(int index) => _column_t2_002Ec0[index];
    internal bool[] __tson_values_t2_002Ec0() => _column_t2_002Ec0;

    internal __CopeTableColumn_t2_002Ec1 __column_t2_002Ec1 { get; }

    internal double __read_t2_002Ec1(int index) => _column_t2_002Ec1[index];
    internal double[] __tson_values_t2_002Ec1() => _column_t2_002Ec1;

    internal __CopeTableColumn_t2_002Ec2 __column_t2_002Ec2 { get; }

    internal __CopeRecord_r1 __read_t2_002Ec2(int index) => _column_t2_002Ec2[index];
    internal __CopeRecord_r1[] __tson_values_t2_002Ec2() => _column_t2_002Ec2;

    internal __CopeTableColumn_t2_002Ec3 __column_t2_002Ec3 { get; }

    internal State __read_t2_002Ec3(int index) => _column_t2_002Ec3[index];
    internal State[] __tson_values_t2_002Ec3() => _column_t2_002Ec3;

    internal __CopeTableColumn_t2_002Ec4 __column_t2_002Ec4 { get; }

    internal double[][] __read_t2_002Ec4(int index) => _column_t2_002Ec4[index];
    internal double[][][] __tson_values_t2_002Ec4() => _column_t2_002Ec4;

    internal CopeResult<__CopeTableRow_t2_002Erow, TableBoundsError> GetRow(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<__CopeTableRow_t2_002Erow, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 5)
        {
            return CopeResult<__CopeTableRow_t2_002Erow, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 5.0));
        }
        return CopeResult<__CopeTableRow_t2_002Erow, TableBoundsError>.Ok(new __CopeTableRow_t2_002Erow(this, (int)index));
    }
}

public static class CopelandModule
{
    private static readonly __CopeTable_t1 __cope_table_t1 = __CopeTable_t1.Create();
    private static readonly __CopeTable_t2 __cope_table_t2 = __CopeTable_t2.Create();

    private sealed class __TsonWriter
    {
        private readonly global::System.Text.StringBuilder _builder = new();
        private readonly int _maximumBytes;
        private readonly int _maximumStringCodeUnits;
        private int _bytes;
        internal TsonEncodeError? Error { get; private set; }

        internal __TsonWriter(int maximumBytes, int maximumStringCodeUnits)
        {
            _maximumBytes = maximumBytes;
            _maximumStringCodeUnits = maximumStringCodeUnits;
        }

        internal bool Static(string value) => AppendRaw(value, false);

        internal bool Indent(int level)
        {
            return Static(new string(' ', level * 4));
        }

        internal bool String(string value)
        {
            if (value.Length > _maximumStringCodeUnits)
            {
                return FailOutputLimit();
            }
            for (int index = 0; index < value.Length; index++)
            {
                char character = value[index];
                if (char.IsHighSurrogate(character))
                {
                    if (index + 1 >= value.Length || !char.IsLowSurrogate(value[index + 1])) return FailInvalidUnicode();
                    index++;
                }
                else if (char.IsLowSurrogate(character)) return FailInvalidUnicode();
            }
            if (!Static("\"")) return false;
            for (int index = 0; index < value.Length; index++)
            {
                char character = value[index];
                switch (character)
                {
                    case '"': if (!Static("\\\"")) return false; break;
                    case '\\': if (!Static("\\\\")) return false; break;
                    case '\b': if (!Static("\\b")) return false; break;
                    case '\f': if (!Static("\\f")) return false; break;
                    case '\n': if (!Static("\\n")) return false; break;
                    case '\r': if (!Static("\\r")) return false; break;
                    case '\t': if (!Static("\\t")) return false; break;
                    case '\u2028': if (!UnicodeEscape(character)) return false; break;
                    case '\u2029': if (!UnicodeEscape(character)) return false; break;
                    default:
                        if (character < ' ') { if (!UnicodeEscape(character)) return false; }
                        else if (char.IsHighSurrogate(character))
                        {
                            if (index + 1 >= value.Length || !char.IsLowSurrogate(value[index + 1])) return FailInvalidUnicode();
                            if (!AppendScalar(character, value[++index])) return false;
                        }
                        else if (char.IsLowSurrogate(character)) return FailInvalidUnicode();
                        else if (!AppendRaw(character.ToString(), false)) return false;
                        break;
                }
            }
            return Static("\"");
        }

        internal bool Number(double value)
        {
            ulong bits = global::System.BitConverter.DoubleToUInt64Bits(value);
            if ((bits & 0x7FF0000000000000UL) == 0x7FF0000000000000UL && (bits & 0x000FFFFFFFFFFFFFUL) != 0) bits = 0x7FF8000000000000UL;
            return Static("$number(\"" + bits.ToString("X16", global::System.Globalization.CultureInfo.InvariantCulture) + "\")");
        }

        internal string Finish() => _builder.ToString();

        private bool UnicodeEscape(char value)
        {
            return Static("\\u" + ((int)value).ToString("X4", global::System.Globalization.CultureInfo.InvariantCulture));
        }

        private bool AppendScalar(char high, char low)
        {
            if (_bytes > _maximumBytes - 4) return FailOutputLimit();
            _bytes += 4;
            _builder.Append(high);
            _builder.Append(low);
            return true;
        }

        private bool AppendRaw(string value, bool enforceStringLimit)
        {
            if (enforceStringLimit && value.Length > _maximumStringCodeUnits) return FailOutputLimit();
            int byteCount = 0;
            for (int index = 0; index < value.Length; index++)
            {
                char character = value[index];
                if (character <= 0x7F) byteCount += 1;
                else if (character <= 0x7FF) byteCount += 2;
                else if (char.IsHighSurrogate(character))
                {
                    if (index + 1 >= value.Length || !char.IsLowSurrogate(value[index + 1])) return FailInvalidUnicode();
                    byteCount += 4;
                    index++;
                }
                else if (char.IsLowSurrogate(character)) return FailInvalidUnicode();
                else byteCount += 3;
            }
            if (_bytes > _maximumBytes - byteCount) return FailOutputLimit();
            _bytes += byteCount;
            _builder.Append(value);
            return true;
        }

        private bool FailInvalidUnicode()
        {
            Error = new TsonEncodeError.InvalidUnicode();
            return false;
        }

        private bool FailOutputLimit()
        {
            Error = new TsonEncodeError.OutputLimitExceeded();
            return false;
        }

        internal bool OutputLimit() => FailOutputLimit();
    }

    private static bool __tson_write_boolean(__TsonWriter writer, bool value, int indentation) => writer.Static(value ? "true" : "false");
    private static bool __tson_write_number(__TsonWriter writer, double value, int indentation) => writer.Number(value);
    private static bool __tson_write_string(__TsonWriter writer, string value, int indentation) => writer.String(value);

    private static CopeResult<string, TsonEncodeError> __tson_encode_tson0(__CopeTable_t2 value)
    {
        if (!object.ReferenceEquals(value, __cope_table_t2)) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var column0 = value.__tson_values_t2_002Ec0();
        var length0 = column0 is null ? -1 : column0.Length;
        if (length0 != 5) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var column1 = value.__tson_values_t2_002Ec1();
        var length1 = column1 is null ? -1 : column1.Length;
        if (length1 != 5) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var column2 = value.__tson_values_t2_002Ec2();
        var length2 = column2 is null ? -1 : column2.Length;
        if (length2 != 5) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var column3 = value.__tson_values_t2_002Ec3();
        var length3 = column3 is null ? -1 : column3.Length;
        if (length3 != 5) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var column4 = value.__tson_values_t2_002Ec4();
        var length4 = column4 is null ? -1 : column4.Length;
        if (length4 != 5) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var writer = new __TsonWriter(1048576, 262144);
        if (!writer.Static("const $schema: string = \"copeland://corpus/runtime-table-encoding\";\n\nrecord Point {\n    name: string;\n}\n\nrecord table Samples {\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        if (length0 == 0)
        {
            if (!writer.Static("    active: boolean = ") || !writer.Static("[];\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
            goto __tson_table_column_done_0;
        }
        if (!writer.Static("    active: boolean = ") || !writer.Static("[\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        for (var index = 0; index < length0; index++)
        {
            var cell = column0[index];
            if (!writer.Indent(2)
                || !__tson_write_boolean(writer, cell, 2)
                || !writer.Static(",\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
        }
        if (!writer.Indent(1) || !writer.Static("];\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        __tson_table_column_done_0: ;
        if (length1 == 0)
        {
            if (!writer.Static("    score: number = ") || !writer.Static("[];\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
            goto __tson_table_column_done_1;
        }
        if (!writer.Static("    score: number = ") || !writer.Static("[\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        for (var index = 0; index < length1; index++)
        {
            var cell = column1[index];
            if (!writer.Indent(2)
                || !__tson_write_number(writer, cell, 2)
                || !writer.Static(",\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
        }
        if (!writer.Indent(1) || !writer.Static("];\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        __tson_table_column_done_1: ;
        if (length2 == 0)
        {
            if (!writer.Static("    point: Point = ") || !writer.Static("[];\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
            goto __tson_table_column_done_2;
        }
        if (!writer.Static("    point: Point = ") || !writer.Static("[\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        for (var index = 0; index < length2; index++)
        {
            var cell = column2[index];
            if (!writer.Indent(2)
                || !__tson_write_tson0_005Frecord_005Fr1(writer, cell, 2)
                || !writer.Static(",\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
        }
        if (!writer.Indent(1) || !writer.Static("];\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        __tson_table_column_done_2: ;
        if (length3 == 0)
        {
            if (!writer.Static("    state: State = ") || !writer.Static("[];\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
            goto __tson_table_column_done_3;
        }
        if (!writer.Static("    state: State = ") || !writer.Static("[\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        for (var index = 0; index < length3; index++)
        {
            var cell = column3[index];
            if (!writer.Indent(2)
                || !__tson_write_tson0_005Fenum_005FState(writer, cell, 2)
                || !writer.Static(",\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
        }
        if (!writer.Indent(1) || !writer.Static("];\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        __tson_table_column_done_3: ;
        if (length4 == 0)
        {
            if (!writer.Static("    values: number[][] = ") || !writer.Static("[];\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
            goto __tson_table_column_done_4;
        }
        if (!writer.Static("    values: number[][] = ") || !writer.Static("[\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        for (var index = 0; index < length4; index++)
        {
            var cell = column4[index];
            if (!writer.Indent(2)
                || !__tson_write_tson0_005Farray_005F0(writer, cell, 2)
                || !writer.Static(",\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
        }
        if (!writer.Indent(1) || !writer.Static("];\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        __tson_table_column_done_4: ;
        if (!writer.Static("}\n\nenum State {\n    Off,\n    Named(label: string),\n}\n\nconst $value = Samples;\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        return CopeResult<string, TsonEncodeError>.Ok(writer.Finish());
    }

    private static bool __tson_write_tson0_005Frecord_005Fr1(__TsonWriter writer, __CopeRecord_r1 value, int indentation)
    {
        if (!writer.Static("$record.Point({\n") ) return false;
        if (!writer.Indent(indentation + 1)) return false;
        if (!writer.Static("\"name\": ")) return false;
        if (!__tson_write_string(writer, value.__field_r1_002Ef0, indentation + 1)) return false;
        if (!writer.Static(",\n")) return false;
        if (!writer.Indent(indentation)) return false;
        return writer.Static("})");
    }

    private static bool __tson_write_tson0_005Fenum_005FState(__TsonWriter writer, State value, int indentation)
    {
        switch (value)
        {
            case State.Off:
                return writer.Static("State.Off");
            case State.Named item:
                if (!writer.Static("State.Named(\n")) return false;
                if (!writer.Indent(indentation + 1)) return false;
                if (!__tson_write_string(writer, item.label, indentation + 1)) return false;
                if (!writer.Static("\n")) return false;
                if (!writer.Indent(indentation)) return false;
                return writer.Static(")");
            default:
                throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        }
    }

    private static bool __tson_write_tson0_005Farray_005F0(__TsonWriter writer, double[][] value, int indentation)
    {
        if (value is null) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var array = value;
        var length = array.Length;
        if (length > 100000) return writer.OutputLimit();
        if (length == 0) return writer.Static("[]");
        if (!writer.Static("[\n")) return false;
        for (var index = 0; index < length; index++)
        {
            var element = array[index];
            if (!writer.Indent(indentation + 1)) return false;
            if (!__tson_write_tson0_005Farray_005F1(writer, element, indentation + 1)) return false;
            if (!writer.Static(",\n")) return false;
        }
        if (!writer.Indent(indentation)) return false;
        return writer.Static("]");
    }

    private static bool __tson_write_tson0_005Farray_005F1(__TsonWriter writer, double[] value, int indentation)
    {
        if (value is null) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var array = value;
        var length = array.Length;
        if (length > 100000) return writer.OutputLimit();
        if (length == 0) return writer.Static("[]");
        if (!writer.Static("[\n")) return false;
        for (var index = 0; index < length; index++)
        {
            var element = array[index];
            if (!writer.Indent(indentation + 1)) return false;
            if (!__tson_write_number(writer, element, indentation + 1)) return false;
            if (!writer.Static(",\n")) return false;
        }
        if (!writer.Indent(indentation)) return false;
        return writer.Static("]");
    }

    private static CopeResult<string, TsonEncodeError> __tson_encode_tson1(__CopeTable_t1 value)
    {
        if (!object.ReferenceEquals(value, __cope_table_t1)) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var column0 = value.__tson_values_t1_002Ec0();
        var length0 = column0 is null ? -1 : column0.Length;
        if (length0 != 0) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var column1 = value.__tson_values_t1_002Ec1();
        var length1 = column1 is null ? -1 : column1.Length;
        if (length1 != 0) throw new global::System.InvalidOperationException("Copeland C# backend invariant failure.");
        var writer = new __TsonWriter(1048576, 262144);
        if (!writer.Static("const $schema: string = \"copeland://corpus/runtime-table-encoding\";\n\nrecord table Empty {\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        if (length0 == 0)
        {
            if (!writer.Static("    active: boolean = ") || !writer.Static("[];\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
            goto __tson_table_column_done_0;
        }
        if (!writer.Static("    active: boolean = ") || !writer.Static("[\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        for (var index = 0; index < length0; index++)
        {
            var cell = column0[index];
            if (!writer.Indent(2)
                || !__tson_write_boolean(writer, cell, 2)
                || !writer.Static(",\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
        }
        if (!writer.Indent(1) || !writer.Static("];\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        __tson_table_column_done_0: ;
        if (length1 == 0)
        {
            if (!writer.Static("    note: string = ") || !writer.Static("[];\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
            goto __tson_table_column_done_1;
        }
        if (!writer.Static("    note: string = ") || !writer.Static("[\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        for (var index = 0; index < length1; index++)
        {
            var cell = column1[index];
            if (!writer.Indent(2)
                || !__tson_write_string(writer, cell, 2)
                || !writer.Static(",\n"))
            {
                return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
            }
        }
        if (!writer.Indent(1) || !writer.Static("];\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        __tson_table_column_done_1: ;
        if (!writer.Static("}\n\nconst $value = Empty;\n"))
        {
            return CopeResult<string, TsonEncodeError>.Err(writer.Error ?? new TsonEncodeError.OutputLimitExceeded());
        }
        return CopeResult<string, TsonEncodeError>.Ok(writer.Finish());
    }

    public static CopeResult<string, TsonEncodeError> encode()
    {
        return __tson_encode_tson0(__cope_table_t2);
    }

    public static CopeResult<string, TsonEncodeError> encodeEmpty()
    {
        return __tson_encode_tson1(__cope_table_t1);
    }

}
