using System.Text;

namespace Copeland.TS.Database;

public static class DatabaseCSharpGenerator
{
    public static string Generate(DatabaseSchema schema)
    {
        DatabaseField valueField = schema.StoredFields.FirstOrDefault(field =>
                field.Type is DatabaseScalarType.Float64 or DatabaseScalarType.Int32)
            ?? throw new DatabaseBuildException("M0 generated query requires one numeric non-partition field.");
        string databaseType = PublicName(schema.DatabaseName) + "Database";
        string recordType = PublicName(schema.RecordName);
        string routeArguments = string.Join(
            ", ",
            schema.PartitionFields.Select(fieldName =>
            {
                DatabaseField field = Field(schema, fieldName);
                return $"{ClrType(field.Type)} {LocalName(field.Name)}";
            }));
        string routeValues = string.Join(
            ", ",
            schema.PartitionFields.Select(fieldName => LocalName(fieldName)));
        string routeFields = string.Join(
            ", ",
            schema.PartitionFields.Select(fieldName =>
            {
                DatabaseField field = Field(schema, fieldName);
                return $"{ClrType(field.Type)} {PublicName(field.Name)}";
            }));
        string rootReads = string.Join(
            Environment.NewLine,
            schema.PartitionFields.Select(fieldName =>
            {
                DatabaseField field = Field(schema, fieldName);
                return $"                    {ClrType(field.Type)} {LocalName(field.Name)} = {RootReadExpression(field.Type)};";
            }));
        string recordParameters = string.Join(
            ", ",
            schema.Fields.Select(field => $"{ClrType(field.Type)} {PublicName(field.Name)}"));

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("using System.Collections.Generic;");
        source.AppendLine("using System.IO;");
        source.AppendLine("using System.Linq;");
        source.AppendLine("using System.Security.Cryptography;");
        source.AppendLine("using System.Text;");
        source.AppendLine();
        source.AppendLine("namespace Copeland.Generated;");
        source.AppendLine();
        source.AppendLine($"public sealed record {recordType}({recordParameters});");
        source.AppendLine();
        source.AppendLine("public sealed record DatabaseQueryTrace(");
        source.AppendLine("    IReadOnlyList<string> OpenedLeaves,");
        source.AppendLine("    IReadOnlyList<string> ReadColumns,");
        source.AppendLine("    long BytesRead);");
        source.AppendLine();
        source.AppendLine($"public sealed class {databaseType} : IDisposable");
        source.AppendLine("{");
        source.AppendLine("    private const int FormatVersion = 1;");
        source.AppendLine("    private const int MaximumLeaves = 1_000_000;");
        source.AppendLine("    private const int MaximumRowsPerLeaf = 100_000_000;");
        source.AppendLine("    private const long MaximumRootBytes = 512L * 1024 * 1024;");
        source.AppendLine("    private const long MaximumLeafBytes = 1024L * 1024 * 1024;");
        source.AppendLine($"    public const string SchemaIdentity = \"{schema.SchemaIdentity}\";");
        source.AppendLine($"    public const string IndexIdentity = \"{schema.IndexIdentity}\";");
        source.AppendLine("    private static readonly byte[] RootMagic = \"CTSROOT1\"u8.ToArray();");
        source.AppendLine("    private static readonly byte[] LeafMagic = \"CTSLEAF1\"u8.ToArray();");
        source.AppendLine("    private readonly string _databasePath;");
        source.AppendLine("    private readonly Dictionary<RouteKey, LeafLocation> _leaves;");
        source.AppendLine("    private bool _disposed;");
        source.AppendLine();
        source.AppendLine($"    private {databaseType}(string databasePath, Dictionary<RouteKey, LeafLocation> leaves)");
        source.AppendLine("    {");
        source.AppendLine("        _databasePath = databasePath;");
        source.AppendLine("        _leaves = leaves;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public DatabaseQueryTrace LastQueryTrace { get; private set; } = new([], [], 0);");
        source.AppendLine();
        source.AppendLine($"    public static {databaseType} Open(string path)");
        source.AppendLine("    {");
        source.AppendLine("        ArgumentException.ThrowIfNullOrWhiteSpace(path);");
        source.AppendLine("        string databasePath = Path.GetFullPath(path);");
        source.AppendLine("        string rootPath = Path.Combine(databasePath, \"root.index\");");
        source.AppendLine("        try");
        source.AppendLine("        {");
        source.AppendLine("            using var stream = new FileStream(rootPath, FileMode.Open, FileAccess.Read, FileShare.Read);");
        source.AppendLine("            Require(stream.Length <= MaximumRootBytes, \"Database root exceeds the M0 size limit.\");");
        source.AppendLine("            using var reader = new BinaryReader(stream, Encoding.UTF8, leaveOpen: true);");
        source.AppendLine("            RequireBytes(reader, RootMagic, \"root magic\");");
        source.AppendLine("            Require(reader.ReadInt32() == FormatVersion, \"Unsupported database root format version.\");");
        source.AppendLine("            RequireIdentity(reader, SchemaIdentity, \"schema\");");
        source.AppendLine("            RequireIdentity(reader, IndexIdentity, \"index\");");
        source.AppendLine($"            Require(reader.ReadInt32() == {schema.PartitionFields.Count}, \"Database partition depth does not match the generated API.\");");
        foreach (string fieldName in schema.PartitionFields)
        {
            DatabaseField field = Field(schema, fieldName);
            source.AppendLine($"            Require(reader.ReadString() == \"{Escape(field.Name)}\", \"Database partition field does not match the generated API.\");");
            source.AppendLine($"            Require(reader.ReadByte() == {(byte)field.Type}, \"Database partition key type does not match the generated API.\");");
        }

        source.AppendLine("            int leafCount = reader.ReadInt32();");
        source.AppendLine("            Require(leafCount >= 0 && leafCount <= MaximumLeaves, \"Invalid database leaf count.\");");
        source.AppendLine("            var leaves = new Dictionary<RouteKey, LeafLocation>();");
        source.AppendLine("            for (int leafIndex = 0; leafIndex < leafCount; leafIndex++)");
        source.AppendLine("            {");
        source.AppendLine(rootReads);
        source.AppendLine("                byte[] leafIdentity = ReadExactly(reader, 32, \"leaf identity\");");
        source.AppendLine("                string relativePath = reader.ReadString();");
        source.AppendLine("                Require(IsSafeLeafPath(relativePath), \"Database root contains an unsafe leaf path.\");");
        source.AppendLine($"                var key = new RouteKey({routeValues});");
        source.AppendLine("                Require(leaves.TryAdd(key, new LeafLocation(relativePath, leafIdentity)), \"Database root contains a duplicate route.\");");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            Require(stream.Position == stream.Length, \"Database root contains trailing data.\");");
        source.AppendLine($"            return new {databaseType}(databasePath, leaves);");
        source.AppendLine("        }");
        source.AppendLine("        catch (EndOfStreamException exception)");
        source.AppendLine("        {");
        source.AppendLine("            throw new InvalidDataException(\"Database root is truncated.\", exception);");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine($"    public double Sum{PublicName(valueField.Name)}({routeArguments})");
        source.AppendLine("    {");
        source.AppendLine("        ObjectDisposedException.ThrowIf(_disposed, this);");
        source.AppendLine($"        var route = new RouteKey({routeValues});");
        source.AppendLine("        if (!_leaves.TryGetValue(route, out LeafLocation? location))");
        source.AppendLine("        {");
        source.AppendLine("            throw new KeyNotFoundException(\"No leaf exists for the requested partition route.\");");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        string leafPath = ResolveLeafPath(location.RelativePath);");
        source.AppendLine("        var openedLeaves = new List<string> { location.RelativePath };");
        source.AppendLine($"        ColumnReadResult result = ReadNumericColumn(leafPath, location.Identity, \"{Escape(valueField.Name)}\", {(byte)valueField.Type});");
        source.AppendLine($"        LastQueryTrace = new DatabaseQueryTrace(openedLeaves, new[] {{ \"{Escape(valueField.Name)}\" }}, result.BytesRead);");
        source.AppendLine("        return result.Sum;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public void Dispose()");
        source.AppendLine("    {");
        source.AppendLine("        _disposed = true;");
        source.AppendLine("    }");
        source.AppendLine();
        AppendReadNumericColumn(source);
        AppendHelpers(source);
        source.AppendLine();
        source.AppendLine($"    private readonly record struct RouteKey({routeFields});");
        source.AppendLine("    private sealed record LeafLocation(string RelativePath, byte[] Identity);");
        source.AppendLine("    private sealed record ColumnDescriptor(byte Type, long Offset, long Length, byte[] Hash);");
        source.AppendLine("    private sealed record ColumnReadResult(double Sum, long BytesRead);");
        source.AppendLine("}");
        return source.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static void AppendReadNumericColumn(StringBuilder source)
    {
        source.AppendLine("    private static ColumnReadResult ReadNumericColumn(string path, byte[] expectedLeafIdentity, string columnName, byte expectedType)");
        source.AppendLine("    {");
        source.AppendLine("        try");
        source.AppendLine("        {");
        source.AppendLine("            using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);");
        source.AppendLine("            Require(stream.Length <= MaximumLeafBytes, \"Leaf segment exceeds the M0 size limit.\");");
        source.AppendLine("            using var reader = new BinaryReader(stream, Encoding.UTF8, leaveOpen: true);");
        source.AppendLine("            RequireBytes(reader, LeafMagic, \"leaf magic\");");
        source.AppendLine("            Require(reader.ReadInt32() == FormatVersion, \"Unsupported leaf format version.\");");
        source.AppendLine("            RequireIdentity(reader, SchemaIdentity, \"schema\");");
        source.AppendLine("            RequireIdentity(reader, IndexIdentity, \"index\");");
        source.AppendLine("            RequireBytes(reader, expectedLeafIdentity, \"leaf identity\");");
        source.AppendLine("            int rowCount = reader.ReadInt32();");
        source.AppendLine("            Require(rowCount >= 0 && rowCount <= MaximumRowsPerLeaf, \"Invalid leaf row count.\");");
        source.AppendLine("            int columnCount = reader.ReadInt32();");
        source.AppendLine("            Require(columnCount >= 0 && columnCount <= 256, \"Invalid leaf column count.\");");
        source.AppendLine("            var columns = new Dictionary<string, ColumnDescriptor>(StringComparer.Ordinal);");
        source.AppendLine("            for (int columnIndex = 0; columnIndex < columnCount; columnIndex++)");
        source.AppendLine("            {");
        source.AppendLine("                string name = reader.ReadString();");
        source.AppendLine("                byte type = reader.ReadByte();");
        source.AppendLine("                long offset = reader.ReadInt64();");
        source.AppendLine("                long length = reader.ReadInt64();");
        source.AppendLine("                byte[] hash = ReadExactly(reader, 32, \"column hash\");");
        source.AppendLine("                Require(offset >= 0 && length >= 0 && offset <= stream.Length && length <= stream.Length - offset, \"Leaf column region is outside the file.\");");
        source.AppendLine("                Require(columns.TryAdd(name, new ColumnDescriptor(type, offset, length, hash)), \"Leaf contains a duplicate column.\");");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            long headerBytes = stream.Position;");
        source.AppendLine("            long previousEnd = headerBytes;");
        source.AppendLine("            foreach (ColumnDescriptor descriptor in columns.Values.OrderBy(column => column.Offset))");
        source.AppendLine("            {");
        source.AppendLine("                Require(descriptor.Offset == previousEnd, \"Leaf columns overlap or contain an undeclared gap.\");");
        source.AppendLine("                previousEnd = checked(descriptor.Offset + descriptor.Length);");
        source.AppendLine("            }");
        source.AppendLine("            Require(previousEnd == stream.Length, \"Leaf contains undeclared trailing data.\");");
        source.AppendLine();
        source.AppendLine("            ColumnDescriptor target = columns.TryGetValue(columnName, out ColumnDescriptor? found)");
        source.AppendLine("                ? found");
        source.AppendLine("                : throw new InvalidDataException($\"Leaf is missing required column '{columnName}'.\");");
        source.AppendLine("            Require(target.Type == expectedType, \"Leaf column type does not match the generated query.\");");
        source.AppendLine("            int elementWidth = expectedType == 1 ? 4 : 8;");
        source.AppendLine("            Require(target.Length == checked((long)rowCount * elementWidth), \"Leaf numeric column length does not match its row count.\");");
        source.AppendLine("            Require(target.Length <= int.MaxValue, \"Leaf column is too large for M0.\");");
        source.AppendLine("            stream.Position = target.Offset;");
        source.AppendLine("            byte[] payload = ReadExactly(reader, (int)target.Length, \"column payload\");");
        source.AppendLine("            Require(CryptographicOperations.FixedTimeEquals(SHA256.HashData(payload), target.Hash), \"Leaf column checksum mismatch.\");");
        source.AppendLine("            double sum = 0;");
        source.AppendLine("            using var payloadStream = new MemoryStream(payload, writable: false);");
        source.AppendLine("            using var payloadReader = new BinaryReader(payloadStream);");
        source.AppendLine("            for (int rowIndex = 0; rowIndex < rowCount; rowIndex++)");
        source.AppendLine("            {");
        source.AppendLine("                sum += expectedType == 1 ? payloadReader.ReadInt32() : payloadReader.ReadDouble();");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            return new ColumnReadResult(sum, checked(headerBytes + target.Length));");
        source.AppendLine("        }");
        source.AppendLine("        catch (EndOfStreamException exception)");
        source.AppendLine("        {");
        source.AppendLine("            throw new InvalidDataException(\"Leaf segment is truncated.\", exception);");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void AppendHelpers(StringBuilder source)
    {
        source.AppendLine("    private string ResolveLeafPath(string relativePath)");
        source.AppendLine("    {");
        source.AppendLine("        string fullPath = Path.GetFullPath(Path.Combine(_databasePath, relativePath));");
        source.AppendLine("        string expectedPrefix = _databasePath.TrimEnd(Path.DirectorySeparatorChar) + Path.DirectorySeparatorChar;");
        source.AppendLine("        Require(fullPath.StartsWith(expectedPrefix, StringComparison.OrdinalIgnoreCase), \"Leaf path escapes the database directory.\");");
        source.AppendLine("        return fullPath;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static bool IsSafeLeafPath(string path)");
        source.AppendLine("        => !string.IsNullOrWhiteSpace(path)");
        source.AppendLine("            && !Path.IsPathRooted(path)");
        source.AppendLine("            && path.Replace('\\\\', '/').StartsWith(\"leaves/\", StringComparison.Ordinal)");
        source.AppendLine("            && !path.Split('/', '\\\\').Contains(\"..\", StringComparer.Ordinal);");
        source.AppendLine();
        source.AppendLine("    private static void RequireIdentity(BinaryReader reader, string expectedHex, string kind)");
        source.AppendLine("    {");
        source.AppendLine("        byte[] expected = Convert.FromHexString(expectedHex);");
        source.AppendLine("        byte[] actual = ReadExactly(reader, expected.Length, kind + \" identity\");");
        source.AppendLine("        Require(CryptographicOperations.FixedTimeEquals(actual, expected), $\"Database {kind} identity mismatch.\");");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static void RequireBytes(BinaryReader reader, byte[] expected, string description)");
        source.AppendLine("    {");
        source.AppendLine("        byte[] actual = ReadExactly(reader, expected.Length, description);");
        source.AppendLine("        Require(actual.AsSpan().SequenceEqual(expected), $\"Invalid {description}.\");");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static byte[] ReadExactly(BinaryReader reader, int length, string description)");
        source.AppendLine("    {");
        source.AppendLine("        byte[] bytes = reader.ReadBytes(length);");
        source.AppendLine("        if (bytes.Length != length)");
        source.AppendLine("        {");
        source.AppendLine("            throw new InvalidDataException($\"Truncated {description}.\");");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        return bytes;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static void Require(bool condition, string message)");
        source.AppendLine("    {");
        source.AppendLine("        if (!condition)");
        source.AppendLine("        {");
        source.AppendLine("            throw new InvalidDataException(message);");
        source.AppendLine("        }");
        source.AppendLine("    }");
    }

    private static DatabaseField Field(DatabaseSchema schema, string name)
        => schema.Fields.Single(field => field.Name == name);

    private static string RootReadExpression(DatabaseScalarType type)
        => type switch
        {
            DatabaseScalarType.String => "reader.ReadString()",
            DatabaseScalarType.Int32 => "reader.ReadInt32()",
            _ => throw new DatabaseBuildException($"Unsupported generated route key type '{type}'."),
        };

    private static string ClrType(DatabaseScalarType type)
        => type switch
        {
            DatabaseScalarType.Boolean => "bool",
            DatabaseScalarType.Int32 => "int",
            DatabaseScalarType.Float64 => "double",
            DatabaseScalarType.String => "string",
            _ => throw new ArgumentOutOfRangeException(nameof(type)),
        };

    private static string PublicName(string value)
        => string.Concat(value.Split(['-', '_'], StringSplitOptions.RemoveEmptyEntries)
            .Select(part => char.ToUpperInvariant(part[0]) + part[1..]));

    private static string LocalName(string value)
    {
        string publicName = PublicName(value);
        return char.ToLowerInvariant(publicName[0]) + publicName[1..];
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
}
