<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Copeland.Markdown.Tests</AssemblyName>
    <RootNamespace>Copeland.Markdown.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Copeland.Markdown/Copeland.Markdown.csproj" />
    <ProjectReference Include="../../src/Machina.Standard/Machina.Standard.csproj" />
  </ItemGroup>
</Project>
