// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public sealed class __CopeRecord_r2
{
    internal __CopeRecord_r2(int value0, int value1, int value2, bool value3)
    {
        __field_r2_002Ef0 = value0;
        __field_r2_002Ef1 = value1;
        __field_r2_002Ef2 = value2;
        __field_r2_002Ef3 = value3;
    }

    public int __field_r2_002Ef0 { get; }

    public int __field_r2_002Ef1 { get; }

    public int __field_r2_002Ef2 { get; }

    public bool __field_r2_002Ef3 { get; }
}

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(AuditKind value0, int value1)
    {
        __field_r1_002Ef0 = value0;
        __field_r1_002Ef1 = value1;
    }

    internal AuditKind __field_r1_002Ef0 { get; }

    internal int __field_r1_002Ef1 { get; }
}


public abstract record AuditKind
{
    protected AuditKind()
    {
    }

    public sealed record Started : AuditKind;

    public sealed record Retried(int count) : AuditKind;

    public sealed record Completed(int total) : AuditKind;

    public sealed record Failed(string reason) : AuditKind;

}

public readonly record struct DeliveryTransitionResult(string Kind, string FromState, string? ToState, string Event, long Revision, bool IsTerminal, object? Error);
public static class Delivery
{
    public static Session Start() => new Session();
    public sealed class Session
    {
        private __CopeRecord_r2 board;
        private string state = "Idle";
        private bool terminal;
        private bool sending;
        private long revision;
        internal Session() { board = new __CopeRecord_r2(0, 0, 0, false); }
        public __CopeRecord_r2 Board => board;
        public string State => state;
        public bool IsTerminal => terminal;
        public long Revision => revision;
        public DeliveryTransitionResult SendStart(int amount)
        {
            if (sending) throw new global::System.InvalidOperationException("A Copeland flow session cannot receive a reentrant event.");
            if (terminal) return new("Terminal", state, null, "Start", revision, true, null);
            sending = true;
            try
            {
                switch (state)
                {
                    case "Idle":
                        if (!((amount > 0))) return new("Unhandled", state, null, "Start", revision, false, null);
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, amount, nextBoard.__field_r2_002Ef2, nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        nextBoard = new __CopeRecord_r2(((board).__field_r2_002Ef0 + 1), nextBoard.__field_r2_002Ef1, nextBoard.__field_r2_002Ef2, nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, nextBoard.__field_r2_002Ef1, ((board).__field_r2_002Ef2 + 1), nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Staging";
                        revision++;
                        return new("Transitioned", fromState, state, "Start", revision, false, null);
                    default:
                        return new("Unhandled", state, null, "Start", revision, false, null);
                }
            }
            finally
            {
                sending = false;
            }
        }
        public DeliveryTransitionResult SendRetry(int amount)
        {
            if (sending) throw new global::System.InvalidOperationException("A Copeland flow session cannot receive a reentrant event.");
            if (terminal) return new("Terminal", state, null, "Retry", revision, true, null);
            sending = true;
            try
            {
                switch (state)
                {
                    case "Staging":
                        if (!((amount > 0))) return new("Unhandled", state, null, "Retry", revision, false, null);
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        nextBoard = new __CopeRecord_r2(((board).__field_r2_002Ef0 + 1), nextBoard.__field_r2_002Ef1, nextBoard.__field_r2_002Ef2, nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, ((board).__field_r2_002Ef1 + amount), nextBoard.__field_r2_002Ef2, nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Retrying";
                        revision++;
                        return new("Transitioned", fromState, state, "Retry", revision, false, null);
                    default:
                        return new("Unhandled", state, null, "Retry", revision, false, null);
                }
            }
            finally
            {
                sending = false;
            }
        }
        public DeliveryTransitionResult SendAccept(int amount)
        {
            if (sending) throw new global::System.InvalidOperationException("A Copeland flow session cannot receive a reentrant event.");
            if (terminal) return new("Terminal", state, null, "Accept", revision, true, null);
            sending = true;
            try
            {
                switch (state)
                {
                    case "Staging":
                        if (!((amount >= 0))) return new("Unhandled", state, null, "Accept", revision, false, null);
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, ((board).__field_r2_002Ef1 + amount), nextBoard.__field_r2_002Ef2, nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, nextBoard.__field_r2_002Ef1, nextBoard.__field_r2_002Ef2, true);
                        board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Accepted";
                        revision++;
                        return new("Transitioned", fromState, state, "Accept", revision, false, null);
                    case "Retrying":
                        if (!((amount >= 0))) return new("Unhandled", state, null, "Accept", revision, false, null);
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, ((board).__field_r2_002Ef1 + amount), nextBoard.__field_r2_002Ef2, nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, nextBoard.__field_r2_002Ef1, nextBoard.__field_r2_002Ef2, true);
                        board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Accepted";
                        revision++;
                        return new("Transitioned", fromState, state, "Accept", revision, false, null);
                    case "Completing":
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, ((board).__field_r2_002Ef1 + amount), nextBoard.__field_r2_002Ef2, nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Completed";
                        revision++;
                        return EnterCompleted(fromState, "Accept");
                    default:
                        return new("Unhandled", state, null, "Accept", revision, false, null);
                }
            }
            finally
            {
                sending = false;
            }
        }
        public DeliveryTransitionResult SendReject(int code)
        {
            if (sending) throw new global::System.InvalidOperationException("A Copeland flow session cannot receive a reentrant event.");
            if (terminal) return new("Terminal", state, null, "Reject", revision, true, null);
            sending = true;
            try
            {
                switch (state)
                {
                    case "Staging":
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Rejected";
                        revision++;
                        return EnterRejected(fromState, "Reject");
                    case "Retrying":
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Rejected";
                        revision++;
                        return EnterRejected(fromState, "Reject");
                    case "Completing":
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Rejected";
                        revision++;
                        return EnterRejected(fromState, "Reject");
                    default:
                        return new("Unhandled", state, null, "Reject", revision, false, null);
                }
            }
            finally
            {
                sending = false;
            }
        }
        public DeliveryTransitionResult SendReset()
        {
            if (sending) throw new global::System.InvalidOperationException("A Copeland flow session cannot receive a reentrant event.");
            if (terminal) return new("Terminal", state, null, "Reset", revision, true, null);
            sending = true;
            try
            {
                switch (state)
                {
                    case "Accepted":
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, 0, nextBoard.__field_r2_002Ef2, nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        nextBoard = new __CopeRecord_r2(0, nextBoard.__field_r2_002Ef1, nextBoard.__field_r2_002Ef2, nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, nextBoard.__field_r2_002Ef1, nextBoard.__field_r2_002Ef2, false);
                        board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Idle";
                        revision++;
                        return new("Transitioned", fromState, state, "Reset", revision, false, null);
                    default:
                        return new("Unhandled", state, null, "Reset", revision, false, null);
                }
            }
            finally
            {
                sending = false;
            }
        }
        public DeliveryTransitionResult SendCancel()
        {
            if (sending) throw new global::System.InvalidOperationException("A Copeland flow session cannot receive a reentrant event.");
            if (terminal) return new("Terminal", state, null, "Cancel", revision, true, null);
            sending = true;
            try
            {
                switch (state)
                {
                    case "Idle":
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Cancelled";
                        revision++;
                        return EnterCancelled(fromState, "Cancel");
                    case "Retrying":
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Cancelled";
                        revision++;
                        return EnterCancelled(fromState, "Cancel");
                    default:
                        return new("Unhandled", state, null, "Cancel", revision, false, null);
                }
            }
            finally
            {
                sending = false;
            }
        }
        public DeliveryTransitionResult SendTick(int amount)
        {
            if (sending) throw new global::System.InvalidOperationException("A Copeland flow session cannot receive a reentrant event.");
            if (terminal) return new("Terminal", state, null, "Tick", revision, true, null);
            sending = true;
            try
            {
                switch (state)
                {
                    case "Staging":
                        if (!((amount > 0))) return new("Unhandled", state, null, "Tick", revision, false, null);
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, ((board).__field_r2_002Ef1 + amount), nextBoard.__field_r2_002Ef2, nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, nextBoard.__field_r2_002Ef1, ((board).__field_r2_002Ef2 + 1), nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Staging";
                        revision++;
                        return new("Transitioned", fromState, state, "Tick", revision, false, null);
                    case "Retrying":
                        if (!((amount > 0))) return new("Unhandled", state, null, "Tick", revision, false, null);
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, ((board).__field_r2_002Ef1 + amount), nextBoard.__field_r2_002Ef2, nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Retrying";
                        revision++;
                        return new("Transitioned", fromState, state, "Tick", revision, false, null);
                    case "Accepted":
                        if (!((amount > 0))) return new("Unhandled", state, null, "Tick", revision, false, null);
                        __CopeRecord_r2 nextBoard = this.board;
                        __CopeRecord_r2 board = nextBoard;
                        nextBoard = new __CopeRecord_r2(nextBoard.__field_r2_002Ef0, ((board).__field_r2_002Ef1 + amount), nextBoard.__field_r2_002Ef2, nextBoard.__field_r2_002Ef3);
                        board = nextBoard;
                        string fromState = state;
                        this.board = nextBoard;
                        state = "Completing";
                        revision++;
                        return new("Transitioned", fromState, state, "Tick", revision, false, null);
                    default:
                        return new("Unhandled", state, null, "Tick", revision, false, null);
                }
            }
            finally
            {
                sending = false;
            }
        }
        private DeliveryTransitionResult EnterCompleted(string fromState, string eventName)
        {
            __CopeRecord_r2 board = this.board;
            terminal = true;
            return new("Completed", fromState, state, eventName, revision, true, null);
        }
        private DeliveryTransitionResult EnterRejected(string fromState, string eventName)
        {
            __CopeRecord_r2 board = this.board;
            terminal = true;
            return new("Failed", fromState, state, eventName, revision, true, "delivery rejected");
        }
        private DeliveryTransitionResult EnterCancelled(string fromState, string eventName)
        {
            __CopeRecord_r2 board = this.board;
            terminal = true;
            return new("Failed", fromState, state, eventName, revision, true, "delivery cancelled");
        }
    }
}

public static class CopelandModule
{
    public static int nextSequence(int value)
    {
        return (value + 1);
    }

    public static int auditScore(__CopeRecord_r1 entry)
    {
        return (entry).__field_r1_002Ef0 switch { AuditKind.Started _ => (entry).__field_r1_002Ef1, AuditKind.Retried(var count) => ((entry).__field_r1_002Ef1 + count), AuditKind.Completed(var total) => ((entry).__field_r1_002Ef1 + total), AuditKind.Failed(var reason) => ((entry).__field_r1_002Ef1 + reason.Length), _ => throw new global::System.InvalidOperationException("Non-exhaustive match.") };
    }

    public static int main()
    {
        var __cope_record_init_0 = new AuditKind.Completed(42);
        var __cope_record_init_1 = 3;
        __CopeRecord_r1 entry = new __CopeRecord_r1(__cope_record_init_0, __cope_record_init_1);
        return auditScore(entry);
    }

}
