<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Machina.Dominatus</AssemblyName>
    <RootNamespace>Machina.Dominatus</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Machina.UI/Machina.Core/Machina.Core.csproj" />
    <ProjectReference Include="../../Machina.UI/Machina.Layout/Machina.Layout.csproj" />
    <ProjectReference Include="../../Machina.UI/Machina.Presentation/Machina.Presentation.csproj" />
    <ProjectReference Include="../../Machina.UI/Machina.Standard/Machina.Standard.csproj" />
    <PackageReference Include="Dominatus.Core" />
    <PackageReference Include="Dominatus.OptFlow" />
  </ItemGroup>
</Project>
