<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Machina.Testing/Machina.Testing.csproj" />
    <ProjectReference Include="../../src/Machina.Pipeline/Machina.Pipeline.csproj" />
    <ProjectReference Include="../../src/Machina.Standard/Machina.Standard.csproj" />
    <ProjectReference Include="../../src/Machina.Core/Machina.Core.csproj" />
    <ProjectReference Include="../../src/Machina.Layout/Machina.Layout.csproj" />
    <ProjectReference Include="../../src/Machina.Runtime/Machina.Runtime.csproj" />
    <ProjectReference Include="../../src/Machina.Renderer.Raster/Machina.Renderer.Raster.csproj" />
    <ProjectReference Include="../../src/Machina.Dominatus/Machina.Dominatus.csproj" />
    <ProjectReference Include="../../samples/Machina.Presenter.Sample/Machina.Presenter.Sample.csproj" />
  </ItemGroup>
</Project>
