// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public static class CopelandModule
{
    public static int xorIntegers(int left, int right)
    {
        int leftRemaining = ((left < 0) ? ((left + 2147483647) + 1) : left);
        int rightRemaining = ((right < 0) ? ((right + 2147483647) + 1) : right);
        int place = 1;
        int result = 0;
        {
            int bit = 0;
            for (; (bit < 31); bit = (bit + 1))
            {
                if (((leftRemaining % 2) != (rightRemaining % 2)))
                {
                    result = (result + place);
                }
                leftRemaining = (leftRemaining / 2);
                rightRemaining = (rightRemaining / 2);
                if ((bit < 30))
                {
                    place = (place * 2);
                }
            }
        }
        return (((left < 0) != (right < 0)) ? ((result - 2147483647) - 1) : result);
    }

    public static int hashIntegers(int[] values)
    {
        int hash = -2128831035;
        foreach (int value in values)
        {
            hash = (xorIntegers(hash, value) * 16777619);
        }
        return hash;
    }

    public static int run()
    {
        return hashIntegers(new int[] { 1, 2, 3 });
    }

}
