import json,pathlib
p=pathlib.Path('tests/Copeland/Copeland.TS.Tests/TypeScriptInstinctCorpus');p.mkdir(exist_ok=True)
cases=[]
def yes(id,cat,body,result,clr=False):
 cases.append(dict(Id=id,Category=cat,Input=body,Outcome='compile',ExpectedJson=result,ClrOnly=clr))
def no(id,cat,body,code,anchor,repair):
 cases.append(dict(Id=id,Category=cat,Input=body,Outcome='repair',PrimaryCode=code,Anchor=anchor,Repair=repair))
yes('string-split','strings','function run(): string[] { return String.Split(",a,,b,", ","); }','["","a","","b",""]')
yes('string-split-empty','strings','function run(): string[] { return String.Split("ab", ""); }','["a","b"]')
yes('string-index-ordinal','strings','function run(): int { return String.IndexOf("abcd", "bc"); }','1')
yes('string-code-utf16','strings','function run(): int { return String.CodeAt("😀", 0); }','55357')
yes('string-slice-negative','strings','function run(): string { return String.Slice("abcdef", -4, -1); }','"cde"')
yes('string-slice-reversed','strings','function run(): string { return String.Slice("abc", 2, 1); }','""')
yes('string-join','strings','function run(): string { return String.Join(["a", "b"], ","); }','"a,b"')
yes('array-filled','collections','function run(): int[] { const a = MutableArray<int>(3, 7); a[1] = 9; return a.freeze(); }','[7,9,7]')
yes('array-string-filled','collections','function run(): string[] { return MutableArray<string>(2, "x").freeze(); }','["x","x"]')
yes('increment-postfix','loops','function run(): int { let value: int = 3; const previous: int = value++; return previous * 10 + value; }','34')
yes('decrement-postfix','loops','function run(): int { let value: int = 3; const previous: int = value--; return previous * 10 + value; }','32')
yes('compound-all','mutation','function run(): int { let value: int = 4; value += 3; value *= 2; value -= 2; value /= 3; value %= 3; return value; }','1')
yes('loop-increment','loops','function run(): int { let total: int = 0; for (let i: int = 0; i < 10; i++) { total += i; } return total; }','45')
yes('conditional-expression','conditionals','function run(): int { return if (true) { 7 } else { 9 }; }','7')
yes('batch-guard','batch','function run(): int[] { return batch [-2, 0, 3] as item { if (item < 0) { return -item; } return item * 2; }; }','[2,0,6]')
yes('batch-if-else','batch','function run(): int[] { return batch [-2, 3] as item { if (item < 0) { return -item; } else { return item * 2; } }; }','[2,6]')
yes('int-add-wrap','numeric','function run(): int { return 2147483647 + 1; }','-2147483648')
yes('int-multiply-wrap','numeric','function run(): int { return 2147483647 * 2147483647; }','1')
yes('int-divide-wrap','numeric','function run(): int { const min: int = -2147483647 - 1; return min / -1; }','-2147483648')
yes('int-remainder-min','numeric','function run(): int { const min: int = -2147483647 - 1; return min % -1; }','0')
yes('int-remainder-sign','numeric','function run(): int { return -7 % 3; }','-1')
yes('int-negate-wrap','numeric','function run(): int { const min: int = -2147483647 - 1; return -min; }','-2147483648')
yes('bitwise-hash','numeric','function run(): int { return (123 ^ 45) * 16777619; }','1442885330')
yes('bitwise-shift-mask','numeric','function run(): int { return (1 << 33) | (8 >> 2); }','2')
yes('generic-identity','generics','function identity<T>(value: T): T { return value; } function run(): int { return identity<int>(7); }','7')
yes('generic-clr-list','interop','using System.Collections.Generic; function run(): int { const values = new List<int>(); values.Add(7); return values.Count; }','1',True)
yes('static-property-chain','static','using System.Globalization; function run(): int { return CultureInfo.InvariantCulture.CompareInfo.IndexOf("abcdef", "cd"); }','2',True)
yes('closure-capture','closures','function run(): int { const bias: int = 2; const add = (value: int): int => value + bias; return add(5); }','7')
yes('record-value','records','record Pair { left: int; right: int; } function run(): int { const p = Pair { left: 2, right: 3 }; return p.left + p.right; }','5')
no('receiver-split','strings','function run(): string[] { const text: string = "a,b"; return text.split(","); }','COPE-CALL-0021','split','String.Split(text, ",")')
no('length-case','strings','function run(): int { const text: string = "abc"; return text.Length; }','COPE-STRING-0001','Length','.length')
no('unknown-receiver','diagnostics','function run(): int { return Missing.Case(); }','COPE-BIND-0001','Missing','Undefined name')
no('array-push','collections','function run(): int { const values: int[] = [1]; values.push(2); return 0; }','COPE-CALL-0021','push','MutableArray<T>(length)')
no('computed-compound','mutation','function run(): int { const values = MutableArray<int>(2); values[0] += 1; return values[0]; }','COPE-MUTATION-0001','+=','const locals')
no('nullish-plain','Option','function run(): int { const value: int = 1; return value ?? 0; }','COPE-OPTION-0006','?','Option<T>')
(p/'instinct-corpus.json').write_text(json.dumps(cases,indent=2)+'\n')
