// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public static class CopelandModule
{
    public static int sumRange(int limit)
    {
        int total = 0;
        {
            int index = 0;
            for (; (index < limit); index = (index + 1))
            {
                total = (total + index);
            }
        }
        return total;
    }

    public static int run()
    {
        return sumRange(10);
    }

}
