from pathlib import Path
p=Path('src/Copeland/Copeland.TS/Semantics/Binder.cs');s=p.read_text();s=s.replace('private void ReportRepair(string id, string message, SyntaxToken token, string replacement)','private void ReportRepair(string id, string message, SyntaxToken token, string replacement, string repairKind = "canonical-form")').replace('suggestedReplacement: replacement, repairKind: "canonical-form"','suggestedReplacement: replacement, repairKind: repairKind')
s=s.replace('string arguments = string.Join(", ", call.Arguments.Select(AuthoredText));','string arguments = string.Join(", ", call.Arguments.Select(AuthoredText));\n                if (nativeMethod == "Slice" && call.Arguments.Count == 1)\n                {\n                    arguments += $", {AuthoredText(member.Target)}.length";\n                }')
p.write_text(s,newline='\n')
p=Path('src/Copeland/Copeland.TS/Syntax/Lexer.cs');s=p.read_text().replace('if (uint.TryParse(_text[digitsStart.._position],','if (_position - digitsStart is >= 1 and <= 8\n                && uint.TryParse(_text[digitsStart.._position],');p.write_text(s,newline='\n')
for file in ['src/Copeland/Copeland.TS.Backend.CSharp/CSharp/IntegerRuntime.cs','src/Copeland/Copeland.TS.Backend.JavaScript/IntegerRuntime.cs','src/Copeland/Copeland.TS.Backend.CSharp/CSharp/BatchRuntime.cs']:
 p=Path(file);s=p.read_text().replace("foreach (string line in source.Split('\\n')) writer.WriteLine(line);","foreach (string line in source.Split('\\n'))\n        {\n            writer.WriteLine(line);\n        }")
 s=s.replace('if (right == 0) throw new global::System.InvalidOperationException("Integer division by zero.");','if (right == 0)\n    {\n        throw new global::System.InvalidOperationException("Integer division by zero.");\n    }').replace('if (right === 0) throw new Error("Integer division by zero.");','if (right === 0) {\n        throw new Error("Integer division by zero.");\n    }')
 s=s.replace('private static int __cope_batch_parallel_threshold_for_testing = 0;','// M26 measurements favor parallel expensive work at 128 items; cheap work still favors sequential.\n// This count-only default is a conservative compromise, not a universal crossover.\nprivate const int __cope_batch_parallel_threshold = 128;\nprivate static int __cope_batch_parallel_threshold_for_testing = 0;').replace(': 128;',': __cope_batch_parallel_threshold;')
 s=s.replace('if (failures is not null) break;','if (failures is not null)\n            {\n                break;\n            }').replace('if (index < firstFailure) firstFailure = index;','if (index < firstFailure)\n            {\n                firstFailure = index;\n            }')
 p.write_text(s,newline='\n')
