<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Copeland.Cli</AssemblyName>
    <RootNamespace>Copeland.Cli</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Copeland.Markdown/Copeland.Markdown.csproj" />
    <ProjectReference Include="../Copeland.TS/Copeland.TS.csproj" />
    <ProjectReference Include="../Copeland.TS.Database/Copeland.TS.Database.csproj" />
    <ProjectReference Include="../Copeland.TS.Mir/Copeland.TS.Mir.csproj" />
    <ProjectReference Include="../Copeland.TS.Backend.CSharp/Copeland.TS.Backend.CSharp.csproj" />
    <ProjectReference Include="../Copeland.TS.Backend.JavaScript/Copeland.TS.Backend.JavaScript.csproj" />
    <ProjectReference Include="../Copeland.TS.LanguageServer/Copeland.TS.LanguageServer.csproj" />
  </ItemGroup>
</Project>
