// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(string value0, bool value1)
    {
        __field_r1_002Ef0 = value0;
        __field_r1_002Ef1 = value1;
    }

    internal string __field_r1_002Ef0 { get; }

    internal bool __field_r1_002Ef1 { get; }
}


public static class CopelandModule
{
    public static __CopeRecord_r1 load()
    {
        var __cope_record_init_0 = "fixture";
        var __cope_record_init_1 = true;
        __CopeRecord_r1 settings = new __CopeRecord_r1(__cope_record_init_0, __cope_record_init_1);
        return settings;
    }

}
