// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(double value0, double value1)
    {
        __field_r1_002Ef0 = value0;
        __field_r1_002Ef1 = value1;
    }

    internal double __field_r1_002Ef0 { get; }

    internal double __field_r1_002Ef1 { get; }
}


public static class CopelandModule
{
    public static __CopeRecord_r1 main()
    {
        var __cope_record_init_0 = 2.0;
        var __cope_record_init_1 = 40.0;
        return new __CopeRecord_r1(__cope_record_init_1, __cope_record_init_0);
    }

}
