// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(double value0, double value1)
    {
        __field_r1_002Ef0 = value0;
        __field_r1_002Ef1 = value1;
    }

    internal double __field_r1_002Ef0 { get; }

    internal double __field_r1_002Ef1 { get; }
}

public sealed class __CopeRecord_r2
{
    internal __CopeRecord_r2(__CopeRecord_r1 value0)
    {
        __field_r2_002Ef0 = value0;
    }

    internal __CopeRecord_r1 __field_r2_002Ef0 { get; }
}


public static class CopelandModule
{
    public static double main()
    {
        var __cope_record_init_0 = 40.0;
        var __cope_record_init_1 = 2.0;
        var __cope_record_init_2 = new __CopeRecord_r1(__cope_record_init_0, __cope_record_init_1);
        __CopeRecord_r2 envelope = new __CopeRecord_r2(__cope_record_init_2);
        return (((envelope).__field_r2_002Ef0).__field_r1_002Ef0 + ((envelope).__field_r2_002Ef0).__field_r1_002Ef1);
    }

}
