// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(double value0, double value1)
    {
        __field_r1_002Ef0 = value0;
        __field_r1_002Ef1 = value1;
    }

    internal double __field_r1_002Ef0 { get; }

    internal double __field_r1_002Ef1 { get; }
}


public static class CopelandModule
{
    public static double main()
    {
        var __cope_record_init_0 = 1.0;
        var __cope_record_init_1 = 2.0;
        __CopeRecord_r1 source = new __CopeRecord_r1(__cope_record_init_0, __cope_record_init_1);
        var __cope_record_source_2 = source;
        var __cope_record_replacement_3 = 2.0;
        var __cope_record_replacement_4 = 40.0;
        __CopeRecord_r1 updated = new __CopeRecord_r1(__cope_record_replacement_4, __cope_record_replacement_3);
        return ((updated).__field_r1_002Ef0 + (updated).__field_r1_002Ef1);
    }

}
