<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Copeland.StandaloneWebM0.Generate</RootNamespace>
    <AssemblyName>StandaloneWebM0.Generate</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Copeland\Copeland.TS\Copeland.TS.csproj" />
    <ProjectReference Include="..\..\..\..\src\Copeland\Copeland.TS.Backend.AspNetCore\Copeland.TS.Backend.AspNetCore.csproj" />
    <ProjectReference Include="..\..\..\..\src\Copeland\Copeland.TS.Backend.CSharp\Copeland.TS.Backend.CSharp.csproj" />
    <ProjectReference Include="..\..\..\..\src\Copeland\Copeland.TS.Backend.JavaScript\Copeland.TS.Backend.JavaScript.csproj" />
  </ItemGroup>
</Project>
