// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public static class CopelandModule
{
    public static double[] main()
    {
        double[] xs = new double[] { 1.0, 2.0, 3.0 };
        return xs;
    }

}
