// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public readonly struct CopeResult<TValue, TError>
{
    private readonly TValue _value;
    private readonly TError _error;
    public bool IsOk { get; }

    public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException("Result has no value.");
    public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException("Result has no error.");

    private CopeResult(bool isOk, TValue value, TError error)
    {
        IsOk = isOk;
        _value = value;
        _error = error;
    }

    public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);
    public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);
}

public readonly record struct ParseError;

public static class CopelandModule
{
    public static CopeResult<double, ParseError> parseNumber(string text)
    {
        return CopeResult<double, ParseError>.Ok(1.0);
    }

    public static CopeResult<double, ParseError> caller(string text)
    {
        var __cope_tmp0 = parseNumber(text);
        if (!__cope_tmp0.IsOk)
        {
            return CopeResult<double, ParseError>.Err(__cope_tmp0.Error);
        }
        double x = __cope_tmp0.Value;
        return CopeResult<double, ParseError>.Ok(x);
    }

}
