<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Copeland.Machina.M1</AssemblyName>
    <RootNamespace>Copeland.Machina.M1</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Copeland/Copeland.TS/Copeland.TS.csproj" />
    <ProjectReference Include="../../../src/Copeland/Copeland.TS.Mir/Copeland.TS.Mir.csproj" />
  </ItemGroup>
</Project>
