// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public readonly struct CopeResult<TValue, TError>
{
    private readonly TValue _value;
    private readonly TError _error;
    public bool IsOk { get; }

    public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException("Result has no value.");
    public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException("Result has no error.");

    private CopeResult(bool isOk, TValue value, TError error)
    {
        IsOk = isOk;
        _value = value;
        _error = error;
    }

    public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);
    public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);
}

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(double value0, string value1)
    {
        __field_r1_002Ef0 = value0;
        __field_r1_002Ef1 = value1;
    }

    internal double __field_r1_002Ef0 { get; }

    internal string __field_r1_002Ef1 { get; }
}


public abstract record TableBoundsError
{
    protected TableBoundsError()
    {
    }

    public sealed record InvalidIndex(double index) : TableBoundsError;

    public sealed record OutOfBounds(double index, double rowCount) : TableBoundsError;

}
public abstract record State
{
    protected State()
    {
    }

    public sealed record Missing : State;

    public sealed record Named(string label) : State;

}

public abstract class CopeColumn<T>
{
    internal abstract CopeResult<T, TableBoundsError> Get(double index);
}

public sealed class __CopeTableColumn_t1_002Ec0 : CopeColumn<bool>
{
    private readonly bool[] _values;

    internal __CopeTableColumn_t1_002Ec0(bool[] values)
    {
        _values = values;
    }

    internal override CopeResult<bool, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<bool, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 2)
        {
            return CopeResult<bool, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 2.0));
        }
        return CopeResult<bool, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t1_002Ec1 : CopeColumn<double>
{
    private readonly double[] _values;

    internal __CopeTableColumn_t1_002Ec1(double[] values)
    {
        _values = values;
    }

    internal override CopeResult<double, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<double, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 2)
        {
            return CopeResult<double, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 2.0));
        }
        return CopeResult<double, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t1_002Ec2 : CopeColumn<string>
{
    private readonly string[] _values;

    internal __CopeTableColumn_t1_002Ec2(string[] values)
    {
        _values = values;
    }

    internal override CopeResult<string, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<string, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 2)
        {
            return CopeResult<string, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 2.0));
        }
        return CopeResult<string, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t1_002Ec3 : CopeColumn<__CopeRecord_r1>
{
    private readonly __CopeRecord_r1[] _values;

    internal __CopeTableColumn_t1_002Ec3(__CopeRecord_r1[] values)
    {
        _values = values;
    }

    internal override CopeResult<__CopeRecord_r1, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<__CopeRecord_r1, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 2)
        {
            return CopeResult<__CopeRecord_r1, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 2.0));
        }
        return CopeResult<__CopeRecord_r1, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t1_002Ec4 : CopeColumn<State>
{
    private readonly State[] _values;

    internal __CopeTableColumn_t1_002Ec4(State[] values)
    {
        _values = values;
    }

    internal override CopeResult<State, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<State, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 2)
        {
            return CopeResult<State, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 2.0));
        }
        return CopeResult<State, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableColumn_t1_002Ec5 : CopeColumn<double[][]>
{
    private readonly double[][][] _values;

    internal __CopeTableColumn_t1_002Ec5(double[][][] values)
    {
        _values = values;
    }

    internal override CopeResult<double[][], TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<double[][], TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 2)
        {
            return CopeResult<double[][], TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 2.0));
        }
        return CopeResult<double[][], TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableRow_t1_002Erow
{
    private readonly __CopeTable_t1 _table;
    private readonly int _index;

    internal __CopeTableRow_t1_002Erow(__CopeTable_t1 table, int index)
    {
        _table = table;
        _index = index;
    }

    internal bool __row_field_t1_002Ec0 => _table.__read_t1_002Ec0(_index);

    internal double __row_field_t1_002Ec1 => _table.__read_t1_002Ec1(_index);

    internal string __row_field_t1_002Ec2 => _table.__read_t1_002Ec2(_index);

    internal __CopeRecord_r1 __row_field_t1_002Ec3 => _table.__read_t1_002Ec3(_index);

    internal State __row_field_t1_002Ec4 => _table.__read_t1_002Ec4(_index);

    internal double[][] __row_field_t1_002Ec5 => _table.__read_t1_002Ec5(_index);
}

public sealed class __CopeTable_t1
{
    private readonly bool[] _column_t1_002Ec0;
    private readonly double[] _column_t1_002Ec1;
    private readonly string[] _column_t1_002Ec2;
    private readonly __CopeRecord_r1[] _column_t1_002Ec3;
    private readonly State[] _column_t1_002Ec4;
    private readonly double[][][] _column_t1_002Ec5;

    private __CopeTable_t1(bool[] values0, double[] values1, string[] values2, __CopeRecord_r1[] values3, State[] values4, double[][][] values5)
    {
        _column_t1_002Ec0 = values0;
        __column_t1_002Ec0 = new __CopeTableColumn_t1_002Ec0(values0);
        _column_t1_002Ec1 = values1;
        __column_t1_002Ec1 = new __CopeTableColumn_t1_002Ec1(values1);
        _column_t1_002Ec2 = values2;
        __column_t1_002Ec2 = new __CopeTableColumn_t1_002Ec2(values2);
        _column_t1_002Ec3 = values3;
        __column_t1_002Ec3 = new __CopeTableColumn_t1_002Ec3(values3);
        _column_t1_002Ec4 = values4;
        __column_t1_002Ec4 = new __CopeTableColumn_t1_002Ec4(values4);
        _column_t1_002Ec5 = values5;
        __column_t1_002Ec5 = new __CopeTableColumn_t1_002Ec5(values5);
    }

    internal static __CopeTable_t1 Create()
    {
        return new __CopeTable_t1(
            new bool[] { true, false },
            new double[] { -0.0, global::System.BitConverter.UInt64BitsToDouble(0x7FF8000000000000UL) },
            new string[] { "quote \" slash \\ newline\n", "雪 😀" },
            new __CopeRecord_r1[] { new __CopeRecord_r1(1.0, "first"), new __CopeRecord_r1(2.0, "second") },
            new State[] { new State.Missing(), new State.Named("ready") },
            new double[][][] { new double[][] { new double[] {  }, new double[] { 1.0, 2.0 } }, new double[][] { new double[] { 3.0 }, new double[] {  } } }
        );
    }

    internal __CopeTableColumn_t1_002Ec0 __column_t1_002Ec0 { get; }

    internal bool __read_t1_002Ec0(int index) => _column_t1_002Ec0[index];

    internal __CopeTableColumn_t1_002Ec1 __column_t1_002Ec1 { get; }

    internal double __read_t1_002Ec1(int index) => _column_t1_002Ec1[index];

    internal __CopeTableColumn_t1_002Ec2 __column_t1_002Ec2 { get; }

    internal string __read_t1_002Ec2(int index) => _column_t1_002Ec2[index];

    internal __CopeTableColumn_t1_002Ec3 __column_t1_002Ec3 { get; }

    internal __CopeRecord_r1 __read_t1_002Ec3(int index) => _column_t1_002Ec3[index];

    internal __CopeTableColumn_t1_002Ec4 __column_t1_002Ec4 { get; }

    internal State __read_t1_002Ec4(int index) => _column_t1_002Ec4[index];

    internal __CopeTableColumn_t1_002Ec5 __column_t1_002Ec5 { get; }

    internal double[][] __read_t1_002Ec5(int index) => _column_t1_002Ec5[index];

    internal CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError> GetRow(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 2)
        {
            return CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 2.0));
        }
        return CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError>.Ok(new __CopeTableRow_t1_002Erow(this, (int)index));
    }
}

public sealed class __CopeTableColumn_t2_002Ec0 : CopeColumn<double>
{
    private readonly double[] _values;

    internal __CopeTableColumn_t2_002Ec0(double[] values)
    {
        _values = values;
    }

    internal override CopeResult<double, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<double, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 0)
        {
            return CopeResult<double, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 0.0));
        }
        return CopeResult<double, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableRow_t2_002Erow
{
    private readonly __CopeTable_t2 _table;
    private readonly int _index;

    internal __CopeTableRow_t2_002Erow(__CopeTable_t2 table, int index)
    {
        _table = table;
        _index = index;
    }

    internal double __row_field_t2_002Ec0 => _table.__read_t2_002Ec0(_index);
}

public sealed class __CopeTable_t2
{
    private readonly double[] _column_t2_002Ec0;

    private __CopeTable_t2(double[] values0)
    {
        _column_t2_002Ec0 = values0;
        __column_t2_002Ec0 = new __CopeTableColumn_t2_002Ec0(values0);
    }

    internal static __CopeTable_t2 Create()
    {
        return new __CopeTable_t2(
            new double[] {  }
        );
    }

    internal __CopeTableColumn_t2_002Ec0 __column_t2_002Ec0 { get; }

    internal double __read_t2_002Ec0(int index) => _column_t2_002Ec0[index];

    internal CopeResult<__CopeTableRow_t2_002Erow, TableBoundsError> GetRow(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<__CopeTableRow_t2_002Erow, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 0)
        {
            return CopeResult<__CopeTableRow_t2_002Erow, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 0.0));
        }
        return CopeResult<__CopeTableRow_t2_002Erow, TableBoundsError>.Ok(new __CopeTableRow_t2_002Erow(this, (int)index));
    }
}

public static class CopelandModule
{
    private static readonly __CopeTable_t1 __cope_table_t1 = __CopeTable_t1.Create();
    private static readonly __CopeTable_t2 __cope_table_t2 = __CopeTable_t2.Create();

    private sealed class CopeUnwrapPanicException : global::System.Exception
    {
        public object? Error { get; }

        public CopeUnwrapPanicException(object? error)
            : base("COPE-PANIC-UNWRAP: Result unwrap encountered err")
        {
            Error = error;
        }
    }

    public static string observation()
    {
        var __cope_tmp0 = __cope_table_t1.GetRow(1.0);
        if (!__cope_tmp0.IsOk)
        {
            throw new CopeUnwrapPanicException(__cope_tmp0.Error);
        }
        __CopeTableRow_t1_002Erow row = __cope_tmp0.Value;
        return row.__row_field_t1_002Ec4 switch { State.Missing _ => "missing", State.Named(var label) => label, _ => throw new global::System.InvalidOperationException("Non-exhaustive match.") };
    }

    public static double negativeZero()
    {
        var __cope_tmp0 = __cope_table_t1.__column_t1_002Ec1.Get(0.0);
        if (!__cope_tmp0.IsOk)
        {
            throw new CopeUnwrapPanicException(__cope_tmp0.Error);
        }
        return __cope_tmp0.Value;
    }

    public static double[][] nested()
    {
        var __cope_tmp0 = __cope_table_t1.__column_t1_002Ec5.Get(1.0);
        if (!__cope_tmp0.IsOk)
        {
            throw new CopeUnwrapPanicException(__cope_tmp0.Error);
        }
        return __cope_tmp0.Value;
    }

    public static double emptyBounds()
    {
        var __cope_tmp0 = __cope_table_t2.__column_t2_002Ec0.Get(0.0);
        double __cope_tmp1;
        if (__cope_tmp0.IsOk)
        {
            var value = __cope_tmp0.Value;
            __cope_tmp1 = value;
        }
        else
        {
            var error = __cope_tmp0.Error;
            __cope_tmp1 = error switch { TableBoundsError.InvalidIndex(var index) => 1000.0, TableBoundsError.OutOfBounds(var index, var rowCount) => 2000.0, _ => throw new global::System.InvalidOperationException("Non-exhaustive match.") };
        }
        return __cope_tmp1;
    }

}
