<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Oblivion/Oblivion.Standalone/Oblivion.Standalone.csproj" />
    <ProjectReference Include="../../../src/Oblivion/Oblivion.Persistence/Oblivion.Persistence.csproj" />
  </ItemGroup>
</Project>
