<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Oblivion.Persistence</AssemblyName>
    <RootNamespace>Oblivion.Persistence</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Oblivion.Model/Oblivion.Model.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Tomlyn" />
  </ItemGroup>
</Project>
