// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public static class CopelandModule
{
    public static double choose(bool flag)
    {
        if (flag)
        {
            return 1.0;
        }
        else
        {
            return 2.0;
        }
    }

}
