// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(double value0, double value1)
    {
        __field_r1_002Ef0 = value0;
        __field_r1_002Ef1 = value1;
    }

    internal double __field_r1_002Ef0 { get; }

    internal double __field_r1_002Ef1 { get; }
}


public static class CopelandModule
{
    public static double identity__primitive_number__8F3BAE8FF0D9F338(double value)
    {
        return value;
    }

    public static double sum__record_Point__AD972DE51050F4B6(__CopeRecord_r1 value)
    {
        return ((value).__field_r1_002Ef0 + (value).__field_r1_002Ef1);
    }

    public static double main()
    {
        var __cope_record_init_0 = 20.0;
        var __cope_record_init_1 = 22.0;
        __CopeRecord_r1 point = new __CopeRecord_r1(__cope_record_init_0, __cope_record_init_1);
        double @explicit = identity__primitive_number__8F3BAE8FF0D9F338(sum__record_Point__AD972DE51050F4B6(point));
        double inferred = identity__primitive_number__8F3BAE8FF0D9F338(sum__record_Point__AD972DE51050F4B6(point));
        return (@explicit + inferred);
    }

}
