// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public static class CopelandModule
{
    public static double main()
    {
        double x = 1.0;
        x = 2.0;
        return x;
    }

}
