// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public readonly record struct CopeUnit
{
    public static readonly CopeUnit Value = new();
}

public readonly struct CopeResult<TValue, TError>
{
    private readonly TValue _value;
    private readonly TError _error;
    public bool IsOk { get; }

    public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException("Result has no value.");
    public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException("Result has no error.");

    private CopeResult(bool isOk, TValue value, TError error)
    {
        IsOk = isOk;
        _value = value;
        _error = error;
    }

    public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);
    public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);
}

public readonly record struct SaveError;

public static class CopelandModule
{
    public static CopeResult<CopeUnit, SaveError> save()
    {
        return CopeResult<CopeUnit, SaveError>.Ok(CopeUnit.Value);
    }

}
