// <auto-generated />
#nullable enable

namespace Copeland.Generated;

internal static class CopeArray
{
    public static T[] Create<T>(int length)
    {
        if (length < 0)
        {
            throw new global::System.ArgumentOutOfRangeException(nameof(length), "Copeland mutable array length cannot be negative.");
        }
        return new T[length];
    }
    public static T Get<T>(T[] values, int index)
    {
        if (index < 0 || index >= values.Length)
        {
            throw new global::System.IndexOutOfRangeException("Copeland array index is out of bounds.");
        }
        return values[index];
    }
    public static T Set<T>(T[] values, int index, T value)
    {
        if (index < 0 || index >= values.Length)
        {
            throw new global::System.IndexOutOfRangeException("Copeland array index is out of bounds.");
        }
        values[index] = value;
        return value;
    }
}

public readonly struct CopeResult<TValue, TError>
{
    private readonly TValue _value;
    private readonly TError _error;
    public bool IsOk { get; }

    public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException("Result has no value.");
    public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException("Result has no error.");

    private CopeResult(bool isOk, TValue value, TError error)
    {
        IsOk = isOk;
        _value = value;
        _error = error;
    }

    public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);
    public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);
}

public sealed class CopeAsync<T>
{
    private readonly global::System.Collections.Generic.List<(global::System.Action Success, global::System.Action Cancelled, global::System.Action Failed, global::System.Action Panicked)> continuations = []; 
    private int terminalState;
    public bool IsCompleted => terminalState != 0;
    public bool IsCancelled => terminalState == 2;
    public bool IsPanicked => terminalState == 3;
    public bool IsTransportFailed => terminalState == 4;
    public T Value { get; private set; } = default!;
    public bool Subscribe(global::System.Action success, global::System.Action cancelled, global::System.Action panicked) => SubscribeTransport(success, cancelled, panicked, panicked);
    public bool SubscribeTransport(global::System.Action success, global::System.Action cancelled, global::System.Action failed, global::System.Action panicked)
    {
        if (IsCompleted) return true;
        continuations.Add((success, cancelled, failed, panicked));
        return false;
    }
    public void Resolve(T value)
    {
        if (terminalState != 0) return;
        terminalState = 1;
        Value = value;
        var pending = continuations.ToArray();
        continuations.Clear();
        foreach (var continuation in pending) continuation.Success();
    }
    public void Cancel()
    {
        if (terminalState != 0) return;
        terminalState = 2;
        var pending = continuations.ToArray();
        continuations.Clear();
        foreach (var continuation in pending) continuation.Cancelled();
    }
    public void Fail()
    {
        if (terminalState != 0) return;
        terminalState = 4;
        var pending = continuations.ToArray();
        continuations.Clear();
        foreach (var continuation in pending) continuation.Failed();
    }
    public void Panic()
    {
        if (terminalState != 0) return;
        terminalState = 3;
        var pending = continuations.ToArray();
        continuations.Clear();
        foreach (var continuation in pending) continuation.Panicked();
    }
}
internal static class CopeAsyncPending
{
    internal static CopeAsync<T> Create<T>() => new CopeAsync<T>();
}

internal sealed class CopeGeneratorEnumerable<T>(global::System.Func<global::System.Collections.Generic.IEnumerator<T>> create) : global::System.Collections.Generic.IEnumerable<T>
{
    public global::System.Collections.Generic.IEnumerator<T> GetEnumerator() => new CopeGeneratorEnumerator<T>(create());
    global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
}
internal sealed class CopeGeneratorEnumerator<T>(global::System.Collections.Generic.IEnumerator<T> inner) : global::System.Collections.Generic.IEnumerator<T>
{
    private bool disposed;
    private bool running;
    public T Current => inner.Current;
    object global::System.Collections.IEnumerator.Current => Current!;
    public bool MoveNext()
    {
        if (disposed) return false;
        if (running) throw new global::System.InvalidOperationException("A Copeland generator cannot be resumed while it is already running.");
        running = true;
        try { return inner.MoveNext(); }
        finally { running = false; }
    }
    public void Reset() => throw new global::System.NotSupportedException();
    public void Dispose() { if (disposed) return; disposed = true; inner.Dispose(); }
}

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(int value0, double value1)
    {
        __field_r1_002Ef0 = value0;
        __field_r1_002Ef1 = value1;
    }

    internal int __field_r1_002Ef0 { get; }

    internal double __field_r1_002Ef1 { get; }
}

public sealed class __CopeRecord_r2
{
    internal __CopeRecord_r2(double value0, double value1)
    {
        __field_r2_002Ef0 = value0;
        __field_r2_002Ef1 = value1;
    }

    public double __field_r2_002Ef0 { get; }

    internal double __field_r2_002Ef1 { get; }
}

public sealed class __CopeRecord_r3
{
    internal __CopeRecord_r3(double value0, double value1)
    {
        __field_r3_002Ef0 = value0;
        __field_r3_002Ef1 = value1;
    }

    internal double __field_r3_002Ef0 { get; }

    internal double __field_r3_002Ef1 { get; }
}


public static class CopelandModule
{
    // Private test seam: never reachable from authored Copeland code.
    private static global::System.Action? __cope_batch_item_entered_for_testing = null;
    private static int __cope_batch_max_degree_for_testing = 0;

    private sealed class __CopeAsyncFrame_load
    {
        public int State;
        public double value = default!;
        public double @checked = default!;
        public double __expression_0 = default!;
    }

    private sealed class __CopeAsyncFrame_compose
    {
        public int State;
        public double value = default!;
        public __CopeRecord_r2 boxed = default!;
        public double loaded = default!;
        public __CopeRecord_r3 local = default!;
        public CopeAsync<CopeResult<double, string>> pending = default!;
        public CopeAsync<CopeResult<double, string>> __await_0 = default!;
        public CopeResult<double, string> __await_value_0 = default!;
        public double __expression_0 = default!;
    }

    public static __CopeRecord_r2 LoadedValue__constructor(double raw, double scaled)
    {
        var __cope_record_init_0 = raw;
        var __cope_record_init_1 = scaled;
        return new __CopeRecord_r2(__cope_record_init_0, __cope_record_init_1);
    }

    public static double LoadedValue__total(__CopeRecord_r2 value)
    {
        return ((value).__field_r2_002Ef0 + (value).__field_r2_002Ef1);
    }

    public static double normalize(double value)
    {
        return (value * 2.0);
    }

    public static CopeResult<double, string> validate(double value)
    {
        if ((value < 0.0))
        {
            return CopeResult<double, string>.Err("negative");
        }
        return CopeResult<double, string>.Ok(value);
    }

    public static global::System.Collections.Generic.IEnumerable<double> seedValues() => new CopeGeneratorEnumerable<double>(() => __cope_generator_seedValues().GetEnumerator());
    private static global::System.Collections.Generic.IEnumerable<double> __cope_generator_seedValues()
    {
        yield return 1.0;
        yield return 2.0;
        yield return 3.0;
    }

    public static global::System.Collections.Generic.IEnumerable<double> values() => new CopeGeneratorEnumerable<double>(() => __cope_generator_values().GetEnumerator());
    private static global::System.Collections.Generic.IEnumerable<double> __cope_generator_values()
    {
        yield return 0.0;
        foreach (var __cope_delegated in seedValues()) yield return __cope_delegated;
        yield return 4.0;
    }

    public static double[] collect()
    {
        double[] buffer = CopeArray.Create<double>(checked((int)5));
        int index = 0;
        foreach (double value in values())
        {
            CopeArray.Set(buffer, checked((int)index), value);
            index = (index + 1);
        }
        return (double[])buffer.Clone();
    }

    public static double[] transform(double[] input)
    {
        double increment = 1.0;
        double[] __cope_batch_input_0 = input;
        double[] __cope_batch_output_0 = new double[__cope_batch_input_0.Length];
        var __cope_batch_failures_0 = new global::System.Collections.Concurrent.ConcurrentDictionary<int, global::System.Exception>();
        var __cope_batch_options_0 = new global::System.Threading.Tasks.ParallelOptions();
        if (__cope_batch_max_degree_for_testing > 0)
        {
            __cope_batch_options_0.MaxDegreeOfParallelism = __cope_batch_max_degree_for_testing;
        }
        global::System.Threading.Tasks.Parallel.For(0, __cope_batch_input_0.Length, __cope_batch_options_0, __cope_batch_index_0 =>
        {
            try
            {
                __cope_batch_item_entered_for_testing?.Invoke();
                double value = __cope_batch_input_0[__cope_batch_index_0];
                var __cope_tmp1 = validate(value);
                if (!__cope_tmp1.IsOk)
                {
                    throw new CopeUnwrapPanicException(__cope_tmp1.Error);
                }
                double @checked = __cope_tmp1.Value;
                __cope_batch_output_0[__cope_batch_index_0] = normalize((@checked + increment));
            }
            catch (global::System.Exception exception)
            {
                __cope_batch_failures_0.TryAdd(__cope_batch_index_0, exception);
            }
        });
        if (!__cope_batch_failures_0.IsEmpty)
        {
            var __cope_batch_failure_index = int.MaxValue;
            foreach (int __cope_batch_candidate in __cope_batch_failures_0.Keys)
            {
                if (__cope_batch_candidate < __cope_batch_failure_index) __cope_batch_failure_index = __cope_batch_candidate;
            }
            throw new global::System.InvalidOperationException($"COPE-BATCH-FAILURE index {__cope_batch_failure_index}", __cope_batch_failures_0[__cope_batch_failure_index]);
        }
        return __cope_batch_output_0;
    }

    public static CopeAsync<CopeResult<double, string>> load(double value)
    {
        var frame = new __CopeAsyncFrame_load();
        frame.value = value;
        var computation = new CopeAsync<CopeResult<double, string>>();
        frame.State = 3;
        void Step()
        {
            if (computation.IsCompleted) return;
            while (true)
            {
                switch (frame.State)
                {
                    case 0:
                        computation.Resolve(default!);
                        return;
                    case 1:
                        computation.Resolve(CopeResult<double, string>.Ok((frame.@checked + 1.0)));
                        return;
                    case 2:
                        frame.@checked = frame.__expression_0;
                        frame.State = 1;
                        continue;
                    case 3:
                        var __cope_propagate_3 = validate(frame.value);
                        if (!__cope_propagate_3.IsOk) { computation.Resolve(CopeResult<double, string>.Err(__cope_propagate_3.Error)); return; }
                        frame.__expression_0 = __cope_propagate_3.Value;
                        frame.State = 2;
                        continue;
                    default:
                        return;
                }
            }
        }
        Step();
        return computation;
    }

    public static CopeAsync<CopeResult<double, string>> compose(double value)
    {
        var frame = new __CopeAsyncFrame_compose();
        frame.value = value;
        var computation = new CopeAsync<CopeResult<double, string>>();
        frame.State = 7;
        void Step()
        {
            if (computation.IsCompleted) return;
            while (true)
            {
                switch (frame.State)
                {
                    case 0:
                        computation.Resolve(default!);
                        return;
                    case 1:
                        computation.Resolve(CopeResult<double, string>.Ok(((LoadedValue__total(frame.boxed) + (frame.local).__field_r3_002Ef0) + (frame.local).__field_r3_002Ef1)));
                        return;
                    case 2:
                        frame.local = new __CopeRecord_r3(frame.loaded, (frame.loaded * 2.0));
                        frame.State = 1;
                        continue;
                    case 3:
                        frame.boxed = LoadedValue__constructor(frame.loaded, (frame.loaded * 2.0));
                        frame.State = 2;
                        continue;
                    case 4:
                        frame.loaded = frame.__expression_0;
                        frame.State = 3;
                        continue;
                    case 5:
                        var __cope_propagate_5 = frame.__await_value_0;
                        if (!__cope_propagate_5.IsOk) { computation.Resolve(CopeResult<double, string>.Err(__cope_propagate_5.Error)); return; }
                        frame.__expression_0 = __cope_propagate_5.Value;
                        frame.State = 4;
                        continue;
                    case 6:
                        frame.__await_0 = frame.pending;
                        frame.State = 5;
                        if (!frame.__await_0.SubscribeTransport(() => { frame.__await_value_0 = frame.__await_0.Value; Step(); }, computation.Cancel, computation.Fail, computation.Panic)) return;
                        if (frame.__await_0.IsCancelled) { computation.Cancel(); return; }
                        if (frame.__await_0.IsTransportFailed) { computation.Fail(); return; }
                        if (frame.__await_0.IsPanicked) { computation.Panic(); return; }
                        frame.__await_value_0 = frame.__await_0.Value;
                        continue;
                    case 7:
                        frame.pending = load(frame.value);
                        frame.State = 6;
                        continue;
                    default:
                        return;
                }
            }
        }
        Step();
        return computation;
    }

    public static double main()
    {
        double[] collected = collect();
        double[] transformed = transform(collected);
        double total = 0.0;
        foreach (double value in transformed)
        {
            total = (total + value);
        }
        return total;
    }

}
