// Generated by Aurelian VD-MIR HLSL M0.
// namespace Aurelian.Smoke

struct VertexInput {
    float3 Position : POSITION;
    float4 Color : COLOR0;
};

struct VertexOutput {
    float4 Position : SV_Position;
    float4 Color : COLOR0;
};

VertexOutput VSMain(VertexInput input)
{
    VertexOutput output;
    output.Position = float4(input.Position, 1.0);
    output.Color = input.Color;
    return output;
}

float4 PSMain(VertexOutput input) : SV_Target0
{
    return input.Color;
}

