// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public readonly struct CopeResult<TValue, TError>
{
    private readonly TValue _value;
    private readonly TError _error;
    public bool IsOk { get; }

    public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException("Result has no value.");
    public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException("Result has no error.");

    private CopeResult(bool isOk, TValue value, TError error)
    {
        IsOk = isOk;
        _value = value;
        _error = error;
    }

    public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);
    public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);
}

public abstract record TableBoundsError
{
    protected TableBoundsError()
    {
    }

    public sealed record InvalidIndex(double index) : TableBoundsError;

    public sealed record OutOfBounds(double index, double rowCount) : TableBoundsError;

}

public abstract class CopeColumn<T>
{
    internal abstract CopeResult<T, TableBoundsError> Get(double index);
}

public sealed class __CopeTableColumn_t1_002Ec0 : CopeColumn<double>
{
    private readonly double[] _values;

    internal __CopeTableColumn_t1_002Ec0(double[] values)
    {
        _values = values;
    }

    internal override CopeResult<double, TableBoundsError> Get(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<double, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 0)
        {
            return CopeResult<double, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 0.0));
        }
        return CopeResult<double, TableBoundsError>.Ok(_values[(int)index]);
    }
}

public sealed class __CopeTableRow_t1_002Erow
{
    private readonly __CopeTable_t1 _table;
    private readonly int _index;

    internal __CopeTableRow_t1_002Erow(__CopeTable_t1 table, int index)
    {
        _table = table;
        _index = index;
    }

    internal double __row_field_t1_002Ec0 => _table.__read_t1_002Ec0(_index);
}

public sealed class __CopeTable_t1
{
    private readonly double[] _column_t1_002Ec0;

    private __CopeTable_t1(double[] values0)
    {
        _column_t1_002Ec0 = values0;
        __column_t1_002Ec0 = new __CopeTableColumn_t1_002Ec0(values0);
    }

    internal static __CopeTable_t1 Create()
    {
        return new __CopeTable_t1(
            new double[] {  }
        );
    }

    internal __CopeTableColumn_t1_002Ec0 __column_t1_002Ec0 { get; }

    internal double __read_t1_002Ec0(int index) => _column_t1_002Ec0[index];

    internal CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError> GetRow(double index)
    {
        if (double.IsNaN(index) || double.IsInfinity(index) || index != global::System.Math.Truncate(index))
        {
            return CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError>.Err(new TableBoundsError.InvalidIndex(index));
        }
        if (index < 0 || index >= 0)
        {
            return CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError>.Err(new TableBoundsError.OutOfBounds(index, 0.0));
        }
        return CopeResult<__CopeTableRow_t1_002Erow, TableBoundsError>.Ok(new __CopeTableRow_t1_002Erow(this, (int)index));
    }
}

public static class CopelandModule
{
    private static readonly __CopeTable_t1 __cope_table_t1 = __CopeTable_t1.Create();

    public static double main()
    {
        var __cope_tmp0 = __cope_table_t1.GetRow(0.0);
        double __cope_tmp1;
        if (__cope_tmp0.IsOk)
        {
            var row = __cope_tmp0.Value;
            __cope_tmp1 = 1.0;
        }
        else
        {
            var error = __cope_tmp0.Error;
            __cope_tmp1 = error switch { TableBoundsError.InvalidIndex(var index) => 2.0, TableBoundsError.OutOfBounds(var index, var rowCount) => rowCount, _ => throw new global::System.InvalidOperationException("Non-exhaustive match.") };
        }
        return __cope_tmp1;
    }

}
