<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Copeland.Profile.M1Evidence</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Copeland/Copeland.TS/Copeland.TS.csproj" />
    <ProjectReference Include="../../src/Machina.UI/Machina.Fonts/Machina.Fonts.csproj" />
  </ItemGroup>
</Project>
