// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public abstract record Choice
{
    protected Choice()
    {
    }

    public sealed record A : Choice
    {
        internal static A __Singleton { get; } = new();
    }

}

public static class CopelandModule
{
    public static Choice make()
    {
        return Choice.A.__Singleton;
    }

}
