// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public abstract record Choice
{
    protected Choice()
    {
    }

    public sealed record A : Choice
    {
        internal static A __Singleton { get; } = new();
    }

    public sealed record B : Choice
    {
        internal static B __Singleton { get; } = new();
    }

}

public static class CopelandModule
{
    public static Choice make()
    {
        Choice c = Choice.B.__Singleton;
        return c;
    }

}
