// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public abstract record Choice
{
    protected Choice()
    {
    }

    public sealed record A : Choice;

    public sealed record B : Choice;

}

public static class CopelandModule
{
    public static Choice[] choices()
    {
        Choice[] xs = new Choice[] { new Choice.A(), new Choice.B() };
        return xs;
    }

}
