// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public abstract record Choice
{
    protected Choice()
    {
    }

    public sealed record A : Choice
    {
        internal static A __Singleton { get; } = new();
    }

    public sealed record B : Choice
    {
        internal static B __Singleton { get; } = new();
    }

}

public static class CopelandModule
{
    public static double value(Choice choice)
    {
        return choice switch { Choice.A _ => 1.0, Choice.B _ => 2.0, _ => throw new global::System.InvalidOperationException("Non-exhaustive match.") };
    }

}
