// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public abstract record Shape
{
    protected Shape()
    {
    }

    public sealed record Point : Shape;

    public sealed record Circle(double radius) : Shape;

    public sealed record Rect(double width, double height) : Shape;

}

public static class CopelandModule
{
    public static double area(Shape shape)
    {
        return shape switch { Shape.Point _ => 0.0, Shape.Circle(var radius) => (radius * radius), Shape.Rect(var width, var height) => (width * height), _ => throw new global::System.InvalidOperationException("Non-exhaustive match.") };
    }

}
