// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public readonly struct CopeResult<TValue, TError>
{
    private readonly TValue _value;
    private readonly TError _error;
    public bool IsOk { get; }

    public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException("Result has no value.");
    public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException("Result has no error.");

    private CopeResult(bool isOk, TValue value, TError error)
    {
        IsOk = isOk;
        _value = value;
        _error = error;
    }

    public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);
    public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);
}

public sealed class __CopeRecord_r1
{
    internal __CopeRecord_r1(__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 value0)
    {
        __field_r1_002Ef0 = value0;
    }

    internal __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 __field_r1_002Ef0 { get; }
}


public abstract record Choice
{
    protected Choice()
    {
    }

    public sealed record Value(__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 operation) : Choice;

}
public abstract record Failure
{
    protected Failure()
    {
    }

    public sealed record Bad : Failure;

}

public delegate double __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4(double value0);

internal sealed class __CopeCapturedCallableEnvironment___cope_arrow_0
{
    private readonly double _capture0;

    internal __CopeCapturedCallableEnvironment___cope_arrow_0(double capture0)
    {
        _capture0 = capture0;
    }

    internal double Invoke(double value0) => CopelandModule.__cope_arrow_0(_capture0, value0);
}

public static class CopelandModule
{
    public static double increment(double value)
    {
        return (value + 1.0);
    }

    public static double apply(__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 operation, double value)
    {
        return operation(value);
    }

    public static double __cope_arrow_0(double @base, double value)
    {
        return (@base + value);
    }

    public static __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 makeAdder(double @base)
    {
        return (__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4)new __CopeCapturedCallableEnvironment___cope_arrow_0(@base).Invoke;
    }

    public static double identity__primitive_number__8F3BAE8FF0D9F338(double value)
    {
        return value;
    }

    public static double __cope_arrow_1(double value)
    {
        return (value * 2.0);
    }

    public static double __cope_arrow_2(double value)
    {
        double adjusted = (value + 1.0);
        return (adjusted * 2.0);
    }

    public static double main()
    {
        __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 named = (__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4)increment;
        __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 closed = (__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4)identity__primitive_number__8F3BAE8FF0D9F338;
        __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 @double = (__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4)__cope_arrow_1;
        __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 block = (__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4)__cope_arrow_2;
        __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4 escaped = makeAdder(10.0);
        __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4[] stored = new __CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4[] { named, closed, @double, block, escaped };
        var __cope_record_init_0 = escaped;
        __CopeRecord_r1 box = new __CopeRecord_r1(__cope_record_init_0);
        Choice choice = new Choice.Value((box).__field_r1_002Ef0);
        CopeResult<__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4, Failure> result = CopeResult<__CopeCallable_C5824F8FD649414A60AE68CA699C63F945601237CE3C95C1DE70447C5A565CE4, Failure>.Ok(choice switch { Choice.Value(var operation) => operation, _ => throw new global::System.InvalidOperationException("Non-exhaustive match.") });
        var __cope_tmp1 = result;
        double __cope_tmp2;
        if (__cope_tmp1.IsOk)
        {
            var operation = __cope_tmp1.Value;
            __cope_tmp2 = apply(operation, 1.0);
        }
        else
        {
            var error = __cope_tmp1.Error;
            __cope_tmp2 = 0.0;
        }
        return __cope_tmp2;
    }

}
