<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Integrations/Aurelian.Games/Aurelian.Games.csproj" />
    <ProjectReference Include="../../../src/Aurelian/Aurelian.Runtime/Aurelian.Runtime.csproj" />
    <ProjectReference Include="../../../src/Integrations/Aurelian.Playtesting/Aurelian.Playtesting.csproj" />
    <ProjectReference Include="../../../../Dominatus/src/Dominatus.OptFlow/Dominatus.OptFlow.csproj" />
    <ProjectReference Include="../../../../Dominatus/src/Dominatus.OptFlow.Generators/Dominatus.OptFlow.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    <ProjectReference Include="../../../src/Integrations/Aurelian.GameMenus/Aurelian.GameMenus.csproj" />
    <PackageReference Include="Silk.NET.Input" />
    <PackageReference Include="Silk.NET.Windowing" />
    <PackageReference Include="SkiaSharp" />
    <ProjectReference Include="../../../src/Aurelian/Aurelian.Graphics/Aurelian.Graphics.csproj" />
    <ProjectReference Include="../../../src/Aurelian/Aurelian.Shaders/Aurelian.Shaders.csproj" />
    <ProjectReference Include="../../../src/Copeland/Copeland.TS/Copeland.TS.csproj" />
    <ProjectReference Include="../../../src/Integrations/InputMan.Aurelian/InputMan.Aurelian.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets/CompiledDiffuseProbe.v.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../../src/Aurelian/Aurelian.Shaders/Assets/Solid3D.v.ts" Link="Assets/Solid3D.v.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../../src/Aurelian/Aurelian.Shaders/Assets/Lighting3D.v.ts" Link="Assets/Lighting3D.v.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../../src/Aurelian/Aurelian.Shaders/Assets/TemporalGeometry.v.ts" Link="Assets/TemporalGeometry.v.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../../src/Aurelian/Aurelian.Shaders/Assets/CompiledDiffuseLighting.v.ts" Link="Assets/CompiledDiffuseLighting.v.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../../src/Aurelian/Aurelian.Shaders/Assets/AnalyticShape2D.v.ts" Link="Assets/AnalyticShape2D.v.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../../src/Aurelian/Aurelian.Shaders/Assets/MsdfText.v.ts" Link="Assets/MsdfText.v.ts" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../../src/Aurelian/Aurelian.Assets/Defaults/Fonts/CrimsonText-Regular.ttf" Link="Assets/CrimsonText-Regular.ttf" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../../src/Aurelian/Aurelian.Assets/Defaults/Fonts/SpaceMono-Regular.ttf" Link="Assets/SpaceMono-Regular.ttf" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../../src/Aurelian/Aurelian.Assets/Defaults/Fonts/*.LICENSE.txt" Link="Assets/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
