<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <PackageId>Copeland.TS.Templates</PackageId>
    <PackageVersion>$(CopelandToolchainVersion)</PackageVersion>
    <PackageType>Template</PackageType>
    <PackageTags>dotnet-new;copeland;typescript</PackageTags>
    <Description>Starter templates for Copeland TS projects.</Description>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="templates\**\*" Pack="true" PackagePath="content" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
