// TEMPLATE-BOOTSTRAP-M0 canonical project template.
// Copeland templates are normal typed Copeland programs. TypeScript computes
// project values; template TS-XML document materialization is not yet supported.

export template BootstrapTemplate(static name: string): ProjectTree {
    const packageVersion = "0.1.0-preview.1-tsxml.1";
    const projectFile = `${name}/${name}.csproj`;

    return project([
        textFile(`${name}.slnx`, `<Solution>\n  <Project Path="${projectFile}" />\n</Solution>\n`),
        textFile("README.md", `# ${name}\n\nA Copeland TS + .NET 10 project generated by BootstrapTemplate.\n\nRun npm install, dotnet build, dotnet test, then dotnet run.\n`),
        directory(name, [
            textFile(`${name}.csproj`, `<Project Sdk="Microsoft.NET.Sdk">\n  <PropertyGroup>\n    <OutputType>Exe</OutputType>\n    <TargetFramework>net10.0</TargetFramework>\n    <RootNamespace>${name}</RootNamespace>\n    <ImplicitUsings>enable</ImplicitUsings>\n    <Nullable>enable</Nullable>\n    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>\n    <CopelandRequiredVersion>${packageVersion}</CopelandRequiredVersion>\n  </PropertyGroup>\n  <ItemGroup>\n    <PackageReference Include="Copeland.TS.Sdk" Version="${packageVersion}" PrivateAssets="all" />\n    <CopelandNpmContract Include="contracts/lodash-es.json" />\n  </ItemGroup>\n</Project>\n`),
            textFile("package.json", `{\n  "name": "${name}",\n  "version": "${packageVersion}",\n  "private": true,\n  "type": "module",\n  "dependencies": { "lodash-es": "4.18.1" }\n}\n`),
            textFile("tsconfig.tsx", `import { defineTypeScriptWorkspace } from "copeland/workspace";\n\nexport default defineTypeScriptWorkspace({\n    ownership: "strict",\n    tscl: {\n        project: "./${name}.csproj",\n        include: ["src/**", "tests/**"],\n        types: ["TextDocuments"]\n    }\n});\n`),
            sourceFile("Program.cs", `Console.WriteLine(${name}.Copeland.CopelandProject.greeting("Copeland"));\nConsole.WriteLine("lodash-es says: helloFromNpm");\n`),
            directory("contracts", [textFile("lodash-es.json", `{\n  "schemaVersion": 1,\n  "package": "lodash-es",\n  "version": "4.18.1",\n  "materialized": true,\n  "exports": []\n}\n`)]),
            directory("src", [
                sourceFile("Program.ts", `using System;\nusing ${name};\n\nexport enum GreetingStyle { Friendly, Formal }\n\nexport record Greeting { recipient: string; message: string; }\n\nexport function greeting(name: string): string {\n    return String.Concat(Helper.Decorate(name), " through System.String");\n}\n`),
                sourceFile("GreetingDocument.tsx", `import { Greeting, GreetingStyle } from "./Program";\n\nexport function greetingDocument(name: string): Document {\n    const style: GreetingStyle = GreetingStyle.Friendly;\n    const message: string = match style {\n        Friendly => "Hello",\n        Formal => "Greetings",\n    };\n    const initial: Greeting = { recipient: name, message };\n    const updated: Greeting = initial with { recipient: "Copeland" };\n    return <Document><Paragraph>{updated.message}, {updated.recipient}</Paragraph></Document>;\n}\n`),
                sourceFile("Helper.cs", `namespace ${name};\n\npublic static class Helper\n{\n    public static string Decorate(string value)\n    {\n        return $"C# says hello to {value}";\n    }\n}\n`)
            ]),
            directory("tests", [sourceFile("GreetingDocument.tsxtest", `using Xunit;\n\nenum TestStyle { Friendly, Formal }\nrecord TestGreeting { message: string; recipient: string; }\n\n[Fact]\nexport function enum_match_and_with_work(): void {\n    const style: TestStyle = TestStyle.Friendly;\n    const message: string = match style { Friendly => "Hello", Formal => "Greetings" };\n    const initial: TestGreeting = { message, recipient: "Ada" };\n    const updated: TestGreeting = initial with { recipient: "Copeland" };\n    Assert.True(updated.message == "Hello");\n}\n`)])
        ])
    ]);
}
