using Copeland.Script.Diagnostics;
using Copeland.Script.Mir;

namespace Copeland.Script.Codegen.CSharp;

public static class CSharpBackend
{
    public static CSharpCompilation Emit(MirProgram program)
    {
        var diagnostics = new List<Diagnostic>();
        if (program.Enums.Count > 0)
        {
            diagnostics.Add(new Diagnostic("COPE-CS-0001", "Unsupported MIR feature: enum declarations.", 0, 0));
            return new CSharpCompilation(string.Empty, diagnostics);
        }

        var writer = new CSharpTextWriter();

        var fallible = program.Functions.Any(f => f.IsFallible);
        var needsUnit = program.Functions.Any(f => f.IsFallible && f.ReturnType.Name == "void");
        var errorTypes = program.Functions.Where(f => f.ErrorType is not null).Select(f => f.ErrorType!.Name).Distinct(StringComparer.Ordinal).OrderBy(n => n, StringComparer.Ordinal).ToArray();

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("namespace Copeland.Generated;");
        writer.WriteLine();

        if (needsUnit)
        {
            writer.WriteLine("public readonly record struct CopeUnit"); writer.WriteLine("{"); writer.Indent();
            writer.WriteLine("public static readonly CopeUnit Value = new();"); writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
        }

        if (fallible)
        {
            writer.WriteLine("public readonly struct CopeResult<TValue, TError>"); writer.WriteLine("{"); writer.Indent();
            writer.WriteLine("private readonly TValue _value;"); writer.WriteLine("private readonly TError _error;"); writer.WriteLine("public bool IsOk { get; }"); writer.WriteLine();
            writer.WriteLine("public TValue Value => IsOk ? _value : throw new global::System.InvalidOperationException(\"Result has no value.\");");
            writer.WriteLine("public TError Error => !IsOk ? _error : throw new global::System.InvalidOperationException(\"Result has no error.\");"); writer.WriteLine();
            writer.WriteLine("private CopeResult(bool isOk, TValue value, TError error)"); writer.WriteLine("{"); writer.Indent();
            writer.WriteLine("IsOk = isOk;"); writer.WriteLine("_value = value;"); writer.WriteLine("_error = error;"); writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
            writer.WriteLine("public static CopeResult<TValue, TError> Ok(TValue value) => new(true, value, default!);");
            writer.WriteLine("public static CopeResult<TValue, TError> Err(TError error) => new(false, default!, error);");
            writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
        }

        foreach (var e in errorTypes)
            writer.WriteLine($"public readonly record struct {CSharpNameMangler.Mangle(e)};");
        if (errorTypes.Length > 0) writer.WriteLine();

        writer.WriteLine("public static class CopelandModule"); writer.WriteLine("{"); writer.Indent();
        foreach (var function in program.Functions)
            EmitFunction(writer, function, diagnostics);
        writer.Unindent(); writer.WriteLine("}");

        return new CSharpCompilation(writer.ToString(), diagnostics);
    }

    private static void EmitFunction(CSharpTextWriter writer, MirFunction function, List<Diagnostic> diagnostics)
    {
        var fn = CSharpNameMangler.Mangle(function.Name);
        var returnType = FunctionReturnType(function);
        var parms = string.Join(", ", function.Parameters.Select(p => $"{MapType(p.Type)} {CSharpNameMangler.Mangle(p.Name)}"));
        writer.WriteLine($"public static {returnType} {fn}({parms})"); writer.WriteLine("{"); writer.Indent();
        var temp = 0;
        foreach (var stmt in function.Body) EmitStatement(writer, stmt, function, ref temp, diagnostics);
        writer.Unindent(); writer.WriteLine("}"); writer.WriteLine();
    }

    private static void EmitStatement(CSharpTextWriter writer, MirStatement stmt, MirFunction fn, ref int tempIndex, List<Diagnostic> diagnostics)
    {
        switch (stmt)
        {
            case MirVariableDeclarationStatement v:
                writer.WriteLine($"{MapType(v.Local.Type)} {CSharpNameMangler.Mangle(v.Local.Name)} = {EmitExpression(writer, v.Initializer, fn, ref tempIndex, diagnostics)};");
                break;
            case MirExpressionStatement e:
                writer.WriteLine($"{EmitExpression(writer, e.Expression, fn, ref tempIndex, diagnostics)};");
                break;
            case MirReturnStatement r:
                if (fn.IsFallible)
                {
                    if (r.Expression is null)
                        writer.WriteLine($"return CopeResult<{MapSuccessType(fn.ReturnType)}, {MapType(fn.ErrorType!)}>.Ok({(fn.ReturnType.Name == "void" ? "CopeUnit.Value" : "default!")});");
                    else
                        writer.WriteLine($"return CopeResult<{MapSuccessType(fn.ReturnType)}, {MapType(fn.ErrorType!)}>.Ok({EmitExpression(writer, r.Expression, fn, ref tempIndex, diagnostics)});");
                }
                else writer.WriteLine(r.Expression is null ? "return;" : $"return {EmitExpression(writer, r.Expression, fn, ref tempIndex, diagnostics)};");
                break;
            case MirIfStatement i:
                writer.WriteLine($"if ({EmitExpression(writer, i.Condition, fn, ref tempIndex, diagnostics)})"); writer.WriteLine("{"); writer.Indent();
                foreach (var s in i.ThenStatements) EmitStatement(writer, s, fn, ref tempIndex, diagnostics);
                writer.Unindent(); writer.WriteLine("}");
                if (i.ElseStatements is not null){ writer.WriteLine("else"); writer.WriteLine("{"); writer.Indent(); foreach(var s in i.ElseStatements) EmitStatement(writer,s,fn,ref tempIndex,diagnostics); writer.Unindent(); writer.WriteLine("}");}
                break;
            default:
                diagnostics.Add(new Diagnostic("COPE-CS-0001", $"Unsupported MIR statement: {stmt.GetType().Name}", 0, 0));
                break;
        }
    }

    private static string EmitExpression(CSharpTextWriter writer, MirExpression expr, MirFunction fn, ref int tempIndex, List<Diagnostic> diagnostics)
    {
        return expr switch
        {
            MirLiteralExpression l => CSharpLiteralWriter.Write(l.Value),
            MirVariableExpression v => CSharpNameMangler.Mangle(v.Name),
            MirAssignmentExpression a => $"{CSharpNameMangler.Mangle(a.Name)} = {EmitExpression(writer, a.Expression, fn, ref tempIndex, diagnostics)}",
            MirUnaryExpression u => $"{u.Operator}{EmitExpression(writer, u.Operand, fn, ref tempIndex, diagnostics)}",
            MirBinaryExpression b => $"({EmitExpression(writer, b.Left, fn, ref tempIndex, diagnostics)} {(b.Operator is "===" ? "==" : b.Operator is "!==" ? "!=" : b.Operator)} {EmitExpression(writer, b.Right, fn, ref tempIndex, diagnostics)})",
            MirCallExpression c when c.IsFallible && c.IsPropagated && c.ErrorType is not null => EmitPropagation(writer, c, fn, ref tempIndex, diagnostics),
            MirCallExpression c => $"{CSharpNameMangler.Mangle(c.FunctionName)}({string.Join(", ", EmitArguments(c.Arguments, writer, fn, ref tempIndex, diagnostics))})",
            MirArrayExpression a => $"new {MapType(a.Type)} {{ {string.Join(", ", EmitArguments(a.Elements, writer, fn, ref tempIndex, diagnostics))} }}",
                        MirEnumValueExpression => AddUnsupportedExpression("enum value", diagnostics),
            MirMatchExpression => AddUnsupportedExpression("match expression", diagnostics),
            _ => AddUnsupportedExpression(expr.GetType().Name, diagnostics)
        };
    }


    private static string AddUnsupportedExpression(string feature, List<Diagnostic> diagnostics)
    {
        diagnostics.Add(new Diagnostic("COPE-CS-0001", $"Unsupported MIR expression: {feature}", 0, 0));
        return "default!";
    }

    private static string EmitPropagation(CSharpTextWriter writer, MirCallExpression c, MirFunction fn, ref int tempIndex, List<Diagnostic> diagnostics)
    {
        if (!fn.IsFallible || fn.ErrorType is null)
        {
            diagnostics.Add(new Diagnostic("COPE-CS-0002", "Propagation used in non-fallible function.", 0, 0));
            return "default!";
        }

        var t = $"__cope_tmp{tempIndex++}";
        var call = $"{CSharpNameMangler.Mangle(c.FunctionName)}({string.Join(", ", EmitArguments(c.Arguments, writer, fn, ref tempIndex, diagnostics))})";
        writer.WriteLine($"var {t} = {call};");
        writer.WriteLine($"if (!{t}.IsOk)"); writer.WriteLine("{"); writer.Indent();
        writer.WriteLine($"return CopeResult<{MapSuccessType(fn.ReturnType)}, {MapType(fn.ErrorType)}>.Err({t}.Error);"); writer.Unindent(); writer.WriteLine("}");
        return $"{t}.Value";
    }

    private static string FunctionReturnType(MirFunction fn)
        => fn.IsFallible ? $"CopeResult<{MapSuccessType(fn.ReturnType)}, {MapType(fn.ErrorType!)}>" : MapType(fn.ReturnType);
    private static List<string> EmitArguments(IReadOnlyList<MirExpression> arguments, CSharpTextWriter writer, MirFunction fn, ref int tempIndex, List<Diagnostic> diagnostics)
    {
        var values = new List<string>(arguments.Count);
        foreach (var argument in arguments)
            values.Add(EmitExpression(writer, argument, fn, ref tempIndex, diagnostics));

        return values;
    }
    private static string MapSuccessType(MirType t) => t.Name == "void" ? "CopeUnit" : MapType(t);
    private static string MapType(MirType t) => t.Name.EndsWith("[]", StringComparison.Ordinal) ? MapType(new MirType(t.Name[..^2])) + "[]" : t.Name switch
    {
        "number" => "double",
        "string" => "string",
        "boolean" => "bool",
        "void" => "void",
        _ => CSharpNameMangler.Mangle(t.Name)
    };
}
