<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Machina.TextConformance</AssemblyName>
    <RootNamespace>Machina.TextConformance</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Machina.UI/Machina.Fonts/Machina.Fonts.csproj" />
    <ProjectReference Include="../../src/Machina.UI/Machina.Fonts.AvaloniaOracle/Machina.Fonts.AvaloniaOracle.csproj" />
  </ItemGroup>
</Project>
