<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Aurelian.Actuation/Aurelian.Actuation.csproj" />
    <PackageReference Include="Dominatus.Core" />
    <PackageReference Include="Dominatus.OptFlow" />
  </ItemGroup>
</Project>
