<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Machina.Presentation</AssemblyName>
    <RootNamespace>Machina.Presentation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Machina.Core/Machina.Core.csproj" />
    <ProjectReference Include="../Machina.Fonts/Machina.Fonts.csproj" />
    <ProjectReference Include="../Machina.Layout/Machina.Layout.csproj" />
    <ProjectReference Include="../Machina.Standard/Machina.Standard.csproj" />
    <ProjectReference Include="../Machina.Runtime/Machina.Runtime.csproj" />
  </ItemGroup>
</Project>
