[lock]
format = 1

[[package]]
ID = 'npm:react-dom@19.2.7'
Name = 'react-dom'
Version = '19.2.7'
Source = 'npm'
Integrity = 'sha512-t0BRVXvbiE/o20Hfw669rLbMCDWtYZLvmJigy2f0MxsXF+71pxhR3xOkspmsO8h3ZlNzyibAmtCa3l4lYKk6gQ=='
Repo = ''
Rev = ''
TreeHash = ''
Path = ''
Workspace = ''
Hash = 'sha256:e47bae602149b38b90b452c89e53d2d60639fee09361d90374983a6aac62739e'

[[package]]
ID = 'npm:react@19.2.7'
Name = 'react'
Version = '19.2.7'
Source = 'npm'
Integrity = 'sha512-HNe9WslTbXmFK8o8cmwgAeJFSBvt1bPdHCVKtaaV+WlAN36mpT4hcRpwbf3fY56ar2oIXzsBpOAiIRHAdY0OlQ=='
Repo = ''
Rev = ''
TreeHash = ''
Path = ''
Workspace = ''
Hash = 'sha256:d0065884db7670ffb89046826995cf0d7754a31653d23908532e52671bf83d7d'

[[package]]
ID = 'npm:scheduler@0.27.0'
Name = 'scheduler'
Version = '0.27.0'
Source = 'npm'
Integrity = 'sha512-eNv+WrVbKu1f3vbYJT/xtiF5syA5HPIMtf9IgY/nKg0sWqzAUEvqY/xm7OcZc/qafLx/iO9FgOmeSAp4v5ti/Q=='
Repo = ''
Rev = ''
TreeHash = ''
Path = ''
Workspace = ''
Hash = 'sha256:ab26ce35ce4032f04b78cfc5bbb4cfe13358e9fe7a5433a8aa6315c3debc5095'

[[package]]
ID = 'path:runtime#c3430e17521727db604269ad5f27c31178f4d6f78fe360113809691f1596dd6a'
Name = '@copeland/browser-v1'
Version = '1.0.0'
Source = 'path'
Integrity = ''
Repo = ''
Rev = ''
TreeHash = ''
Path = 'runtime'
Workspace = ''
Hash = 'sha256:c3430e17521727db604269ad5f27c31178f4d6f78fe360113809691f1596dd6a'

[[edge]]
From = 'copeland-table-derivation-browser-proof:target:browser'
To = 'npm:react-dom@19.2.7'
Kind = 'runtime'
Optional = false

[[edge]]
From = 'copeland-table-derivation-browser-proof:target:browser'
To = 'npm:react@19.2.7'
Kind = 'runtime'
Optional = false

[[edge]]
From = 'copeland-table-derivation-browser-proof:target:browser'
To = 'path:runtime#c3430e17521727db604269ad5f27c31178f4d6f78fe360113809691f1596dd6a'
Kind = 'runtime'
Optional = false

[[edge]]
From = 'npm:react-dom@19.2.7'
To = 'npm:scheduler@0.27.0'
Kind = 'runtime'
Optional = false

[[target]]
Package = 'copeland-table-derivation-browser-proof'
Name = 'browser'
Export = '.'
Entry = 'src/Main.tsx'
Runtime = 'dist/browser/main.js'
Types = 'dist/browser/main.d.ts'
