<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CtsJitM0</AssemblyName>
    <RootNamespace>CtsJitM0</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Copeland/Copeland.TS/Copeland.TS.csproj" />
    <ProjectReference Include="../../src/Copeland/Copeland.TS.Backend.CSharp/Copeland.TS.Backend.CSharp.csproj" />
    <ProjectReference Include="../../src/Copeland/Copeland.TS.Backend.JavaScript/Copeland.TS.Backend.JavaScript.csproj" />
  </ItemGroup>
</Project>
