<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Machina.Fonts.Tooling.Unit.Tests</AssemblyName>
    <RootNamespace>Machina.Fonts.Tooling.Unit.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Machina.Fonts.Tooling/Machina.Fonts.Tooling.csproj" />
  </ItemGroup>
</Project>
