//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Copeland.TS.Workspace")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.1.0-preview.1+8bc7dbe101c916eb63f750d759ea2f1956fe47e0")]
[assembly: System.Reflection.AssemblyProductAttribute("Copeland.TS.Workspace")]
[assembly: System.Reflection.AssemblyTitleAttribute("Copeland.TS.Workspace")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.1.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

