// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public abstract record Shape
{
    protected Shape()
    {
    }

    public sealed record Circle(double radius) : Shape;

}

public static class CopelandModule
{
    public static Shape make()
    {
        return new Shape.Circle(10.0);
    }

}
