// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public abstract record Choice
{
    protected Choice()
    {
    }

    public sealed record A : Choice;

}

public static class CopelandModule
{
    public static Choice make()
    {
        return new Choice.A();
    }

}
