// <auto-generated />
#nullable enable

namespace Copeland.Generated;

public abstract record Status
{
    protected Status()
    {
    }

    public sealed record Idle : Status;

    public sealed record Loaded(string name) : Status;

}

public static class CopelandModule
{
    public static string label(Status status)
    {
        return status switch { Status.Idle _ => "idle", Status.Loaded(var name) => name, _ => throw new global::System.InvalidOperationException("Non-exhaustive match.") };
    }

}
