<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Copeland.Workspace.M0</AssemblyName>
    <RootNamespace>Copeland.Workspace.M0</RootNamespace>
    <CopelandTaskAssembly>$(MSBuildProjectDirectory)\..\..\..\src\Copeland\Copeland.TS.MSBuild\bin\$(Configuration)\net10.0\Copeland.TS.MSBuild.dll</CopelandTaskAssembly>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Copeland\Copeland.TS.MSBuild\Copeland.TS.MSBuild.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Import Project="obj\copeland\workspace\tscl-files.generated.props" Condition="Exists('obj\copeland\workspace\tscl-files.generated.props')" />
  <Import Project="..\..\..\src\Copeland\Copeland.TS.MSBuild\build\Copeland.TS.Sdk.targets" />
</Project>
